package com.hodi.infra.coop;

import com.hodi.common.AppConstant;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.type.SqlTypes;

import java.math.BigDecimal;
import java.time.OffsetDateTime;

/**
 * One payment Co-op has told us about, matched or not.
 *
 * <h2>Separate from a booking payment on purpose</h2>
 *
 * <p>A statement is "money arrived"; a payment is "this booking has been paid". Most of the time they are the
 * same event, and the entire value of this table is the times they are not — a mistyped reference, a walk-in
 * payer, a deposit against a unit cancelled last week.
 *
 * <h2>refNo is the idempotency key, and the index is the guarantee</h2>
 *
 * <p>Co-op retries anything it does not get a clean answer to within thirty seconds. A timeout on our side is
 * indistinguishable from a refusal on theirs, so the same money arrives twice — and the second arrival must be
 * recognised as the first. A "have I seen this?" check inside the service loses that race exactly the way the
 * booking check does; the unique index does not.
 */
@Entity
@Table(name = "coop_statements")
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
public class CoopStatement {

    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "ref_no", nullable = false, length = 64) private String refNo;
    @Column(name = "trace_id", length = 64) private String traceId;
    /** The bank's own transaction id for the posting. Searchable from the statements screen, not shown. */
    @Column(length = 64) private String ft;
    /** Ours, returned to Co-op as the RRN. Generated once and kept, so a retry echoes the same value. */
    @Column(name = "our_reference", nullable = false, unique = true, length = 16) private String ourReference;

    @Column(name = "trans_type", nullable = false, length = 48) private String transType;
    /** Which of our accounts it landed in, resolved from {@code accountIdentifier}. Null when we do not know it. */
    @Column(name = "payment_account_id") private Long paymentAccountId;
    @Column(name = "account_identifier", length = 64) private String accountIdentifier;

    /** What the payer typed. The reason this table exists is that this is often wrong. */
    @Column(length = 64) private String reference;

    @Column(nullable = false, precision = 15, scale = 2) private BigDecimal amount;
    @Column(nullable = false, length = 3) @Builder.Default private String currency = "KES";
    @Column(name = "phone_no", length = 32) private String phoneNo;
    @Column(name = "customer_name", length = 160) private String customerName;
    @Column(name = "paid_at") private OffsetDateTime paidAt;

    /** The payload as it arrived. JSONB, so a reconciliation query can reach a field the columns do not. */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "raw_payload", columnDefinition = "jsonb") private String rawPayload;

    @Column(nullable = false, length = 16)
    @Builder.Default private String state = AppConstant.STATEMENT_UNMAPPED;

    @Column(name = "mapped_payment_id") private Long mappedPaymentId;
    @Column(name = "mapped_booking_id") private Long mappedBookingId;
    @Column(name = "mapped_at") private OffsetDateTime mappedAt;
    @Column(name = "mapped_by", length = 64) private String mappedBy;
    /** Why it could not be placed automatically, in words a person can act on. */
    @Column(name = "unmapped_reason", columnDefinition = "TEXT") private String unmappedReason;

    @Column(name = "tenant_id") private Long tenantId;
    @Column(name = "institution_id") private Long institutionId;

    @Column(nullable = false) @Builder.Default private Integer status = AppConstant.STATUS_ACTIVE;
    @Column(name = "status_flag", nullable = false, length = 32)
    @Builder.Default private String statusFlag = AppConstant.FLAG_ACTIVE;

    /** Generated by the database from the references, the payer's words, name and phone. Never written. */
    @Column(name = "search_text", insertable = false, updatable = false) private String searchText;

    @CreationTimestamp @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;
    @UpdateTimestamp @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;
    @Column(name = "created_by", length = 64) private String createdBy;
    @Column(name = "updated_by", length = 64) private String updatedBy;

    public boolean isMapped() { return AppConstant.STATEMENT_MAPPED.equals(state); }
    public boolean isUnmapped() { return AppConstant.STATEMENT_UNMAPPED.equals(state); }
    public boolean isIgnored() { return AppConstant.STATEMENT_IGNORED.equals(state); }
    public boolean isAwaitingAccount() { return AppConstant.STATEMENT_NO_ACCOUNT.equals(state); }

    /**
     * The account this landed in is not one of ours yet.
     *
     * <p>Not the unused queue: nobody can place money whose account is unknown, a slip must not find it, and
     * a queue worker must not apply it to a booking in an organisation it may not belong to. It waits here
     * until the account is registered, then {@link #linkedTo} puts it through the matcher.
     */
    public void awaitingAccount(String reason) {
        this.state = AppConstant.STATEMENT_NO_ACCOUNT;
        this.unmappedReason = reason;
    }

    /** The account exists now: the credit takes its owner and goes back to being ordinary unplaced money. */
    public void linkedTo(com.hodi.modules.payments.PaymentAccount account, String by) {
        this.paymentAccountId = account.getId();
        this.accountIdentifier = account.getAccountNo();
        this.tenantId = account.getTenantId();
        this.institutionId = account.getInstitutionId();
        this.state = AppConstant.STATEMENT_UNMAPPED;
        this.unmappedReason = null;
        this.updatedBy = by;
    }

    /**
     * A person has decided this is not money for any booking — a refund that bounced back, a supplier's
     * transfer into the wrong account — and it should stop appearing as work.
     *
     * <p>It stays on record: the bank still says it happened, and the reference still blocks a second
     * arrival of the same money. Only unplaced credits can be set aside; a placed one is voided first.
     */
    public void setAside(String reason, String by) {
        this.state = AppConstant.STATEMENT_IGNORED;
        this.unmappedReason = reason;
        this.updatedBy = by;
    }

    /** Back to the queue from set-aside, when the person who set it aside was wrong. */
    public void restore(String by) {
        this.state = AppConstant.STATEMENT_UNMAPPED;
        this.unmappedReason = "Restored to the queue by " + by + ".";
        this.updatedBy = by;
    }

    /** The money has been credited to a booking as this payment. The one way a statement becomes MAPPED. */
    public void placedOn(Long paymentId, Long bookingId, String by) {
        this.state = AppConstant.STATEMENT_MAPPED;
        this.mappedPaymentId = paymentId;
        this.mappedBookingId = bookingId;
        this.mappedAt = OffsetDateTime.now();
        this.mappedBy = by;
        this.unmappedReason = null;
        this.updatedBy = by;
    }

    /**
     * The payment it was applied to is gone, so the money is unplaced again.
     *
     * <p>Back to the queue, never deleted: the bank still says it happened. The reference stays too, so the
     * same money cannot arrive a second time while a person is deciding what to do with the first.
     */
    public void release(String reason, String by) {
        this.state = AppConstant.STATEMENT_UNMAPPED;
        this.mappedPaymentId = null;
        this.mappedBookingId = null;
        this.mappedAt = null;
        this.mappedBy = null;
        this.unmappedReason = reason;
        this.updatedBy = by;
    }
}
