package com.hodi.modules.audit;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.OffsetDateTime;

/**
 * An append-only record of one mutation. No {@code status} or {@code updated_*} columns by design: an
 * audit row is written once and never edited or soft-deleted.
 *
 * <p>{@code actionId} carries the same value as the request's {@code X-Action-Id} header and the
 * {@code actionId} in every log line for that request, so the trail and the log file join up.
 */
@Entity
@Table(name = "audit_logs")
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
public class AuditLog {

    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "action_id", length = 64) private String actionId;
    @Column(name = "tenant_id") private Long tenantId;

    @Column(name = "actor_user_id") private Long actorUserId;

    /**
     * Which of the actor's profiles was active.
     *
     * <p>The user type and actor class recorded below are properties of a profile now, so without this the
     * trail says "a seller staff member did this" for somebody who also holds a platform profile, and
     * nothing says which hat they were wearing.
     */
    @Column(name = "actor_profile_id") private Long actorProfileId;
    @Column(name = "actor_username", length = 64) private String actorUsername;
    @Column(name = "actor_user_type", length = 32) private String actorUserType;
    /** Which population the actor belonged to, so a trail can be read without joining user_types. */
    @Column(name = "actor_class", length = 16) private String actorClass;
    /** The lending institution the actor belonged to, where they had one. */
    @Column(name = "institution_id") private Long institutionId;

    @Column(nullable = false, length = 64) private String operation;
    @Column(length = 128) private String entity;
    @Column(name = "entity_id") private Long entityId;

    @Column(nullable = false, length = 32)
    @Builder.Default
    private String outcome = "SUCCESS";

    // jsonb columns need an explicit JDBC type code: columnDefinition only drives DDL, so without
    // this Hibernate binds the String as varchar and Postgres refuses to cast it.
    @JdbcTypeCode(SqlTypes.JSON) @Column(name = "before_payload", columnDefinition = "jsonb")
    private String beforePayload;

    @JdbcTypeCode(SqlTypes.JSON) @Column(name = "after_payload", columnDefinition = "jsonb")
    private String afterPayload;

    @JdbcTypeCode(SqlTypes.JSON) @Column(name = "changed_fields", columnDefinition = "jsonb")
    private String changedFields;

    @Column(name = "ip_address", length = 64) private String ipAddress;
    @Column(name = "user_agent", length = 512) private String userAgent;

    @CreationTimestamp @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /**
     * Generated by Postgres (GENERATED ALWAYS AS … STORED) and backed by a pg_trgm GIN index.
     * Read-only from the application — the database owns it, so it cannot drift out of step with the row.
     */
    @Column(name = "search_text", insertable = false, updatable = false)
    private String searchText;
}
