-- ═════════════════════════════════════════════════════════════════════════════════════════════════
-- Development finance: where the money went, and when it will be finished
--
-- See claudedocs/DEVELOPMENT_FINANCE_AND_PROGRAMME_PLAN.md. The phase table already carried a budget, a
-- planned spend, a committed and a spent figure — typed into an editor and overwritten in place. That is a
-- snapshot, and "how has this project been consuming funds" is a question about time. This migration gives
-- the money a history.
--
-- <h2>A ledger, and the phase figures derived from it</h2>
--
-- `development_expenditures` is one row per cost event, dated, categorised and attributable. The phase's
-- `committed_amount` and `spent_amount` stop being typed: DevelopmentInventoryService recounts them from the
-- ledger, the way it already recounts every unit tally, so there is one writer. What was typed before today
-- becomes an opening line per phase — dated at the phase's start, referenced OPENING — so the ledger's total
-- equals the old column on day one and nothing anybody entered is lost.
--
-- <h2>Never edited, only voided</h2>
--
-- A cost report a lender has read must not quietly change. A wrong line is voided with a reason and stays,
-- exactly as a payment is. The views sum received lines only.
--
-- <h2>The facility, drawn</h2>
--
-- `facility_drawdowns` is the other half of "funds consumed": what the lender disbursed, dated. Drawn and
-- undrawn are then sums rather than guesses.
--
-- <h2>Categories are configuration</h2>
--
-- Eight are seeded; the platform adds, renames and suspends them the way progress milestones and property
-- types are maintained. A developer's own vocabulary is not refused.
-- ═════════════════════════════════════════════════════════════════════════════════════════════════

-- ── the vocabulary ───────────────────────────────────────────────────────────────────────────────

CREATE TABLE development_cost_categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(32)  NOT NULL UNIQUE,
    name        VARCHAR(120) NOT NULL,
    description TEXT,
    sort_order  INTEGER      NOT NULL DEFAULT 100,
    status      INTEGER      NOT NULL DEFAULT 1,
    status_flag VARCHAR(32)  NOT NULL DEFAULT 'Active',
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(64),
    updated_by  VARCHAR(64),
    CONSTRAINT ck_cost_category_code CHECK (code = upper(code))
);

INSERT INTO development_cost_categories (code, name, description, sort_order, created_by) VALUES
    ('LAND',              'Land',                    'Acquisition, transfer and title costs.', 10, 'migration'),
    ('CONSTRUCTION',      'Construction',            'The contractor: works, materials, certificates.', 20, 'migration'),
    ('PROFESSIONAL_FEES', 'Professional fees',       'Architects, engineers, quantity surveyors, project managers.', 30, 'migration'),
    ('STATUTORY',         'Statutory and approvals', 'Permits, county approvals, NEMA, connections.', 40, 'migration'),
    ('FINANCE_COSTS',     'Finance costs',           'Interest, arrangement and facility fees.', 50, 'migration'),
    ('MARKETING',         'Marketing and sales',     'Agents'' commissions, advertising, show houses.', 60, 'migration'),
    ('CONTINGENCY',       'Contingency',             'Drawn against the contingency allowance.', 70, 'migration'),
    ('OTHER',             'Other',                   'Anything the categories above do not name.', 100, 'migration');

-- ── the ledger ───────────────────────────────────────────────────────────────────────────────────

CREATE TABLE development_expenditures (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference       VARCHAR(16)  NOT NULL UNIQUE,

    development_id  BIGINT       NOT NULL REFERENCES developments (id),
    -- Null for a project-level cost: land, finance costs, marketing rarely belong to one phase.
    phase_id        BIGINT       REFERENCES development_phases (id),
    category_id     BIGINT       NOT NULL REFERENCES development_cost_categories (id),

    -- COMMITTED: a contract or certificate signed, money promised. SPENT: money out.
    kind            VARCHAR(16)  NOT NULL,
    amount          NUMERIC(15, 2) NOT NULL,
    currency        VARCHAR(3)   NOT NULL DEFAULT 'KES',
    -- When the cost was incurred, not when it was keyed in. The spend curve is drawn from this.
    incurred_on     DATE         NOT NULL DEFAULT CURRENT_DATE,

    payee           VARCHAR(160),
    -- The invoice, certificate or payment voucher number.
    reference_no    VARCHAR(64),
    notes           TEXT,
    -- The evidence, in the vault, where one was attached.
    document_id     BIGINT       REFERENCES vault_documents (id),

    -- Cached from the development so a list can scope without a join.
    tenant_id       BIGINT,
    institution_id  BIGINT,

    voided_at       TIMESTAMPTZ,
    voided_by       VARCHAR(64),
    void_reason     TEXT,

    status          INTEGER      NOT NULL DEFAULT 1,
    status_flag     VARCHAR(32)  NOT NULL DEFAULT 'Active',
    search_text     TEXT GENERATED ALWAYS AS (
        lower(coalesce(reference, '') || ' ' || coalesce(payee, '') || ' ' || coalesce(reference_no, '')
              || ' ' || coalesce(notes, ''))
    ) STORED,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      VARCHAR(64),
    updated_by      VARCHAR(64),

    CONSTRAINT ck_expenditure_kind CHECK (kind IN ('COMMITTED', 'SPENT')),
    CONSTRAINT ck_expenditure_amount CHECK (amount > 0),
    -- 1 recorded, 4 voided, 5 archived.
    CONSTRAINT ck_expenditure_status CHECK (status IN (1, 4, 5)),
    CONSTRAINT ck_expenditure_void CHECK (
        status <> 4 OR (voided_at IS NOT NULL AND void_reason IS NOT NULL)),
    CONSTRAINT ck_expenditure_owner CHECK ((institution_id IS NULL) OR (tenant_id IS NULL))
);

CREATE INDEX idx_expenditure_development ON development_expenditures (development_id, incurred_on DESC)
    WHERE status <> 5;
CREATE INDEX idx_expenditure_phase ON development_expenditures (phase_id) WHERE phase_id IS NOT NULL;
CREATE INDEX idx_expenditure_category ON development_expenditures (category_id);
CREATE INDEX idx_expenditure_search ON development_expenditures USING gin (search_text public.gin_trgm_ops);

-- ── the facility, drawn ──────────────────────────────────────────────────────────────────────────

CREATE TABLE facility_drawdowns (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference       VARCHAR(16)  NOT NULL UNIQUE,
    development_id  BIGINT       NOT NULL REFERENCES developments (id),

    amount          NUMERIC(15, 2) NOT NULL,
    currency        VARCHAR(3)   NOT NULL DEFAULT 'KES',
    drawn_on        DATE         NOT NULL DEFAULT CURRENT_DATE,
    -- The bank's disbursement advice or the drawdown request number.
    reference_no    VARCHAR(64),
    notes           TEXT,
    document_id     BIGINT       REFERENCES vault_documents (id),

    tenant_id       BIGINT,
    institution_id  BIGINT,

    voided_at       TIMESTAMPTZ,
    voided_by       VARCHAR(64),
    void_reason     TEXT,

    status          INTEGER      NOT NULL DEFAULT 1,
    status_flag     VARCHAR(32)  NOT NULL DEFAULT 'Active',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      VARCHAR(64),
    updated_by      VARCHAR(64),

    CONSTRAINT ck_drawdown_amount CHECK (amount > 0),
    CONSTRAINT ck_drawdown_status CHECK (status IN (1, 4, 5)),
    CONSTRAINT ck_drawdown_void CHECK (
        status <> 4 OR (voided_at IS NOT NULL AND void_reason IS NOT NULL)),
    CONSTRAINT ck_drawdown_owner CHECK ((institution_id IS NULL) OR (tenant_id IS NULL))
);

CREATE INDEX idx_drawdown_development ON facility_drawdowns (development_id, drawn_on DESC) WHERE status <> 5;

-- ── the typed figures become opening lines ───────────────────────────────────────────────────────

/*
 * One line per phase per kind, for every non-zero figure anybody typed. Filed under Other with the
 * reference OPENING, dated at the phase's start (or the project's, or when the phase was created), so the
 * ledger's total on day one is exactly the column it replaces.
 */
INSERT INTO development_expenditures (reference, development_id, phase_id, category_id, kind, amount,
                                      currency, incurred_on, reference_no, notes,
                                      tenant_id, institution_id, created_by, updated_by)
SELECT v.prefix || lpad(p.id::text, 10, '0'),
       p.development_id, p.id,
       (SELECT id FROM development_cost_categories WHERE code = 'OTHER'),
       v.kind, v.amount, p.currency,
       coalesce(p.actual_start_on, d.started_on, p.created_at::date),
       'OPENING',
       'Opening balance carried from the figure typed on the phase before the ledger existed.',
       d.tenant_id, d.institution_id, 'migration', 'migration'
  FROM development_phases p
  JOIN developments d ON d.id = p.development_id
  CROSS JOIN LATERAL (VALUES ('SPENT', p.spent_amount, 'OS'), ('COMMITTED', p.committed_amount, 'OC'))
       AS v(kind, amount, prefix)
 WHERE p.status <> 5
   AND v.amount IS NOT NULL
   AND v.amount > 0;

COMMENT ON COLUMN development_phases.spent_amount IS
    'Derived: the sum of SPENT lines in development_expenditures for this phase. Recounted by '
    'DevelopmentInventoryService on every ledger write; never typed.';
COMMENT ON COLUMN development_phases.committed_amount IS
    'Derived: the sum of COMMITTED lines in development_expenditures for this phase. Never typed.';

-- ── the views ────────────────────────────────────────────────────────────────────────────────────

/*
 * One row per development: the money as it stands, and the programme against its promise.
 *
 * Every figure is a sum over the ledger, the drawdowns, the phases and the booking balances, so the
 * finance panel, the report and the comparison table read one definition of each. Carries both owner
 * columns so the owner-scope predicate can be spliced onto it.
 */
CREATE VIEW v_development_finance AS
SELECT d.id                                                  AS development_id,
       d.reference,
       d.name                                                AS development_name,
       d.tenant_id,
       d.institution_id,
       coalesce(d.institution_name, d.tenant_name)           AS owner_name,
       d.currency,
       d.construction_status,
       d.percent_complete,
       d.started_on,
       d.projected_completion_on,
       d.actual_completion_on,
       d.units_total,
       d.units_available,
       d.units_reserved,
       d.units_sold,
       d.budget_amount,
       d.facility_amount,
       d.facility_reference,
       coalesce(ph.phase_budget, 0)                          AS phase_budget,
       coalesce(ph.planned_spend, 0)                         AS planned_spend,
       -- What should have been spent by now: the planned spend of every phase already due to finish.
       coalesce(ph.planned_to_date, 0)                       AS planned_to_date,
       coalesce(ex.committed, 0)                             AS committed,
       coalesce(ex.spent, 0)                                 AS spent,
       coalesce(dd.drawn, 0)                                 AS drawn,
       coalesce(bk.contracted, 0)                            AS contracted,
       coalesce(bk.collected, 0)                             AS collected,
       coalesce(bk.receivable, 0)                            AS receivable,
       coalesce(bk.overdue, 0)                               AS overdue,
       coalesce(bk.live_bookings, 0)                         AS live_bookings,
       ph.phases,
       -- The latest date any phase now expects to finish: what happened, else what is now expected, else
       -- what was promised.
       ph.forecast_on,
       coalesce(ph.phases_late, 0)                           AS phases_late,
       ph.worst_slippage_days,
       d.created_at
  FROM developments d
  LEFT JOIN LATERAL (
        SELECT count(*)                                                                  AS phases,
               sum(p.budget_amount)                                                      AS phase_budget,
               sum(p.planned_spend)                                                      AS planned_spend,
               sum(p.planned_spend) FILTER (WHERE p.planned_completion_on <= CURRENT_DATE) AS planned_to_date,
               max(coalesce(p.actual_completion_on, p.revised_completion_on,
                            p.planned_completion_on))                                    AS forecast_on,
               count(*) FILTER (WHERE p.actual_completion_on IS NULL
                                  AND coalesce(p.revised_completion_on, p.planned_completion_on)
                                      < CURRENT_DATE)                                    AS phases_late,
               max(coalesce(p.actual_completion_on, p.revised_completion_on)
                   - p.planned_completion_on)                                            AS worst_slippage_days
          FROM development_phases p
         WHERE p.development_id = d.id AND p.status <> 5
  ) ph ON true
  LEFT JOIN LATERAL (
        SELECT sum(e.amount) FILTER (WHERE e.kind = 'COMMITTED') AS committed,
               sum(e.amount) FILTER (WHERE e.kind = 'SPENT')     AS spent
          FROM development_expenditures e
         WHERE e.development_id = d.id AND e.status = 1
  ) ex ON true
  LEFT JOIN LATERAL (
        SELECT sum(f.amount) AS drawn
          FROM facility_drawdowns f
         WHERE f.development_id = d.id AND f.status = 1
  ) dd ON true
  LEFT JOIN LATERAL (
        SELECT sum(b.price_agreed) FILTER (WHERE b.state IN ('RESERVED', 'AGREED', 'COMPLETED')) AS contracted,
               sum(v.paid)                                                                     AS collected,
               sum(v.balance) FILTER (WHERE b.state IN ('RESERVED', 'AGREED'))                 AS receivable,
               sum(v.overdue) FILTER (WHERE b.state IN ('RESERVED', 'AGREED'))                 AS overdue,
               count(*) FILTER (WHERE b.state IN ('RESERVED', 'AGREED'))                       AS live_bookings
          FROM unit_bookings b
          JOIN v_booking_balances v ON v.booking_id = b.id
         WHERE b.development_id = d.id AND b.status <> 5
  ) bk ON true
 WHERE d.status <> 5;

COMMENT ON VIEW v_development_finance IS
    'One row per development: budget, planned spend to date, committed, spent, drawn, and the sales side '
    '(contracted, collected, receivable, overdue), plus the programme against its promise.';

/*
 * The spend curve: cumulative planned, committed and spent, month by month, per development.
 *
 * One row per development per month per series from the project's start (or its first cost) to now, so a
 * quiet month is a flat step rather than a gap. "Planned" is a step curve — the planned spend of each phase
 * lands in the month it was due to finish — which is honest about what the phase table records; a smooth
 * S-curve would be inventing a shape nobody entered.
 *
 * Carries the owner columns and development_id, in the chart shape (bucket, series, value), so the chart
 * engine can draw it for one development or, summed, for an organisation.
 */
CREATE VIEW v_chart_dev_spend AS
WITH months AS (
    SELECT d.id AS development_id, d.tenant_id, d.institution_id, m::date AS bucket
      FROM developments d
      CROSS JOIN LATERAL generate_series(
            date_trunc('month', coalesce(d.started_on,
                (SELECT min(e.incurred_on) FROM development_expenditures e WHERE e.development_id = d.id),
                CURRENT_DATE)),
            date_trunc('month', CURRENT_DATE),
            interval '1 month') AS m
     WHERE d.status <> 5
)
SELECT m.tenant_id, m.institution_id, m.development_id, m.bucket, 'Planned' AS series,
       (SELECT coalesce(sum(p.planned_spend), 0) FROM development_phases p
         WHERE p.development_id = m.development_id AND p.status <> 5
           AND p.planned_completion_on < m.bucket + interval '1 month') AS value
  FROM months m
UNION ALL
SELECT m.tenant_id, m.institution_id, m.development_id, m.bucket, 'Committed',
       (SELECT coalesce(sum(e.amount), 0) FROM development_expenditures e
         WHERE e.development_id = m.development_id AND e.status = 1 AND e.kind = 'COMMITTED'
           AND e.incurred_on < m.bucket + interval '1 month')
  FROM months m
UNION ALL
SELECT m.tenant_id, m.institution_id, m.development_id, m.bucket, 'Spent',
       (SELECT coalesce(sum(e.amount), 0) FROM development_expenditures e
         WHERE e.development_id = m.development_id AND e.status = 1 AND e.kind = 'SPENT'
           AND e.incurred_on < m.bucket + interval '1 month')
  FROM months m;

/* Where the money stands: what was allowed, what has gone, what the lender put in, what buyers have paid. */
CREATE VIEW v_chart_dev_funding AS
SELECT f.tenant_id, f.institution_id, f.development_id, NULL::date AS bucket, s.series, s.value
  FROM v_development_finance f
  CROSS JOIN LATERAL (VALUES
        ('Budget',    f.budget_amount),
        ('Spent',     f.spent),
        ('Drawn',     f.drawn),
        ('Collected', f.collected)
  ) AS s(series, value)
 WHERE s.value IS NOT NULL;

/*
 * Completion over time, from the percentage stakeholder posts recorded.
 *
 * The highest figure reported in each month. Only meaningful for one development — a percentage cannot be
 * summed across projects — so the catalogue marks it as drawn per development only.
 */
CREATE VIEW v_chart_dev_completion AS
SELECT u.tenant_id, u.institution_id, u.development_id,
       date_trunc('month', u.reported_on)::date AS bucket,
       'Complete'                                AS series,
       max(u.percent_complete)::numeric          AS value
  FROM listing_progress_updates u
 WHERE u.development_id IS NOT NULL
   AND u.percent_complete IS NOT NULL
   AND u.status <> 5
 GROUP BY 1, 2, 3, 4;

/*
 * The three existing development charts gain development_id, so each can be drawn for one project.
 * Appended, which is what CREATE OR REPLACE VIEW allows.
 */
CREATE OR REPLACE VIEW v_chart_unit_inventory AS
SELECT d.tenant_id,
       d.institution_id,
       NULL::date         AS bucket,
       s.series,
       s.value,
       d.id               AS development_id
  FROM developments d
  CROSS JOIN LATERAL (VALUES
        ('Available', d.units_available),
        ('Reserved',  d.units_reserved),
        ('Sold',      d.units_sold)
  ) AS s(series, value)
 WHERE d.status <> 5
   AND d.units_total > 0;

CREATE OR REPLACE VIEW v_chart_payments_by_month AS
SELECT p.tenant_id,
       p.institution_id,
       date_trunc('month', p.paid_on)::date AS bucket,
       'Received'                           AS series,
       sum(p.amount)                        AS value,
       p.development_id
  FROM payments p
 WHERE p.status = 1
 GROUP BY 1, 2, 3, 6;

CREATE OR REPLACE VIEW v_chart_bookings_by_month_state AS
SELECT b.tenant_id, b.institution_id, NULL::date AS bucket, b.state AS series, count(*) AS value,
       b.development_id
  FROM unit_bookings b
 WHERE b.status <> 5
 GROUP BY 1, 2, 4, 6;

DROP VIEW v_chart_bookings_by_state;
ALTER VIEW v_chart_bookings_by_month_state RENAME TO v_chart_bookings_by_state;
