-- ═════════════════════════════════════════════════════════════════════════════════════════════════
-- A unit is not just a label, a floor and a price
--
-- Two two-beds in the same block are not the same home. One has two balconies and the other has one; one has
-- an open-plan kitchen and the other a separate one; one has three baths and the other two. Until now the
-- model said everything about a unit came from its typology and only the price could differ, which made the
-- typology a lie for every scheme where it mattered — and every scheme where it matters is the one somebody is
-- choosing between two flats in.
--
-- <h2>Null means inherit, and that is the whole design</h2>
--
-- Every column here is nullable, and null means "as the typology says". A project of two hundred units where
-- eight differ stores eight rows with anything in these columns; the other hundred and ninety-two say nothing
-- and follow the typology.
--
-- That matters for more than storage. It means correcting the typology's bathroom count fixes it everywhere
-- it was inherited and nowhere it was deliberately overridden — which is the behaviour somebody expects and
-- the opposite of what copying the typology onto every unit at generation time would have given. It is also
-- the same rule the price already follows: a unit's own price, or the typology's.
--
-- <h2>Features are a set, not a column each</h2>
--
-- "Open-plan kitchen", "en-suite master", "corner unit", "own DSQ" — a list nobody can enumerate in advance
-- and which differs by developer. A column each would mean a migration every time a marketing team invented a
-- selling point.
--
-- So a catalogue and a join, the same shape `property_type_configs` and `progress_milestone_configs` already
-- use: the vocabulary is data, and adding to it is a config change rather than a deploy.
--
-- The inheritance rule is the same as the scalars, and it has to be stated because a set has no null: a unit
-- with any feature rows of its own has exactly those, and a unit with none inherits the typology's. That
-- allows "this one, without the open-plan kitchen" — which additive-only inheritance could not express.
-- ═════════════════════════════════════════════════════════════════════════════════════════════════

ALTER TABLE development_units
    ADD COLUMN bedrooms          SMALLINT,
    ADD COLUMN bathrooms         SMALLINT,
    ADD COLUMN balconies         SMALLINT,
    ADD COLUMN parking_spaces    SMALLINT,
    ADD COLUMN floor_area_sqm    NUMERIC(10, 2),
    ADD COLUMN balcony_area_sqm  NUMERIC(10, 2),
    -- Which way it looks, in the words a buyer uses: "north-east", "over the pool", "street".
    ADD COLUMN aspect            VARCHAR(64),
    -- What is different about this one. Not a copy of the typology's blurb — the reason to pick this flat.
    ADD COLUMN description       TEXT;

COMMENT ON COLUMN development_units.bathrooms IS
    'Null means the typology''s figure. Set only where this unit differs, so correcting the typology still '
    'fixes every unit that never disagreed with it.';

ALTER TABLE development_units ADD CONSTRAINT ck_unit_counts CHECK (
    (bedrooms IS NULL OR bedrooms >= 0)
    AND (bathrooms IS NULL OR bathrooms >= 0)
    AND (balconies IS NULL OR balconies >= 0)
    AND (parking_spaces IS NULL OR parking_spaces >= 0));

ALTER TABLE development_units ADD CONSTRAINT ck_unit_areas CHECK (
    (floor_area_sqm IS NULL OR floor_area_sqm > 0)
    AND (balcony_area_sqm IS NULL OR balcony_area_sqm >= 0));

-- ── the vocabulary ───────────────────────────────────────────────────────────────────────────────

CREATE TABLE unit_feature_configs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    code            VARCHAR(48)  NOT NULL UNIQUE,
    name            VARCHAR(120) NOT NULL,
    description     TEXT,
    /*
     * A grouping for the screen that lists them — KITCHEN, OUTDOOR, FIXTURES, PARKING, VIEW.
     *
     * Free text rather than a CHECK: this is a display heading, and refusing a developer's new category is
     * the sort of rule that turns into a support ticket rather than better data.
     */
    category        VARCHAR(32),
    sort_order      INTEGER      NOT NULL DEFAULT 100,

    status          INTEGER      NOT NULL DEFAULT 1,
    status_flag     VARCHAR(32)  NOT NULL DEFAULT 'Active',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      VARCHAR(64),
    updated_by      VARCHAR(64)
);

CREATE INDEX idx_unit_feature_order ON unit_feature_configs (sort_order) WHERE status <> 5;

-- A starting vocabulary, from what actually distinguishes one flat from the next in this market.
INSERT INTO unit_feature_configs (code, name, category, sort_order, created_by) VALUES
    ('OPEN_PLAN_KITCHEN', 'Open-plan kitchen',      'KITCHEN',  10, 'migration'),
    ('SEPARATE_KITCHEN',  'Separate kitchen',       'KITCHEN',  20, 'migration'),
    ('PANTRY',            'Pantry',                 'KITCHEN',  30, 'migration'),
    ('EN_SUITE_MASTER',   'En-suite master',        'FIXTURES', 40, 'migration'),
    ('ALL_EN_SUITE',      'All bedrooms en-suite',  'FIXTURES', 50, 'migration'),
    ('WALK_IN_CLOSET',    'Walk-in closet',         'FIXTURES', 60, 'migration'),
    ('DSQ',               'Domestic staff quarter', 'FIXTURES', 70, 'migration'),
    ('CORNER_UNIT',       'Corner unit',            'OUTDOOR',  80, 'migration'),
    ('GARDEN',            'Private garden',         'OUTDOOR',  90, 'migration'),
    ('ROOF_TERRACE',      'Roof terrace',           'OUTDOOR', 100, 'migration'),
    ('DOUBLE_VOLUME',     'Double-volume living',   'OUTDOOR', 110, 'migration'),
    ('COVERED_PARKING',   'Covered parking',        'PARKING', 120, 'migration');

-- ── what each unit, or each typology, actually has ───────────────────────────────────────────────

/*
 * One table for both, because the inheritance rule needs them comparable.
 *
 * A row belongs to a unit or to a typology, never both. A unit with any rows of its own has exactly those; a
 * unit with none inherits its typology's. Two tables would have made that rule a join across two shapes and
 * the "override with fewer features" case awkward to express.
 */
CREATE TABLE unit_features (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    unit_id         BIGINT REFERENCES development_units (id),
    unit_type_id    BIGINT REFERENCES development_unit_types (id),
    feature_code    VARCHAR(48) NOT NULL REFERENCES unit_feature_configs (code),

    status          INTEGER      NOT NULL DEFAULT 1,
    status_flag     VARCHAR(32)  NOT NULL DEFAULT 'Active',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      VARCHAR(64),

    CONSTRAINT ck_unit_feature_owner CHECK (
        (unit_id IS NOT NULL)::int + (unit_type_id IS NOT NULL)::int = 1)
);

-- One row per feature per owner: saying a flat has a pantry twice is not saying it twice as much.
CREATE UNIQUE INDEX uk_unit_feature_unit ON unit_features (unit_id, feature_code)
    WHERE unit_id IS NOT NULL AND status <> 5;
CREATE UNIQUE INDEX uk_unit_feature_type ON unit_features (unit_type_id, feature_code)
    WHERE unit_type_id IS NOT NULL AND status <> 5;

CREATE INDEX idx_unit_feature_lookup ON unit_features (unit_id) WHERE unit_id IS NOT NULL AND status <> 5;
CREATE INDEX idx_unit_feature_type_lookup ON unit_features (unit_type_id)
    WHERE unit_type_id IS NOT NULL AND status <> 5;
