-- Every message is recorded, and the person has an inbox.
--
-- A send used to be a log line. Now it is a row: what was said, to whom (masked for the eye, kept for
-- the retry), on which channel, whether the gateway took it, and what it was about. A failed send is
-- tried again with backoff; a switched-off channel is recorded as skipped and left alone.
--
-- And in-app is real: a row per person per message, read or not, with a link to the thing it concerns.

CREATE TABLE notification_log (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Null for a contact with no account: a walk-in buyer told by the phone on their booking.
    user_id             BIGINT,
    event_code          VARCHAR(40)  NOT NULL,
    purpose             VARCHAR(32)  NOT NULL,
    channel             VARCHAR(16)  NOT NULL,
    recipient           VARCHAR(160) NOT NULL,
    recipient_masked    VARCHAR(160) NOT NULL,
    subject             VARCHAR(255),
    -- The rendered body, so a retry sends what was composed, not a re-render of a fact that has moved on.
    payload             TEXT,
    -- QUEUED | SENT | FAILED | SKIPPED
    status              VARCHAR(12)  NOT NULL DEFAULT 'QUEUED',
    provider_reference  VARCHAR(64),
    error               TEXT,
    attempts            INTEGER      NOT NULL DEFAULT 0,
    next_attempt_at     TIMESTAMPTZ,
    about_type          VARCHAR(32),
    about_id            BIGINT,
    about_ref           VARCHAR(32),
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_attempt_at     TIMESTAMPTZ,
    sent_at             TIMESTAMPTZ,
    CONSTRAINT ck_notification_log_status CHECK (status IN ('QUEUED', 'SENT', 'FAILED', 'SKIPPED')),
    CONSTRAINT ck_notification_log_channel CHECK (channel IN ('EMAIL', 'SMS'))
);
CREATE INDEX idx_notification_log_retry ON notification_log (next_attempt_at) WHERE status = 'FAILED';
CREATE INDEX idx_notification_log_about ON notification_log (about_type, about_id, created_at DESC);
CREATE INDEX idx_notification_log_user ON notification_log (user_id, created_at DESC);
CREATE INDEX idx_notification_log_created ON notification_log (created_at DESC);

CREATE TABLE notifications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES users (id),
    event_code  VARCHAR(40)  NOT NULL,
    title       VARCHAR(255) NOT NULL,
    line        TEXT         NOT NULL,
    link        VARCHAR(255),
    about_type  VARCHAR(32),
    about_id    BIGINT,
    about_ref   VARCHAR(32),
    read_at     TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_notifications_user_unread ON notifications (user_id, created_at DESC) WHERE read_at IS NULL;
CREATE INDEX idx_notifications_user ON notifications (user_id, created_at DESC);
