-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- A seller applies, the bank decides.
--
-- The one route a seller could reach the platform by was a platform administrator typing them in
-- (TENANTS_CREATE). That stays — a bank officer onboarding somebody they are sitting with is a real
-- workflow — and this is the self-service route beside it.
--
-- The shape is the agent register's, because that already answers the hard parts: the applicant gets an
-- account immediately so they can finish the application while signed in, and it grants them nothing.
-- There is no organisation to list into until approval, and EffectivePermissionResolver withholds every
-- listing verb while the profile's kyc_status is not cleared.
--
-- ── two tables ───────────────────────────────────────────────────────────────────────────────────
--
-- seller_applications is the application itself. seller_identity_checks is what was asked of whom, and
-- it is a separate table rather than columns because the answer is "zero or more attempts", each with
-- its own moment and verdict — a retried AML check after a name correction is a second row, not an
-- overwrite of the first.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────

CREATE TABLE seller_applications (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference             VARCHAR(32)  NOT NULL UNIQUE,

    -- The account created at the moment of applying, and the profile that carries the KYC gate.
    user_id               BIGINT       NOT NULL,
    profile_id            BIGINT       NOT NULL,
    -- Null until approved. This is what the applicant is asking for.
    tenant_id             BIGINT,

    -- ── the person ──
    full_name             VARCHAR(160) NOT NULL,
    email                 VARCHAR(128) NOT NULL,
    phone                 VARCHAR(32),
    id_number             VARCHAR(64),
    kra_pin               VARCHAR(32),

    /*
     * Where those details came from, which is the first thing a reviewer wants to know.
     *
     * COOP_ACCOUNT means the bank's own records supplied them against a validated account — identification
     * the bank has already performed. SELF_DECLARED means the applicant typed them and nothing has yet
     * corroborated it.
     */
    identity_source       VARCHAR(24)  NOT NULL DEFAULT 'SELF_DECLARED',
    coop_account_number   VARCHAR(34),
    coop_account_verified BOOLEAN      NOT NULL DEFAULT false,

    -- ── the organisation being asked for ──
    organisation_name     VARCHAR(160),
    seller_type           VARCHAR(32),
    registration_number   VARCHAR(64),
    county                VARCHAR(64),
    town                  VARCHAR(64),
    address_line          VARCHAR(255),

    -- ── where it stands ──
    state                 VARCHAR(16)  NOT NULL DEFAULT 'DRAFT',
    submitted_at          TIMESTAMPTZ,
    decided_at            TIMESTAMPTZ,
    decided_by_user_id    BIGINT,
    decision_note         TEXT,

    status                INTEGER      NOT NULL DEFAULT 1,
    status_flag           VARCHAR(32)  NOT NULL DEFAULT 'Active',
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by            VARCHAR(64),
    updated_by            VARCHAR(64),

    /*
     * DRAFT is the window between registering and submitting — the applicant has an account and is still
     * filling the rest in. MORE_INFO is the bank asking for something without refusing: it returns to the
     * applicant's hands, which REJECTED never does.
     */
    CONSTRAINT ck_seller_app_state
        CHECK (state IN ('DRAFT', 'SUBMITTED', 'MORE_INFO', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_seller_app_identity_source
        CHECK (identity_source IN ('COOP_ACCOUNT', 'SELF_DECLARED')),
    -- A decided application has a decider and a moment, and a pending one has neither. Without this,
    -- "approved by nobody" is representable, and that is the row an audit cannot answer questions about.
    CONSTRAINT ck_seller_app_decided
        CHECK ((state IN ('DRAFT', 'SUBMITTED', 'MORE_INFO') AND decided_at IS NULL)
            OR (state IN ('APPROVED', 'REJECTED') AND decided_at IS NOT NULL
                AND decided_by_user_id IS NOT NULL))
);

-- One open application per person. A second is either a mistake or an attempt to get a different answer
-- from a different reviewer, and both are better refused than recorded.
CREATE UNIQUE INDEX uk_seller_app_open ON seller_applications (user_id)
    WHERE state IN ('DRAFT', 'SUBMITTED', 'MORE_INFO');
CREATE INDEX idx_seller_app_state ON seller_applications (state, submitted_at DESC);
CREATE INDEX idx_seller_app_tenant ON seller_applications (tenant_id);

ALTER TABLE seller_applications ADD COLUMN search_text text
    GENERATED ALWAYS AS (
        lower(coalesce(full_name, '') || ' ' || coalesce(email, '') || ' ' ||
              coalesce(phone, '') || ' ' || coalesce(organisation_name, '') || ' ' ||
              coalesce(reference, ''))
    ) STORED;
CREATE INDEX idx_seller_app_search_trgm ON seller_applications USING gin (search_text gin_trgm_ops);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- What was checked, and what came back.
--
-- Every run is recorded whether or not it reached anything. A check that could not run leaves a row
-- saying so, because the alternative is a reviewer looking at an application with no AML line and being
-- unable to tell whether it passed, failed, or was never attempted.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE seller_identity_checks (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id    BIGINT       NOT NULL REFERENCES seller_applications (id) ON DELETE CASCADE,

    check_code        VARCHAR(24)  NOT NULL,
    verdict           VARCHAR(32)  NOT NULL,
    -- The provider's own reference, when there is one. Null while the provider is a stub.
    provider_ref      VARCHAR(128),
    detail            TEXT,
    ran_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),

    status            INTEGER      NOT NULL DEFAULT 1,
    status_flag       VARCHAR(32)  NOT NULL DEFAULT 'Active',
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by        VARCHAR(64),
    updated_by        VARCHAR(64),

    CONSTRAINT ck_seller_check_code
        CHECK (check_code IN ('COOP_ACCOUNT', 'AML', 'IPRS')),
    /*
     * PENDING_INTEGRATION is what a stub returns, and it is deliberately not PASS.
     *
     * A simulated check that passed would be indistinguishable from a real one that passed, and the day
     * the integration lands nobody could say which historical rows meant anything. SKIPPED_COOP_VERIFIED
     * is the AML/IPRS answer for an applicant whose Co-op account validated: the bank ran both to open
     * that account, and the row records why there is nothing to see rather than leaving a gap.
     */
    CONSTRAINT ck_seller_check_verdict
        CHECK (verdict IN ('PASS', 'FAIL', 'REVIEW', 'PENDING_INTEGRATION', 'SKIPPED_COOP_VERIFIED'))
);

CREATE INDEX idx_seller_check_app ON seller_identity_checks (application_id, check_code);
