-- ═════════════════════════════════════════════════════════════════════════════════════════════════
-- M3 — affordability and the finance beside the listing (BRD FR025–FR034, plan §3.11)
--
-- The platform's headline is a property and the mortgage against it, side by side. This is the other half of
-- that sentence: what lenders offer, and what a household can carry.
--
-- <h2>Products are a lender's rows; who sees them is already decided</h2>
--
-- `institution_id` is the isolation, resolved from the principal exactly as `tenant_id` is for a seller's
-- listings. Which products appear against a *listing* is a different question, and the partnership table
-- already answers it — the arrangement that lets a lender work a seller's portfolio is the arrangement that
-- puts their rates on it. No new column, no new visibility rule.
--
-- <h2>Published, not approved</h2>
--
-- No Maker/Checker queue here: §3.2's list is M6, M8, M10 and M13, and inventing a control the BRD does not
-- ask for is not free. What publication does get is its own permission — drafting a rate and putting it in
-- front of the public are different acts by different people.
-- ═════════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE mortgage_products (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    institution_id        BIGINT       NOT NULL REFERENCES lending_institutions (id),
    -- Label cache: a marketplace panel names the bank without joining.
    institution_name      VARCHAR(255),

    reference             VARCHAR(16)  NOT NULL UNIQUE,
    name                  VARCHAR(160) NOT NULL,
    description           TEXT,

    product_type          VARCHAR(24)  NOT NULL DEFAULT 'MORTGAGE',
    currency              VARCHAR(3)   NOT NULL DEFAULT 'KES',

    -- What the lender will lend.
    min_amount            NUMERIC(15, 2),
    max_amount            NUMERIC(15, 2),
    min_term_months       SMALLINT     NOT NULL DEFAULT 12,
    max_term_months       SMALLINT     NOT NULL DEFAULT 240,

    -- NUMERIC, never a float: a rate multiplies money, and 13.5 that is really 13.499999 compounds into a
    -- repayment figure that does not match the lender's own.
    interest_rate         NUMERIC(6, 3) NOT NULL,
    rate_type             VARCHAR(16)  NOT NULL DEFAULT 'FIXED',

    -- The two ends of the same constraint, both stored because lenders quote whichever suits them and a
    -- buyer needs to see the one they were told. Neither is derived from the other at write time.
    max_ltv_percent       NUMERIC(5, 2) NOT NULL DEFAULT 90,
    min_deposit_percent   NUMERIC(5, 2) NOT NULL DEFAULT 10,

    processing_fee_percent NUMERIC(5, 2) NOT NULL DEFAULT 0,
    insurance_percent     NUMERIC(5, 2) NOT NULL DEFAULT 0,
    other_fees_note       TEXT,

    -- Eligibility, as figures rather than prose where a figure will do — these are what the affordability
    -- match actually filters on, and prose cannot be filtered.
    min_monthly_income    NUMERIC(15, 2),
    max_dti_percent       NUMERIC(5, 2),
    eligibility_notes     TEXT,
    required_documents    TEXT,

    -- In front of the public, or not. Deliberately a flag rather than a state machine: a product is on offer
    -- or it is not, and there is no third position anybody has asked for.
    published             BOOLEAN      NOT NULL DEFAULT false,
    published_at          TIMESTAMPTZ,

    status                INTEGER      NOT NULL DEFAULT 1,
    status_flag           VARCHAR(32)  NOT NULL DEFAULT 'Active',
    deactivation_reason   TEXT,

    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by            VARCHAR(64),
    updated_by            VARCHAR(64),

    CONSTRAINT ck_product_type
        CHECK (product_type IN ('MORTGAGE', 'CONSTRUCTION', 'PLOT_PURCHASE', 'EQUITY_RELEASE', 'REFINANCE')),
    CONSTRAINT ck_product_rate_type CHECK (rate_type IN ('FIXED', 'VARIABLE', 'REDUCING')),
    CONSTRAINT ck_product_rate CHECK (interest_rate > 0 AND interest_rate < 100),
    CONSTRAINT ck_product_terms CHECK (max_term_months >= min_term_months AND min_term_months > 0),
    CONSTRAINT ck_product_amounts
        CHECK (max_amount IS NULL OR min_amount IS NULL OR max_amount >= min_amount),
    CONSTRAINT ck_product_ltv CHECK (max_ltv_percent > 0 AND max_ltv_percent <= 100),
    CONSTRAINT ck_product_deposit CHECK (min_deposit_percent >= 0 AND min_deposit_percent < 100),
    -- A published product has a date on it, so "since when has this rate been on offer" is answerable from
    -- the row rather than from the audit trail.
    CONSTRAINT ck_product_published CHECK (published = false OR published_at IS NOT NULL)
);

CREATE INDEX idx_mortgage_products_institution ON mortgage_products (institution_id);
-- The public query: what is on offer. Partial, because the marketplace never asks for anything else.
CREATE INDEX idx_mortgage_products_live ON mortgage_products (institution_id, interest_rate)
    WHERE published AND status <> 5;
CREATE INDEX idx_mortgage_products_type ON mortgage_products (product_type);

ALTER TABLE mortgage_products ADD COLUMN search_text text
    GENERATED ALWAYS AS (
        lower(coalesce(name, '') || ' ' || coalesce(reference, '') || ' ' ||
              coalesce(description, '') || ' ' || coalesce(product_type, '') || ' ' ||
              coalesce(institution_name, ''))
    ) STORED;
CREATE INDEX idx_mortgage_products_search_trgm
    ON mortgage_products USING gin (search_text public.gin_trgm_ops);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- What a household can carry.
--
-- <h2>Keyed on the person, like the shortlist and the consent store</h2>
--
-- An affordability check is about a household's income, not about an actor. Same reasoning, same column.
--
-- <h2>The provider's own answer is kept verbatim</h2>
--
-- `provider_payload` holds whatever the assessor returned, unparsed. Today that is the mock's own working;
-- tomorrow it is the OCP microservice's response. When somebody asks why a figure was what it was, the
-- answer has to be the thing that produced it — not this application's reading of it, which is exactly the
-- part that could be wrong.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE affordability_checks (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id               BIGINT       NOT NULL REFERENCES users (id),
    reference             VARCHAR(16)  NOT NULL UNIQUE,

    -- Set when the check was run from a listing rather than from the calculator on its own. The reference is
    -- copied so the row still says which property it was about after the listing comes down.
    property_id           BIGINT REFERENCES properties (id),
    property_reference    VARCHAR(16),
    property_price        NUMERIC(15, 2),

    -- The inputs, exactly as given. Shown back only to the person who entered them.
    currency              VARCHAR(3)   NOT NULL DEFAULT 'KES',
    gross_monthly_income  NUMERIC(15, 2) NOT NULL,
    other_monthly_income  NUMERIC(15, 2) NOT NULL DEFAULT 0,
    monthly_obligations   NUMERIC(15, 2) NOT NULL DEFAULT 0,
    deposit_amount        NUMERIC(15, 2) NOT NULL DEFAULT 0,
    term_months           SMALLINT     NOT NULL,
    employment_type       VARCHAR(24),
    dependants            SMALLINT,

    -- The outcome.
    decision              VARCHAR(16)  NOT NULL,
    decision_reason       TEXT,
    max_loan_amount       NUMERIC(15, 2) NOT NULL DEFAULT 0,
    max_property_price    NUMERIC(15, 2) NOT NULL DEFAULT 0,
    monthly_repayment     NUMERIC(15, 2) NOT NULL DEFAULT 0,
    -- What share of income the repayment would take, and the ceiling that was applied to get there. Both,
    -- because "why was I told no" is answered by the pair and not by either alone.
    dti_percent           NUMERIC(5, 2),
    dti_ceiling_percent   NUMERIC(5, 2),
    assumed_rate          NUMERIC(6, 3),

    provider              VARCHAR(24)  NOT NULL DEFAULT 'MOCK',
    provider_reference    VARCHAR(64),
    provider_payload      JSONB,

    status                INTEGER      NOT NULL DEFAULT 1,
    status_flag           VARCHAR(32)  NOT NULL DEFAULT 'Active',

    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by            VARCHAR(64),
    updated_by            VARCHAR(64),

    CONSTRAINT ck_affordability_decision
        CHECK (decision IN ('ELIGIBLE', 'MARGINAL', 'NOT_ELIGIBLE')),
    CONSTRAINT ck_affordability_income CHECK (gross_monthly_income >= 0),
    CONSTRAINT ck_affordability_term CHECK (term_months > 0)
);

CREATE INDEX idx_affordability_user ON affordability_checks (user_id, created_at DESC);
CREATE INDEX idx_affordability_property ON affordability_checks (property_id);
CREATE INDEX idx_affordability_created ON affordability_checks (created_at DESC);

-- Deliberately no income in the searchable text. The platform's list is searched by reference, decision and
-- the listing it was run against; a generated column carrying somebody's salary would put it in an index
-- that a LIKE could walk.
ALTER TABLE affordability_checks ADD COLUMN search_text text
    GENERATED ALWAYS AS (
        lower(coalesce(reference, '') || ' ' || coalesce(property_reference, '') || ' ' ||
              coalesce(decision, '') || ' ' || coalesce(provider, ''))
    ) STORED;
CREATE INDEX idx_affordability_search_trgm
    ON affordability_checks USING gin (search_text public.gin_trgm_ops);
