-- ═════════════════════════════════════════════════════════════════════════════════════════════════
-- Many photographs against something that is not a property
--
-- `property_media` is the only many-images-to-one-thing table in this schema and it is welded to
-- `properties`: a NOT NULL foreign key, a partial unique index keyed on it, a `primary_image_key` cache on
-- the parent maintained from it, and a publish gate that counts it. Generalising it would mean changing all
-- four of those in a migration whose subject is none of them.
--
-- So this table is new and `property_media` is left exactly as it is. The deliberate cost is two media
-- tables; the consolidation — one polymorphic table with `property_media` kept as a view over it — is its own
-- later migration, because it has to move the primary-image index, PropertyMediaService, the parent cache and
-- the publish gate together.
--
-- <h2>PROPERTY is not an allowed owner type</h2>
--
-- One table per question. A listing's photographs are in `property_media`; everything else is here; nobody
-- has to work out which to read. It also keeps PropertyMediaService's twelve-photograph cap where it belongs
-- — a development legitimately has two hundred photographs and a listing legitimately does not.
--
-- <h2>A polymorphic owner cannot have a foreign key</h2>
--
-- What replaces it is a CHECK on the owner types and the fact that nothing in this schema hard-deletes:
-- every archive is `status = 5`, so an asset whose owner has gone is an asset nothing queries rather than a
-- dangling row. The service is what keeps the two in step; the constraint is what stops a typo inventing a
-- sixth owner type.
-- ═════════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE media_assets (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_type          VARCHAR(32)  NOT NULL,
    owner_id            BIGINT       NOT NULL,

    -- Who may see it, cached from the owner so the access check is one read rather than a walk up the tree.
    -- Exactly one of the two, or neither for an asset on a platform-owned thing — the same shape as
    -- developments, minus the requirement that one be present, because a progress update on a listing has a
    -- tenant and a progress update on a bank's project has an institution.
    tenant_id           BIGINT,
    institution_id      BIGINT,

    media_kind          VARCHAR(24)  NOT NULL DEFAULT 'PHOTO',
    storage_key         VARCHAR(512) NOT NULL,
    content_type        VARCHAR(64),
    size_bytes          BIGINT,
    caption             VARCHAR(255),
    sort_order          INTEGER      NOT NULL DEFAULT 0,
    is_primary          BOOLEAN      NOT NULL DEFAULT false,

    -- Marketing, like a listing's gallery, or internal, like a site photograph a lender keeps for its own
    -- file. Never a title deed: those are vault_documents, which is encrypted and ACL-gated, and which is
    -- what the vault is for.
    public_visible      BOOLEAN      NOT NULL DEFAULT true,

    status              INTEGER      NOT NULL DEFAULT 1,
    status_flag         VARCHAR(32)  NOT NULL DEFAULT 'Active',
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          VARCHAR(64),
    updated_by          VARCHAR(64),

    CONSTRAINT ck_media_owner_type CHECK (owner_type IN
        ('DEVELOPMENT', 'DEVELOPMENT_PHASE', 'UNIT_TYPE', 'DEVELOPMENT_UNIT', 'PROGRESS_UPDATE')),
    CONSTRAINT ck_media_kind CHECK (media_kind IN
        ('PHOTO', 'FLOOR_PLAN', 'SITE_PLAN', 'BROCHURE', 'DRONE')),
    CONSTRAINT ck_media_owner CHECK (
        (institution_id IS NULL) OR (tenant_id IS NULL)),
    CONSTRAINT ck_media_size CHECK (size_bytes IS NULL OR size_bytes >= 0)
);

CREATE INDEX idx_media_owner ON media_assets (owner_type, owner_id, sort_order) WHERE status <> 5;
CREATE UNIQUE INDEX uk_media_primary ON media_assets (owner_type, owner_id)
    WHERE is_primary AND status <> 5;
CREATE INDEX idx_media_tenant ON media_assets (tenant_id) WHERE tenant_id IS NOT NULL;
CREATE INDEX idx_media_institution ON media_assets (institution_id) WHERE institution_id IS NOT NULL;
