-- pg_trgm's operator class, wherever the extension lives.
-- An extension exists once per database, in one schema, and on a shared server that schema is whichever
-- application installed it first — public on one machine, another application's schema on the next. Rather
-- than guess, look it up and put it on this transaction's search path; Flyway runs the whole script in one
-- transaction, so every gin_trgm_ops below resolves. Installs it into our own schema if nobody has yet.
DO $$
DECLARE ext_schema text;
BEGIN
    SELECT n.nspname INTO ext_schema
      FROM pg_extension e JOIN pg_namespace n ON n.oid = e.extnamespace
     WHERE e.extname = 'pg_trgm';
    IF ext_schema IS NULL THEN
        EXECUTE 'CREATE EXTENSION pg_trgm';
        ext_schema := current_schema();
    END IF;
    EXECUTE format('SET LOCAL search_path TO %I, %I', current_schema(), ext_schema);
END $$;

-- ═════════════════════════════════════════════════════════════════════════════════════════════════
-- Phase 0b — Maker/Checker, once, for everything (BRD FR070, FR122, FR126, FR128)
--
-- The BRD has staff approvals running through most of the platform: seller registrations, listings, auction
-- listings, promotions, vendor products. Today the only segregation of duties that exists is inside
-- PartnershipService, and it separates *sides* — the seller side cannot approve its own proposal — not
-- *users*. A second person at the same seller can approve their colleague's proposal, and every future
-- approvable thing would have to re-implement even that much.
--
-- So the mechanism becomes a table, and the rule becomes a constraint.
--
-- <p><strong>Self-approval is refused platform-wide, by the database.</strong> The plan (§6, question 2)
-- asked whether it should instead be configurable per entity type. It is not: a rule that can be switched off
-- is not segregation of duties, and every regulator's version of this question expects one answer. Where a
-- team is too small to have two people, the answer is to give the second approval to the platform — which
-- already sits outside every organisation — rather than to let one person do both halves.
--
-- The CHECK is the load-bearing part. A service-layer guard gives the readable message; this is what makes
-- the guarantee true for code that has not been written yet.
-- ═════════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE approval_workflows (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- What is waiting, named the way the owning module names it. Not a foreign key: the table has to serve
    -- entity types that do not exist yet, and a per-type column would be a schema change per module.
    entity_type           VARCHAR(64)  NOT NULL,
    entity_id             BIGINT       NOT NULL,
    -- Which decision is being asked for. One entity can need several over its life — a listing is published,
    -- then later withdrawn — and each is its own request.
    action                VARCHAR(32)  NOT NULL,

    -- Whose queue this belongs in. At most one is set, exactly as everywhere else in this schema.
    tenant_id             BIGINT,
    institution_id        BIGINT,

    -- What a reviewer sees before opening anything: "Acacia Ridge Developments ↔ Equatorial Bank". A label
    -- cache, so the queue renders without joining a different table per entity type.
    subject_label         VARCHAR(255),

    submitted_by_user_id  BIGINT       NOT NULL,
    submitted_by_username VARCHAR(64),
    submitted_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    submission_note       TEXT,

    checked_by_user_id    BIGINT,
    checked_by_username   VARCHAR(64),
    checked_at            TIMESTAMPTZ,
    decision              VARCHAR(16),
    decision_reason       TEXT,

    state                 VARCHAR(16)  NOT NULL DEFAULT 'PENDING',

    status                INTEGER      NOT NULL DEFAULT 1,
    status_flag           VARCHAR(32)  NOT NULL DEFAULT 'Active',

    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by            VARCHAR(64),
    updated_by            VARCHAR(64),

    -- The rule. Nullable while pending; once a decision exists it cannot be the submitter's own.
    CONSTRAINT ck_approval_maker_checker
        CHECK (checked_by_user_id IS NULL OR checked_by_user_id <> submitted_by_user_id),
    CONSTRAINT ck_approval_state
        CHECK (state IN ('PENDING', 'APPROVED', 'REJECTED', 'SENT_BACK')),
    CONSTRAINT ck_approval_decision
        CHECK (decision IS NULL OR decision IN ('APPROVED', 'REJECTED', 'SENT_BACK')),
    -- A decided row has a decider, and a pending one does not. Without this, "state = APPROVED with nobody
    -- named" is representable, and that is the shape an audit cannot answer questions about.
    CONSTRAINT ck_approval_decided
        CHECK ((state = 'PENDING' AND checked_at IS NULL AND decision IS NULL)
            OR (state <> 'PENDING' AND checked_at IS NOT NULL AND decision IS NOT NULL)),
    CONSTRAINT ck_approval_one_scope
        CHECK (tenant_id IS NULL OR institution_id IS NULL)
);

-- One open request per thing per action. Two people submitting the same listing for publication should not
-- produce two queue entries, either of which could be decided while the other stays open.
CREATE UNIQUE INDEX uk_approval_pending ON approval_workflows (entity_type, entity_id, action)
    WHERE state = 'PENDING';

CREATE INDEX idx_approval_queue ON approval_workflows (state, submitted_at DESC);
CREATE INDEX idx_approval_entity ON approval_workflows (entity_type, entity_id);
CREATE INDEX idx_approval_tenant ON approval_workflows (tenant_id);
CREATE INDEX idx_approval_institution ON approval_workflows (institution_id);
CREATE INDEX idx_approval_submitter ON approval_workflows (submitted_by_user_id);

ALTER TABLE approval_workflows ADD COLUMN search_text text
    GENERATED ALWAYS AS (
        lower(coalesce(subject_label, '') || ' ' || coalesce(entity_type, '') || ' ' ||
              coalesce(action, '') || ' ' || coalesce(submitted_by_username, '') || ' ' ||
              coalesce(checked_by_username, '') || ' ' || coalesce(submission_note, ''))
    ) STORED;
CREATE INDEX idx_approval_search_trgm ON approval_workflows USING gin (search_text gin_trgm_ops);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- Backfill: every partnership that is currently pending or already decided gets the row it would have had.
--
-- Without this the queue would open empty on a database with live proposals in it, and the first thing an
-- approver did would be to approve something the workflow had no record of.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
INSERT INTO approval_workflows (entity_type, entity_id, action, tenant_id, institution_id, subject_label,
                                submitted_by_user_id, submitted_at, state,
                                checked_by_user_id, checked_at, decision, created_by)
SELECT 'PARTNERSHIP',
       p.id,
       'ACTIVATE',
       -- The queue belongs to the side that did NOT propose: they are the ones who owe a decision.
       CASE WHEN p.requested_by_side = 'LENDER' THEN p.tenant_id END,
       CASE WHEN p.requested_by_side = 'SELLER' THEN p.institution_id END,
       coalesce(p.tenant_name, '') || ' ↔ ' || coalesce(p.institution_name, ''),
       coalesce(p.requested_by_user_id, 0),
       coalesce(p.requested_at, p.created_at),
       CASE WHEN p.approved_at IS NOT NULL THEN 'APPROVED' ELSE 'PENDING' END,
       p.approved_by_user_id,
       p.approved_at,
       CASE WHEN p.approved_at IS NOT NULL THEN 'APPROVED' END,
       'migration'
FROM tenant_lender_partnerships p
WHERE p.requested_at IS NOT NULL
  AND p.revoked_at IS NULL
  -- A partnership approved by the same user who proposed it would violate the CHECK. None exist — the old
  -- side-based guard made it impossible — but the backfill states the assumption rather than relying on it.
  AND (p.approved_by_user_id IS NULL OR p.approved_by_user_id <> coalesce(p.requested_by_user_id, 0));
