-- ═════════════════════════════════════════════════════════════════════════════════════════════════
-- Phase 4 / M7 — ratings and moderation (BRD post-transaction feedback, plan §4)
--
-- <h2>One table, not three</h2>
--
-- The §4 table names `property_rating`, `service_rating` and `product_rating`. They are the same row with a
-- different subject: a score, some words, who wrote them, and whether anybody has complained. Three tables
-- would mean three moderation queues, three report paths and three sets of aggregates — and the moderator's
-- screen would have to union them anyway.
--
-- So: `ratings` with a `subject_type` discriminator, and no foreign key to any of the four subject tables.
-- A loose reference, the way `approval_workflows` does it, for the same reason: the alternative is four
-- nullable FK columns of which exactly one is ever set.
--
-- <h2>Verified means the platform can see the transaction</h2>
--
-- A rating of a property or of a seller can be checked: the platform holds the enquiry, the viewing and the
-- offer. A rating of a vendor cannot — the platform introduces the two parties and takes no part in what
-- they agree. Rather than pretend otherwise, the row records which it is, and the screens say so. An
-- unverified review is worth less than a verified one and should look it.
--
-- <h2>Published, then moderated</h2>
--
-- Ratings appear immediately. A review site that holds every review for a day is a review site nobody
-- writes to. What the moderation queue holds is the ones somebody has complained about, plus any whose text
-- trips the configured word list on the way in — so the common case is fast and the bad case is caught.
-- ═════════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE ratings (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    reference      VARCHAR(16)  NOT NULL UNIQUE,

    -- PROPERTY | SELLER | AGENT | VENDOR | CATALOGUE_ITEM. No FK: see the header.
    subject_type   VARCHAR(24)  NOT NULL,
    subject_id     BIGINT       NOT NULL,
    -- Denormalised so the moderator's queue and the rater's own list read without four joins.
    subject_ref    VARCHAR(16),
    subject_label  VARCHAR(255),

    user_id        BIGINT       NOT NULL REFERENCES users (id),
    rater_name     VARCHAR(160),

    score          SMALLINT     NOT NULL,
    title          VARCHAR(180),
    body           TEXT,

    -- Whether the platform can see a transaction behind it. Never claimed, only derived.
    verified       BOOLEAN      NOT NULL DEFAULT false,
    verified_via   VARCHAR(32),

    state          VARCHAR(16)  NOT NULL DEFAULT 'PUBLISHED',
    held_reason    TEXT,
    moderated_at   TIMESTAMPTZ,
    moderated_by_user_id BIGINT,
    moderation_note TEXT,

    -- The subject's answer. One per rating: a right of reply, not a conversation.
    reply_body     TEXT,
    replied_at     TIMESTAMPTZ,
    replied_by_user_id BIGINT,

    report_count   INTEGER      NOT NULL DEFAULT 0,

    status         INTEGER      NOT NULL DEFAULT 1,
    status_flag    VARCHAR(32)  NOT NULL DEFAULT 'Active',

    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by     VARCHAR(64),
    updated_by     VARCHAR(64),

    CONSTRAINT ck_rating_score CHECK (score BETWEEN 1 AND 5),
    CONSTRAINT ck_rating_subject CHECK (
        subject_type IN ('PROPERTY', 'SELLER', 'AGENT', 'VENDOR', 'CATALOGUE_ITEM')),
    CONSTRAINT ck_rating_state CHECK (state IN ('PUBLISHED', 'HELD', 'HIDDEN')),
    -- A rating taken down says why. "Hidden by a moderator" with no reason is not a decision anybody can
    -- review afterwards.
    CONSTRAINT ck_rating_hidden CHECK (state <> 'HIDDEN' OR moderation_note IS NOT NULL),
    CONSTRAINT ck_rating_verified CHECK (NOT verified OR verified_via IS NOT NULL),
    CONSTRAINT ck_rating_reply CHECK (reply_body IS NULL OR replied_at IS NOT NULL)
);

-- One rating per person per subject. A second opinion is an edit, not another row.
CREATE UNIQUE INDEX uk_rating_once ON ratings (user_id, subject_type, subject_id) WHERE status <> 5;
CREATE INDEX idx_rating_subject ON ratings (subject_type, subject_id, created_at DESC);
CREATE INDEX idx_rating_user ON ratings (user_id, created_at DESC);
-- The moderator's queue: held or reported, oldest first — the one somebody has been waiting on longest.
CREATE INDEX idx_rating_moderation ON ratings (created_at)
    WHERE (state = 'HELD' OR report_count > 0) AND status <> 5;

ALTER TABLE ratings ADD COLUMN search_text text
    GENERATED ALWAYS AS (
        lower(coalesce(reference, '') || ' ' || coalesce(subject_label, '') || ' ' ||
              coalesce(subject_ref, '') || ' ' || coalesce(rater_name, '') || ' ' ||
              coalesce(title, '') || ' ' || coalesce(body, ''))
    ) STORED;
CREATE INDEX idx_rating_search_trgm ON ratings USING gin (search_text gin_trgm_ops);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- A complaint about a rating.
--
-- Kept rather than collapsed into a counter, because "three people reported this" and "the same person
-- reported it three times" are different facts and only one of them means anything.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE rating_reports (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    rating_id    BIGINT       NOT NULL REFERENCES ratings (id),
    user_id      BIGINT       NOT NULL REFERENCES users (id),
    reason       VARCHAR(32)  NOT NULL,
    detail       TEXT,

    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_report_reason CHECK (
        reason IN ('INACCURATE', 'ABUSIVE', 'PERSONAL_DATA', 'SPAM', 'NOT_A_CUSTOMER', 'OTHER'))
);

-- One report per person per rating. Reporting twice is the same complaint, not a louder one.
CREATE UNIQUE INDEX uk_report_once ON rating_reports (rating_id, user_id);
CREATE INDEX idx_report_rating ON rating_reports (rating_id, created_at DESC);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- The aggregate, in one place with one writer.
--
-- A maintained aggregate rather than a COUNT/AVG per subject on every read: a listing card shows a star
-- rating, and a search page shows twenty listing cards. Kept in its own table rather than as columns on the
-- four subject tables so that maintaining it is one method rather than four — the lesson from M10's
-- listings counter, which was declared as an aggregate and maintained by nothing.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE rating_summaries (
    subject_type  VARCHAR(24)   NOT NULL,
    subject_id    BIGINT        NOT NULL,
    rating_count  INTEGER       NOT NULL DEFAULT 0,
    average_score NUMERIC(3, 2),
    -- The histogram, so a subject page can show the distribution rather than one number. Five small
    -- integers beat a GROUP BY per page view.
    score_1       INTEGER       NOT NULL DEFAULT 0,
    score_2       INTEGER       NOT NULL DEFAULT 0,
    score_3       INTEGER       NOT NULL DEFAULT 0,
    score_4       INTEGER       NOT NULL DEFAULT 0,
    score_5       INTEGER       NOT NULL DEFAULT 0,
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),

    PRIMARY KEY (subject_type, subject_id)
);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- Who reaches the module.
--
-- Buyers write ratings through their own portal, so BUYER_PORTAL already admits them and RATINGS does not
-- need to. What RATINGS admits is the people who are rated — a seller, an agent or a vendor reading and
-- replying to what was said about them — and the platform that moderates.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
UPDATE app_modules
SET allowed_user_types = allowed_user_types || ',VENDOR',
    updated_at         = now(),
    updated_by         = 'system'
WHERE code = 'VENDORS'
  AND ',' || allowed_user_types || ',' NOT LIKE '%,VENDOR,%';
