-- ═════════════════════════════════════════════════════════════════════════════════════════════════
-- Developments — a project with many units, sold off-plan or never sold at all
--
-- Everything before this table assumed one row is one saleable thing. A bank selling "Highrise Apartments,
-- 200 units: 60 one-bed, 70 two-bed, 40 studio, 30 three-bed" cannot be said in that vocabulary: a
-- development is not a listing, a typology is not a bedroom count, and a unit is not a property.
--
-- <h2>Four tables, and what each one is for</h2>
--
-- A DEVELOPMENT is the project. A UNIT TYPE is the product a buyer chooses between — "two bedroom, 92 m²,
-- from KES 9.5M, 70 of them". A UNIT is the inventory row, and the only place in this schema where
-- construction status is a fact about a physical thing rather than a roll-up: it is what makes "who bought
-- B4-12" and "60 of 70 still available" answerable. A PHASE is how the build is divided in time and money.
--
-- <h2>Who owns a development</h2>
--
-- Exactly one principal, and it may be a lending institution rather than a seller. The bank finances a
-- developer's project and the project is the bank's own record — they created it, and it is in their
-- interest to track it. `auction_lots` already had this problem and solved it the same way, with a CHECK
-- that exactly one of the two id columns is set and a hand-written visibility specification instead of
-- TenantScope, because a lender is not a tenant and has no visible-tenant set describing it.
--
-- `selling_tenant_id` is a third, separate question: whose listings the units become when the project is
-- marketed. A bank-financed rental block has an owner and no seller, which is why the never-for-sale case
-- needs no flag of its own — it has no selling tenant and no properties rows.
--
-- <h2>Delegation, rather than a second ownership model</h2>
--
-- The owner grants the developer the right to post progress. `development_collaborators` is that grant, and
-- it is the only thing here that widens anybody's visibility — so it is revocable, it says who granted it,
-- and it is the row this migration would most like tested.
--
-- <h2>Construction status is not a listing state</h2>
--
-- `listing_state` stays what it has always been: a publication lifecycle. Off-plan is
-- `construction_status IN ('PLANNED','UNDER_CONSTRUCTION')`, derived from the units, and never a fourth
-- column that can disagree with the status. The one word added to `listing_state` is PRIVATE, for the
-- project that is tracked and never marketed.
--
-- <h2>Counted columns have exactly one writer</h2>
--
-- Every `units_*`, `from_price`, `to_price` and `percent_complete` on a development or a unit type is
-- counted from the units and phases below it by DevelopmentInventoryService and by nothing else. They are
-- stored rather than computed on read for the reason `promotion_boost` is stored: the marketplace card reads
-- them once per result, and an aggregate per card is a join per card. `percent_basis` records which rule
-- produced the percentage, so a screen can say "62%, weighted by phase budget" and nobody mistakes a
-- derived figure for somebody's opinion.
-- ═════════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE developments (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference               VARCHAR(16)  NOT NULL UNIQUE,

    -- The owning principal. Exactly one, per ck_dev_principal below: a development with two owners is two
    -- developments, and a development with none is a row nobody can reach.
    tenant_id               BIGINT       REFERENCES tenants (id),
    tenant_name             VARCHAR(255),
    institution_id          BIGINT       REFERENCES lending_institutions (id),
    institution_name        VARCHAR(255),

    -- Who markets it. Null on a project that is never offered for sale.
    selling_tenant_id       BIGINT       REFERENCES tenants (id),
    selling_tenant_name     VARCHAR(255),

    -- The builder, as a label rather than a foreign key: a bank's borrower is usually not on this platform,
    -- and requiring them to be would mean no project could be tracked until they were onboarded.
    developer_name          VARCHAR(255),

    name                    VARCHAR(255) NOT NULL,
    description             TEXT,
    -- The same vocabulary a listing uses, so a development of apartments and an apartment agree on the word.
    development_type        VARCHAR(32)  NOT NULL REFERENCES property_type_configs (code),

    -- Why it exists. FOR_SALE is the marketplace case; the others are the tracking case.
    purpose                 VARCHAR(24)  NOT NULL DEFAULT 'FOR_SALE',

    county                  VARCHAR(64),
    town                    VARCHAR(64),
    estate                  VARCHAR(128),
    address_line            TEXT,
    latitude                NUMERIC(9, 6),
    longitude               NUMERIC(9, 6),

    -- What the developer says they are building, kept separate from the counted figures below. "200 units"
    -- is a plan, and the day the plan and the inventory disagree is a fact worth being able to see rather
    -- than one to overwrite.
    planned_unit_count      INTEGER,

    -- Counted from development_units. One writer: DevelopmentInventoryService.
    units_total             INTEGER      NOT NULL DEFAULT 0,
    units_available         INTEGER      NOT NULL DEFAULT 0,
    units_reserved          INTEGER      NOT NULL DEFAULT 0,
    units_sold              INTEGER      NOT NULL DEFAULT 0,
    from_price              NUMERIC(15, 2),
    to_price                NUMERIC(15, 2),
    currency                VARCHAR(3)   NOT NULL DEFAULT 'KES',

    construction_status     VARCHAR(24)  NOT NULL DEFAULT 'PLANNED',
    percent_complete        SMALLINT     NOT NULL DEFAULT 0,
    percent_basis           VARCHAR(16)  NOT NULL DEFAULT 'EQUAL',

    started_on              DATE,
    projected_completion_on DATE,
    actual_completion_on    DATE,

    -- The money. Never on a public response record — see the separate public DTO, which omits these rather
    -- than blanking them.
    budget_amount           NUMERIC(15, 2),
    facility_reference      VARCHAR(32),
    facility_amount         NUMERIC(15, 2),

    -- Publication, the same word and the same meaning as on a listing, plus PRIVATE for the project that is
    -- tracked and never marketed. One column holding one truth, rather than a boolean beside a state that
    -- can contradict it.
    listing_state           VARCHAR(16)  NOT NULL DEFAULT 'DRAFT',
    published_at            TIMESTAMPTZ,
    withdrawn_at            TIMESTAMPTZ,
    withdrawn_reason        TEXT,
    primary_image_key       VARCHAR(512),

    status                  INTEGER      NOT NULL DEFAULT 1,
    status_flag             VARCHAR(32)  NOT NULL DEFAULT 'Active',
    deactivation_reason     TEXT,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by              VARCHAR(64),
    updated_by              VARCHAR(64),

    CONSTRAINT ck_dev_principal CHECK (
        (institution_id IS NOT NULL)::int + (tenant_id IS NOT NULL)::int = 1),
    CONSTRAINT ck_dev_purpose CHECK (purpose IN
        ('FOR_SALE', 'FOR_RENT', 'OWNER_OCCUPIED', 'COMMERCIAL_RENTAL', 'MIXED')),
    CONSTRAINT ck_dev_state CHECK (listing_state IN
        ('DRAFT', 'PENDING', 'LIVE', 'SOLD', 'WITHDRAWN', 'PRIVATE')),
    CONSTRAINT ck_dev_published CHECK (listing_state <> 'LIVE' OR published_at IS NOT NULL),
    -- A marketed development has somebody to market it. DRAFT and WITHDRAWN are exempt because a project
    -- being prepared or taken down may legitimately have neither state settled yet.
    CONSTRAINT ck_dev_selling_tenant CHECK (
        listing_state IN ('DRAFT', 'WITHDRAWN')
        OR (listing_state = 'PRIVATE') = (selling_tenant_id IS NULL)),
    CONSTRAINT ck_dev_percent CHECK (percent_complete BETWEEN 0 AND 100),
    CONSTRAINT ck_dev_percent_basis CHECK (percent_basis IN
        ('WEIGHT', 'BUDGET', 'UNITS', 'EQUAL', 'STATED')),
    CONSTRAINT ck_dev_construction CHECK (construction_status IN
        ('PLANNED', 'UNDER_CONSTRUCTION', 'COMPLETE', 'HANDED_OVER')),
    CONSTRAINT ck_dev_counts CHECK (units_total >= 0
        AND units_available >= 0 AND units_reserved >= 0 AND units_sold >= 0
        AND units_available + units_reserved + units_sold <= units_total),
    CONSTRAINT ck_dev_prices CHECK (to_price IS NULL OR from_price IS NULL OR to_price >= from_price),
    CONSTRAINT ck_dev_money CHECK (
        (budget_amount IS NULL OR budget_amount >= 0)
        AND (facility_amount IS NULL OR facility_amount >= 0))
);

CREATE INDEX idx_dev_tenant ON developments (tenant_id) WHERE tenant_id IS NOT NULL;
CREATE INDEX idx_dev_institution ON developments (institution_id) WHERE institution_id IS NOT NULL;
CREATE INDEX idx_dev_selling_tenant ON developments (selling_tenant_id)
    WHERE selling_tenant_id IS NOT NULL;
-- The public catalogue: live, newest first. Partial, for the same reason idx_properties_live is.
CREATE INDEX idx_dev_live ON developments (published_at DESC)
    WHERE listing_state = 'LIVE' AND status <> 5;
CREATE INDEX idx_dev_state ON developments (listing_state);
CREATE INDEX idx_dev_county_town ON developments (county, town);
CREATE INDEX idx_dev_construction ON developments (construction_status);

ALTER TABLE developments ADD COLUMN search_text text
    GENERATED ALWAYS AS (
        lower(coalesce(name, '') || ' ' || coalesce(description, '') || ' ' ||
              coalesce(reference, '') || ' ' || coalesce(development_type, '') || ' ' ||
              coalesce(county, '') || ' ' || coalesce(town, '') || ' ' || coalesce(estate, '') || ' ' ||
              coalesce(developer_name, '') || ' ' || coalesce(tenant_name, '') || ' ' ||
              coalesce(institution_name, ''))
    ) STORED;
CREATE INDEX idx_dev_search_trgm ON developments USING gin (search_text gin_trgm_ops);

-- ── Delegated rights ─────────────────────────────────────────────────────────────────────────────
-- The bank owns a financed project; the developer building it posts the progress.
--
-- A grant rather than a second owner: the principal on `developments` stays the single answer to "whose
-- record is this", and this table answers "who else may write to it, and what may they write". Revoking is
-- a timestamp and a reason, never a delete, because "who could post progress last March" is a question an
-- audit asks.
--
-- Rights are a single column rather than a set of booleans on purpose — a grant that means five things is
-- five grants, and the day one of them needs revoking separately a boolean column cannot express it.
CREATE TABLE development_collaborators (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    development_id      BIGINT       NOT NULL REFERENCES developments (id),
    -- The organisation being granted the right. A tenant, never an institution: a lender does not need a
    -- grant to read a project it owns, and a lender writing another lender's project is not a case.
    tenant_id           BIGINT       NOT NULL REFERENCES tenants (id),
    tenant_name         VARCHAR(255),

    rights              VARCHAR(24)  NOT NULL DEFAULT 'PROGRESS_WRITE',

    granted_by_user_id  BIGINT,
    granted_by_name     VARCHAR(160),
    granted_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    revoked_by_user_id  BIGINT,
    revoked_at          TIMESTAMPTZ,
    revoked_reason      TEXT,
    note                TEXT,

    status              INTEGER      NOT NULL DEFAULT 1,
    status_flag         VARCHAR(32)  NOT NULL DEFAULT 'Active',
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          VARCHAR(64),
    updated_by          VARCHAR(64),

    CONSTRAINT ck_collab_rights CHECK (rights IN ('PROGRESS_WRITE', 'UNITS_WRITE', 'FULL')),
    -- Taking a right away says why, the same rule ck_commission_waived and ck_booking_cancelled follow.
    CONSTRAINT ck_collab_revoked CHECK (revoked_at IS NULL OR revoked_reason IS NOT NULL)
);

-- One live grant per organisation per development. A second row would make "may they write?" depend on
-- which row was read first.
CREATE UNIQUE INDEX uk_collab_live ON development_collaborators (development_id, tenant_id)
    WHERE revoked_at IS NULL AND status <> 5;
CREATE INDEX idx_collab_development ON development_collaborators (development_id);
-- The authorisation lookup, asked once per write by a collaborating organisation.
CREATE INDEX idx_collab_tenant ON development_collaborators (tenant_id)
    WHERE revoked_at IS NULL AND status <> 5;

-- ── Phases ───────────────────────────────────────────────────────────────────────────────────────
-- Planned and actual are two pairs of columns, not one pair overwritten, plus `revised_completion_on` as the
-- current forecast. "It slipped four months" is the first question a lender asks, and a column that has been
-- overwritten cannot answer it: the planned date is the original promise and does not move, the revised date
-- is what is now expected and does.
--
-- No tenant_id or institution_id on this table or on any child below it. Deliberately: a development's owner
-- may be an institution, so a bare tenant_id would be null for exactly the bank's own projects and any
-- tenant-scoped query would filter them out of their owner's view. Access to a child is the parent's access,
-- checked once on the parent — the arrangement ProgressUpdateService.load already uses.
CREATE TABLE development_phases (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    development_id          BIGINT       NOT NULL REFERENCES developments (id),
    reference               VARCHAR(16)  NOT NULL UNIQUE,

    name                    VARCHAR(160) NOT NULL,
    description             TEXT,
    sequence_no             SMALLINT     NOT NULL DEFAULT 1,

    planned_start_on        DATE,
    planned_completion_on   DATE,
    revised_completion_on   DATE,
    actual_start_on         DATE,
    actual_completion_on    DATE,

    -- planned_spend is what the phase was expected to cost by the time it finished, and it exists now rather
    -- than later because the planned-versus-actual spend curve a lender judges a project by needs two
    -- series. Without it that chart is one line, and adding the column afterwards means restating history
    -- nobody recorded.
    budget_amount           NUMERIC(15, 2),
    planned_spend           NUMERIC(15, 2),
    committed_amount        NUMERIC(15, 2),
    spent_amount            NUMERIC(15, 2),
    currency                VARCHAR(3)   NOT NULL DEFAULT 'KES',

    -- What share of the whole project this phase is. Optional; when every phase of a development has one
    -- they must sum to 100, which the service checks because a database cannot check across rows.
    weight_pct              SMALLINT,

    percent_complete        SMALLINT     NOT NULL DEFAULT 0,
    milestone_code          VARCHAR(32),
    planned_unit_count      INTEGER,

    status                  INTEGER      NOT NULL DEFAULT 1,
    status_flag             VARCHAR(32)  NOT NULL DEFAULT 'Active',
    deactivation_reason     TEXT,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by              VARCHAR(64),
    updated_by              VARCHAR(64),

    CONSTRAINT ck_phase_percent CHECK (percent_complete BETWEEN 0 AND 100),
    CONSTRAINT ck_phase_weight CHECK (weight_pct IS NULL OR weight_pct BETWEEN 1 AND 100),
    CONSTRAINT ck_phase_planned_dates CHECK (planned_completion_on IS NULL
        OR planned_start_on IS NULL OR planned_completion_on >= planned_start_on),
    CONSTRAINT ck_phase_actual_dates CHECK (actual_completion_on IS NULL
        OR actual_start_on IS NULL OR actual_completion_on >= actual_start_on),
    -- A phase that is finished is finished. 100% with no completion date, or a completion date at 80%, is a
    -- phase whose two answers disagree — and the project figure derived from it would inherit the argument.
    CONSTRAINT ck_phase_complete CHECK ((percent_complete = 100) = (actual_completion_on IS NOT NULL)),
    CONSTRAINT ck_phase_money CHECK (
        (budget_amount IS NULL OR budget_amount >= 0)
        AND (planned_spend IS NULL OR planned_spend >= 0)
        AND (committed_amount IS NULL OR committed_amount >= 0)
        AND (spent_amount IS NULL OR spent_amount >= 0))
);

CREATE UNIQUE INDEX uk_phase_sequence ON development_phases (development_id, sequence_no)
    WHERE status <> 5;
CREATE INDEX idx_phase_development ON development_phases (development_id, sequence_no);
-- Lets a unit's phase be constrained to the same development, by the composite foreign key below.
ALTER TABLE development_phases ADD CONSTRAINT uk_phase_dev UNIQUE (id, development_id);

-- ── Unit types (typologies) ──────────────────────────────────────────────────────────────────────
-- "Two bedroom, 92 m², from KES 9.5M, 70 units". This is what a buyer chooses between; the unit below is
-- what one of them ends up owning.
CREATE TABLE development_unit_types (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    development_id          BIGINT       NOT NULL REFERENCES developments (id),
    reference               VARCHAR(16)  NOT NULL UNIQUE,

    code                    VARCHAR(32)  NOT NULL,
    name                    VARCHAR(160) NOT NULL,
    description             TEXT,
    property_type           VARCHAR(32)  NOT NULL REFERENCES property_type_configs (code),

    -- Zero bedrooms is the truthful answer for a studio, not null. Whether the form asks at all is decided
    -- by the property type's has_bedrooms flag, exactly as the listing form already does.
    bedrooms                SMALLINT,
    bathrooms               SMALLINT,
    parking_spaces          SMALLINT,
    floor_area_sqm          NUMERIC(10, 2),
    balcony_area_sqm        NUMERIC(10, 2),

    list_price              NUMERIC(15, 2),
    currency                VARCHAR(3)   NOT NULL DEFAULT 'KES',
    service_charge          NUMERIC(15, 2),

    planned_unit_count      INTEGER      NOT NULL DEFAULT 0,

    -- Counted from development_units. One writer: DevelopmentInventoryService.
    units_total             INTEGER      NOT NULL DEFAULT 0,
    units_available         INTEGER      NOT NULL DEFAULT 0,
    units_reserved          INTEGER      NOT NULL DEFAULT 0,
    units_sold              INTEGER      NOT NULL DEFAULT 0,
    from_price              NUMERIC(15, 2),
    construction_status     VARCHAR(24)  NOT NULL DEFAULT 'PLANNED',

    floor_plan_key          VARCHAR(512),
    primary_image_key       VARCHAR(512),
    sort_order              INTEGER      NOT NULL DEFAULT 100,

    status                  INTEGER      NOT NULL DEFAULT 1,
    status_flag             VARCHAR(32)  NOT NULL DEFAULT 'Active',
    deactivation_reason     TEXT,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by              VARCHAR(64),
    updated_by              VARCHAR(64),

    -- Not an equality: a NOT_FOR_SALE or RETAINED unit counts in units_total and in none of the three.
    CONSTRAINT ck_unit_type_counts CHECK (units_total >= 0
        AND units_available >= 0 AND units_reserved >= 0 AND units_sold >= 0
        AND units_available + units_reserved + units_sold <= units_total),
    CONSTRAINT ck_unit_type_construction CHECK (construction_status IN
        ('PLANNED', 'UNDER_CONSTRUCTION', 'COMPLETE', 'HANDED_OVER')),
    CONSTRAINT ck_unit_type_price CHECK (list_price IS NULL OR list_price >= 0),
    CONSTRAINT ck_unit_type_area CHECK (floor_area_sqm IS NULL OR floor_area_sqm > 0),
    CONSTRAINT ck_unit_type_planned CHECK (planned_unit_count >= 0)
);

CREATE UNIQUE INDEX uk_unit_type_code ON development_unit_types (development_id, code)
    WHERE status <> 5;
CREATE INDEX idx_unit_type_development ON development_unit_types (development_id, sort_order);
ALTER TABLE development_unit_types ADD CONSTRAINT uk_unit_type_dev UNIQUE (id, development_id);

-- ── Units ────────────────────────────────────────────────────────────────────────────────────────
-- The inventory row. What makes "who bought B4-12" and "60 of 70 available" answerable, and the only place
-- construction status is a fact about a physical thing rather than a figure derived from other rows.
CREATE TABLE development_units (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    development_id          BIGINT       NOT NULL,
    unit_type_id            BIGINT       NOT NULL,
    phase_id                BIGINT,
    reference               VARCHAR(16)  NOT NULL UNIQUE,

    unit_label              VARCHAR(32)  NOT NULL,
    block                   VARCHAR(32),
    floor_no                SMALLINT,
    door_no                 VARCHAR(16),

    -- Overrides the typology's price where this one differs, which a top-floor corner usually does.
    list_price              NUMERIC(15, 2),
    currency                VARCHAR(3)   NOT NULL DEFAULT 'KES',

    sale_state              VARCHAR(16)  NOT NULL DEFAULT 'AVAILABLE',
    construction_status     VARCHAR(24)  NOT NULL DEFAULT 'PLANNED',
    completed_on            DATE,
    handed_over_on          DATE,

    -- Who bought it: the account when there is one, the name when there is not. The same arrangement
    -- properties.client_owner_name already uses, and for the same reason — a bank's off-plan buyer from 2019
    -- has no account on this platform, and requiring one would mean the sale could not be recorded.
    --
    -- Personal data. Deliberately absent from every search_text in this migration, from every public
    -- response record, and from the reporting views.
    buyer_user_id           BIGINT       REFERENCES users (id),
    buyer_name              VARCHAR(160),
    buyer_phone             VARCHAR(32),
    buyer_email             VARCHAR(128),
    -- Where the sale came from, when it came through the platform. The link that stops an accepted offer and
    -- a sold unit being two unrelated records of the same event.
    purchase_request_id     BIGINT       REFERENCES purchase_requests (id),

    reserved_at             TIMESTAMPTZ,
    reserved_until          TIMESTAMPTZ,
    sold_price              NUMERIC(15, 2),
    sold_at                 TIMESTAMPTZ,

    notes                   TEXT,

    status                  INTEGER      NOT NULL DEFAULT 1,
    status_flag             VARCHAR(32)  NOT NULL DEFAULT 'Active',
    deactivation_reason     TEXT,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by              VARCHAR(64),
    updated_by              VARCHAR(64),

    -- Composite, so a unit cannot be pointed at another development's typology or phase. The database says
    -- it rather than every service remembering to.
    CONSTRAINT fk_unit_type FOREIGN KEY (unit_type_id, development_id)
        REFERENCES development_unit_types (id, development_id),
    CONSTRAINT fk_unit_phase FOREIGN KEY (phase_id, development_id)
        REFERENCES development_phases (id, development_id),

    CONSTRAINT ck_unit_sale_state CHECK (sale_state IN
        ('AVAILABLE', 'HELD', 'RESERVED', 'SOLD', 'NOT_FOR_SALE', 'RETAINED')),
    CONSTRAINT ck_unit_construction CHECK (construction_status IN
        ('PLANNED', 'UNDER_CONSTRUCTION', 'COMPLETE', 'HANDED_OVER')),
    -- A sold unit has a buyer, a price and a date. Three things every report over this table assumes.
    CONSTRAINT ck_unit_sold CHECK (sale_state <> 'SOLD'
        OR (sold_at IS NOT NULL AND sold_price IS NOT NULL
            AND (buyer_user_id IS NOT NULL OR buyer_name IS NOT NULL))),
    CONSTRAINT ck_unit_reserved CHECK (sale_state NOT IN ('RESERVED', 'HELD')
        OR reserved_until IS NOT NULL),
    CONSTRAINT ck_unit_handover CHECK (construction_status <> 'HANDED_OVER'
        OR handed_over_on IS NOT NULL),
    CONSTRAINT ck_unit_completed CHECK (construction_status NOT IN ('COMPLETE', 'HANDED_OVER')
        OR completed_on IS NOT NULL),
    CONSTRAINT ck_unit_price CHECK (list_price IS NULL OR list_price >= 0)
);

CREATE UNIQUE INDEX uk_unit_label ON development_units (development_id, unit_label) WHERE status <> 5;
-- The inventory grid's query, and the recount's: by development, by typology, by state.
CREATE INDEX idx_unit_inventory ON development_units (development_id, unit_type_id, sale_state)
    WHERE status <> 5;
CREATE INDEX idx_unit_type_state ON development_units (unit_type_id, sale_state) WHERE status <> 5;
CREATE INDEX idx_unit_phase ON development_units (phase_id) WHERE phase_id IS NOT NULL;
-- "What have I bought", from the buyer's own portal. Partial, because most units have no account behind them.
CREATE INDEX idx_unit_buyer ON development_units (buyer_user_id) WHERE buyer_user_id IS NOT NULL;
CREATE INDEX idx_unit_reservation_expiry ON development_units (reserved_until)
    WHERE sale_state IN ('HELD', 'RESERVED') AND status <> 5;

-- ── The listing's link into all of it ────────────────────────────────────────────────────────────
-- Both nullable, and every existing row keeps null: an ordinary listing is exactly what it was, which is why
-- this migration needs no backfill.
--
-- A typology gets a listing so that enquiries, viewings, offers, valuations, media, promotions and
-- commissions keep working through the ten tables that already reference properties(id). What the
-- marketplace *shows* is the development card; the typology rows are excluded from that result list by one
-- predicate rather than by not existing.
ALTER TABLE properties
    ADD COLUMN development_id      BIGINT REFERENCES developments (id),
    ADD COLUMN unit_type_id        BIGINT REFERENCES development_unit_types (id),
    -- Label caches for the card, so a result names its project and its availability without two joins.
    -- One writer: DevelopmentInventoryService.
    ADD COLUMN development_name    VARCHAR(255),
    ADD COLUMN units_available     INTEGER,
    ADD COLUMN units_total         INTEGER,
    ADD COLUMN construction_status VARCHAR(24);

ALTER TABLE properties ADD CONSTRAINT ck_property_unit_type
    CHECK (unit_type_id IS NULL OR development_id IS NOT NULL);
ALTER TABLE properties ADD CONSTRAINT ck_property_construction
    CHECK (construction_status IS NULL OR construction_status IN
        ('PLANNED', 'UNDER_CONSTRUCTION', 'COMPLETE', 'HANDED_OVER'));

-- At most one live listing per typology, enforced rather than remembered: "60 of 70 available" has to have
-- exactly one place a buyer can read it.
CREATE UNIQUE INDEX uk_property_unit_type ON properties (unit_type_id)
    WHERE unit_type_id IS NOT NULL AND status <> 5;
CREATE INDEX idx_properties_development ON properties (development_id)
    WHERE development_id IS NOT NULL;
CREATE INDEX idx_properties_construction ON properties (construction_status)
    WHERE listing_state = 'LIVE' AND status <> 5;
