-- ═════════════════════════════════════════════════════════════════════════════════════════════════
-- Phase 1 / M2 — the thing the platform is for (BRD FR008–FR019, FR065–FR096)
--
-- Everything built so far decides who may do what. This is the first table that holds what they do it to.
--
-- <h2>What is here, and what is deliberately not</h2>
--
-- Properties and their photographs. Not documents: title deeds and approved plans are exactly the sensitive
-- class §3.9 of the plan says gets its own vault with per-document ACLs and encryption at rest, and building
-- them into general media storage now is building the thing that plan says to build properly later. They
-- arrive with M8, where the KYC pack gives them a home.
--
-- Not saved listings or search alerts either: both are a buyer's own rows, and they belong beside M1's consent
-- store rather than in front of it.
--
-- <h2>Lifecycle, and why publication goes through the approvals queue</h2>
--
-- DRAFT → PENDING → LIVE, then SOLD or WITHDRAWN. The step from PENDING to LIVE is a Maker/Checker decision
-- (§3.2, BRD FR090): a listing manager submits, somebody else at the same seller approves, and the platform
-- can decide for a seller too small to have two people. The state column is the listing's own; the queue row
-- records who asked and who agreed.
--
-- <h2>Search</h2>
--
-- One generated column for free text, and real columns for everything a buyer filters by — price, bedrooms,
-- county, type. The BRD's facets are those columns with indexes on them, not a separate search service: a
-- trigram index answers "kilimani" and a btree answers "under 15 million", and both are Postgres.
-- ═════════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE properties (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Whose listing. Every read goes through TenantScope, so this column is the isolation.
    tenant_id              BIGINT       NOT NULL,
    -- Label cache: a marketplace card names the seller without joining.
    tenant_name            VARCHAR(255),

    reference              VARCHAR(16)  NOT NULL UNIQUE,

    title                  VARCHAR(255) NOT NULL,
    description            TEXT,

    property_type          VARCHAR(32)  NOT NULL,
    listing_type           VARCHAR(16)  NOT NULL DEFAULT 'SALE',
    tenure                 VARCHAR(16),

    -- NUMERIC, not a float. A price is money, and money in binary floating point is money that does not add
    -- up. The currency travels with it because a seller's currency is their own column on tenants.
    price                  NUMERIC(15, 2) NOT NULL,
    currency               VARCHAR(3)   NOT NULL DEFAULT 'KES',
    service_charge         NUMERIC(15, 2),
    price_negotiable       BOOLEAN      NOT NULL DEFAULT false,

    bedrooms               SMALLINT,
    bathrooms              SMALLINT,
    parking_spaces         SMALLINT,
    floor_area_sqm         NUMERIC(10, 2),
    plot_area_acres        NUMERIC(10, 3),
    year_built             SMALLINT,

    county                 VARCHAR(64),
    town                   VARCHAR(64),
    estate                 VARCHAR(128),
    address_line           TEXT,
    -- Coordinates as plain numerics rather than PostGIS: what M2 needs is "near this town" and a pin on a
    -- map, which these answer. A radius search over a geography column is a different feature with a
    -- different extension behind it, and adding the extension for a field nothing queries yet would be a
    -- deployment requirement bought for nothing.
    latitude               NUMERIC(9, 6),
    longitude              NUMERIC(9, 6),

    -- The BRD's green features, as columns because they are facets a buyer filters on rather than free text.
    green_certified        BOOLEAN      NOT NULL DEFAULT false,
    green_certification    VARCHAR(64),
    energy_rating          VARCHAR(8),
    has_solar              BOOLEAN      NOT NULL DEFAULT false,
    has_borehole           BOOLEAN      NOT NULL DEFAULT false,
    rainwater_harvesting   BOOLEAN      NOT NULL DEFAULT false,

    listing_state          VARCHAR(16)  NOT NULL DEFAULT 'DRAFT',
    published_at           TIMESTAMPTZ,
    sold_at                TIMESTAMPTZ,
    withdrawn_at           TIMESTAMPTZ,
    withdrawn_reason       TEXT,

    -- Label cache for the card, maintained by the media service: a list of forty properties should not be
    -- forty queries for one photograph each.
    primary_image_key      VARCHAR(512),

    status                 INTEGER      NOT NULL DEFAULT 1,
    status_flag            VARCHAR(32)  NOT NULL DEFAULT 'Active',
    deactivation_reason    TEXT,

    created_at             TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by             VARCHAR(64),
    updated_by             VARCHAR(64),

    CONSTRAINT ck_property_state
        CHECK (listing_state IN ('DRAFT', 'PENDING', 'LIVE', 'SOLD', 'WITHDRAWN')),
    CONSTRAINT ck_property_listing_type
        CHECK (listing_type IN ('SALE', 'RENT')),
    CONSTRAINT ck_property_price CHECK (price >= 0),
    -- A live listing has been published. The public query trusts the pair, so the database says it rather
    -- than the service remembering to.
    CONSTRAINT ck_property_published
        CHECK (listing_state <> 'LIVE' OR published_at IS NOT NULL)
);

CREATE INDEX idx_properties_tenant ON properties (tenant_id);
-- The public query: live listings, newest first. Partial, because the marketplace never asks for anything
-- else and an index carrying drafts would be mostly rows no visitor can see.
CREATE INDEX idx_properties_live ON properties (published_at DESC)
    WHERE listing_state = 'LIVE' AND status <> 5;
CREATE INDEX idx_properties_state ON properties (listing_state);
-- The facets, as the BRD calls them.
CREATE INDEX idx_properties_price ON properties (price);
CREATE INDEX idx_properties_county_town ON properties (county, town);
CREATE INDEX idx_properties_type ON properties (property_type);
CREATE INDEX idx_properties_bedrooms ON properties (bedrooms);
CREATE INDEX idx_properties_green ON properties (green_certified) WHERE green_certified;

ALTER TABLE properties ADD COLUMN search_text text
    GENERATED ALWAYS AS (
        lower(coalesce(title, '') || ' ' || coalesce(description, '') || ' ' ||
              coalesce(reference, '') || ' ' || coalesce(property_type, '') || ' ' ||
              coalesce(county, '') || ' ' || coalesce(town, '') || ' ' || coalesce(estate, '') || ' ' ||
              coalesce(tenant_name, ''))
    ) STORED;
CREATE INDEX idx_properties_search_trgm ON properties USING gin (search_text gin_trgm_ops);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- Photographs.
--
-- The key is authoritative and the URL is recomputed on read — the same rule StorageService states, for the
-- same reason: a URL expires, a CDN changes, a bucket moves, and a row holding one freezes one deployment's
-- arrangement into the data.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE property_media (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id   BIGINT       NOT NULL REFERENCES properties (id),
    tenant_id     BIGINT       NOT NULL,
    storage_key   VARCHAR(512) NOT NULL,
    content_type  VARCHAR(64),
    size_bytes    BIGINT,
    caption       VARCHAR(255),
    sort_order    INTEGER      NOT NULL DEFAULT 0,
    is_primary    BOOLEAN      NOT NULL DEFAULT false,
    status        INTEGER      NOT NULL DEFAULT 1,
    status_flag   VARCHAR(32)  NOT NULL DEFAULT 'Active',
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by    VARCHAR(64),
    updated_by    VARCHAR(64)
);

CREATE INDEX idx_property_media_property ON property_media (property_id, sort_order);
-- One primary photograph per property, enforced rather than remembered: the card reads whichever row says it
-- is primary, and two of them would make the card's contents a matter of query order.
CREATE UNIQUE INDEX uk_property_media_primary ON property_media (property_id)
    WHERE is_primary AND status <> 5;
