-- ═════════════════════════════════════════════════════════════════════════════════════════════════
-- M1 / plan §3.8 — the consent store (BRD FR004–FR005)
--
-- <h2>Why this is a table and not two booleans on a profile</h2>
--
-- The requirement is not "let a buyer switch marketing off". It is "prove, on a date, that this person
-- agreed to be contacted this way for this reason" — and a mutable boolean cannot answer a question about
-- the past. So the current position is one row per (person, channel, purpose), and every movement of that
-- row is copied into an append-only history by a trigger.
--
-- <h2>Keyed on the person, not the profile</h2>
--
-- Deliberately {@code user_id}, though everything about authorisation moved to {@code user_profiles} in
-- Phase 0a. Consent is a fact about a natural person and the address or handset they answer on: somebody
-- who is a buyer on Monday and a seller's owner on Tuesday has one inbox and gave one answer about it. A
-- per-profile store would let the same person be simultaneously opted in and opted out on the same address,
-- which is not a state the regulation contemplates and not one a support agent could explain.
--
-- <h2>Transactional is not opt-out-able, and the database says so</h2>
--
-- The plan asks for that to be "marked as such in the purpose list rather than by convention". A CHECK is
-- the strongest available form of that marking: a receipt, a password reset and a viewing confirmation are
-- not marketing, and a person who switched them off would be locked out of things they asked for. The
-- {@code sendSensitive*} paths in NotifyClient already ignore the global channel switches for exactly this
-- reason; this makes the same statement about the individual's own preferences.
-- ═════════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE consent_preferences (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id             BIGINT      NOT NULL REFERENCES users (id),

    channel             VARCHAR(16) NOT NULL,
    purpose             VARCHAR(32) NOT NULL,
    granted             BOOLEAN     NOT NULL,

    -- Where the answer came from. "They ticked it at registration" and "an administrator set it" are
    -- different evidentiary weights, and the difference is only recoverable if it is recorded at the time.
    source              VARCHAR(32) NOT NULL DEFAULT 'PREFERENCES',
    captured_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Copied into every history row by the trigger below. Kept on the current row too so the latest answer
    -- carries its own provenance without a join.
    captured_ip         VARCHAR(64),
    captured_user_agent TEXT,

    status              INTEGER     NOT NULL DEFAULT 1,
    status_flag         VARCHAR(32) NOT NULL DEFAULT 'Active',

    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by          VARCHAR(64),
    updated_by          VARCHAR(64),

    CONSTRAINT ck_consent_channel CHECK (channel IN ('EMAIL', 'SMS')),
    CONSTRAINT ck_consent_purpose
        CHECK (purpose IN ('TRANSACTIONAL', 'PROPERTY_ALERTS', 'PROMOTIONAL')),
    -- See the header. Transactional messages are the ones that carry out something the person asked for.
    CONSTRAINT ck_consent_transactional CHECK (purpose <> 'TRANSACTIONAL' OR granted)
);

-- One current answer per person, channel and purpose. The uniqueness is what makes "what is their position
-- right now" a single-row read rather than a max-by-date over a history.
CREATE UNIQUE INDEX uk_consent_user_channel_purpose
    ON consent_preferences (user_id, channel, purpose);
CREATE INDEX idx_consent_user ON consent_preferences (user_id);
-- The dispatcher's question, asked once per alert: who may I mail about listings?
CREATE INDEX idx_consent_granted ON consent_preferences (purpose, channel) WHERE granted;

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- The history.
--
-- Written by a trigger rather than by the service, because "the code always remembers to record the change"
-- is the assumption this table exists to remove. A service that updates the row directly — a repair script,
-- a future bulk import, a migration — still leaves a trail.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE consent_preference_history (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consent_preference_id BIGINT      NOT NULL,
    user_id               BIGINT      NOT NULL,
    channel               VARCHAR(16) NOT NULL,
    purpose               VARCHAR(32) NOT NULL,
    -- NULL on the first row for a preference: there was no previous position, which is different from
    -- having previously been false.
    previous_granted      BOOLEAN,
    new_granted           BOOLEAN     NOT NULL,
    source                VARCHAR(32) NOT NULL,
    changed_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    changed_by            VARCHAR(64),
    captured_ip           VARCHAR(64),
    captured_user_agent   TEXT
);

CREATE INDEX idx_consent_history_pref ON consent_preference_history (consent_preference_id, changed_at DESC);
CREATE INDEX idx_consent_history_user ON consent_preference_history (user_id, changed_at DESC);

CREATE OR REPLACE FUNCTION consent_preferences_record_history() RETURNS trigger AS $$
BEGIN
    IF tg_op = 'INSERT' THEN
        INSERT INTO consent_preference_history (
            consent_preference_id, user_id, channel, purpose,
            previous_granted, new_granted, source, changed_at, changed_by,
            captured_ip, captured_user_agent)
        VALUES (new.id, new.user_id, new.channel, new.purpose,
                NULL, new.granted, new.source, new.captured_at, coalesce(new.updated_by, new.created_by),
                new.captured_ip, new.captured_user_agent);
        RETURN new;
    END IF;

    -- Only movements. An UPDATE that touches nothing consent-bearing — a status change, a re-save of the
    -- same answer — is not a change of position and would only pad the evidence with noise.
    IF new.granted IS DISTINCT FROM old.granted OR new.source IS DISTINCT FROM old.source THEN
        INSERT INTO consent_preference_history (
            consent_preference_id, user_id, channel, purpose,
            previous_granted, new_granted, source, changed_at, changed_by,
            captured_ip, captured_user_agent)
        VALUES (new.id, new.user_id, new.channel, new.purpose,
                old.granted, new.granted, new.source, new.captured_at, new.updated_by,
                new.captured_ip, new.captured_user_agent);
    END IF;
    RETURN new;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_consent_preferences_history
    AFTER INSERT OR UPDATE ON consent_preferences
    FOR EACH ROW EXECUTE FUNCTION consent_preferences_record_history();

-- The same guard the audit trail carries, for the same reason: a history that can be edited is a claim
-- about the past, not a record of it. Statement-level — nothing here needs the row.
CREATE OR REPLACE FUNCTION consent_preference_history_append_only() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'consent_preference_history is append-only — % is not permitted', tg_op
        USING errcode = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_consent_history_no_update
    BEFORE UPDATE ON consent_preference_history
    EXECUTE FUNCTION consent_preference_history_append_only();

CREATE TRIGGER trg_consent_history_no_delete
    BEFORE DELETE ON consent_preference_history
    EXECUTE FUNCTION consent_preference_history_append_only();

COMMENT ON TABLE consent_preference_history IS
    'Append-only. Written by trigger from consent_preferences; UPDATE and DELETE are refused.';

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- Backfill.
--
-- Everybody who already has an account gets the transactional consents (they are not optional and the CHECK
-- above requires them true) and an explicit opt-out of everything else. Silence is not consent: nobody
-- registered before today was ever asked about property alerts or marketing, so the honest recorded position
-- is "no", with the source saying it was assumed rather than given.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
INSERT INTO consent_preferences (user_id, channel, purpose, granted, source, created_by, updated_by)
SELECT u.id, c.channel, p.purpose,
       p.purpose = 'TRANSACTIONAL',
       'BACKFILL', 'flyway', 'flyway'
FROM users u
         CROSS JOIN (VALUES ('EMAIL'), ('SMS')) AS c (channel)
         CROSS JOIN (VALUES ('TRANSACTIONAL'), ('PROPERTY_ALERTS'), ('PROMOTIONAL')) AS p (purpose);
