-- ═════════════════════════════════════════════════════════════════════════════════════════════════
-- M4 — leads: the three things a buyer does about a listing (BRD FR035–FR048)
--
-- Ask a question, arrange to see it, offer to buy it. Three tables rather than one polymorphic
-- "interaction" table, because the three have genuinely different shapes: an enquiry is a conversation, a
-- viewing is an appointment with two parties agreeing a time, and a purchase request is an offer with a
-- decision on it. One table with a `kind` column would carry two thirds nulls in every row and a CHECK
-- nobody could read.
--
-- <h2>Two sides, one row</h2>
--
-- Every row here carries both `user_id` (the buyer, the person) and `tenant_id` (the seller organisation).
-- The buyer reads their own through {@code /api/v1/me}; the seller reads theirs through TenantScope. That
-- is the only place in the schema where those two visibility rules meet on the same row, and it is
-- deliberate: a lead *is* the meeting.
--
-- <h2>Contact details are snapshots, not caches</h2>
--
-- `buyer_name`, `buyer_email` and `buyer_phone` are copied at creation and never refreshed. Not a label
-- cache — a snapshot in the plan's sense: these are the details the buyer chose to give for *this* enquiry,
-- and a seller who called the number on a lead from March should find the number that was on it in March.
-- ═════════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE enquiry_tickets (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    reference            VARCHAR(16)  NOT NULL UNIQUE,

    -- The seller's side. TenantScope's column.
    tenant_id            BIGINT       NOT NULL,
    tenant_name          VARCHAR(255),

    -- The listing. Kept by id and by reference: the id joins, the reference survives the listing.
    property_id          BIGINT       NOT NULL REFERENCES properties (id),
    property_reference   VARCHAR(16)  NOT NULL,
    property_title       VARCHAR(255),

    -- The buyer's side.
    user_id              BIGINT       NOT NULL REFERENCES users (id),
    buyer_name           VARCHAR(160),
    buyer_email          VARCHAR(128),
    buyer_phone          VARCHAR(32),

    subject              VARCHAR(180),

    state                VARCHAR(16)  NOT NULL DEFAULT 'OPEN',
    -- Who at the seller is dealing with it. Null is "nobody yet", which is a real and useful state.
    assigned_to_user_id  BIGINT,
    assigned_to_name     VARCHAR(160),

    -- Maintained aggregates (the denormalisation convention): the inbox sorts and counts on these rather
    -- than joining the message table for every row.
    message_count        INTEGER      NOT NULL DEFAULT 0,
    last_message_at      TIMESTAMPTZ,
    last_message_side    VARCHAR(16),
    -- Whether the seller owes a reply. Derived, but stored because "what is waiting on me" is the inbox's
    -- default filter and a derived sort would be a subquery per row.
    awaiting_seller      BOOLEAN      NOT NULL DEFAULT true,

    closed_at            TIMESTAMPTZ,
    closed_by_user_id    BIGINT,
    close_reason         TEXT,

    status               INTEGER      NOT NULL DEFAULT 1,
    status_flag          VARCHAR(32)  NOT NULL DEFAULT 'Active',

    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by           VARCHAR(64),
    updated_by           VARCHAR(64),

    CONSTRAINT ck_enquiry_state CHECK (state IN ('OPEN', 'ANSWERED', 'CLOSED')),
    CONSTRAINT ck_enquiry_closed CHECK (state <> 'CLOSED' OR closed_at IS NOT NULL)
);

CREATE INDEX idx_enquiry_tenant ON enquiry_tickets (tenant_id, last_message_at DESC);
CREATE INDEX idx_enquiry_user ON enquiry_tickets (user_id, created_at DESC);
CREATE INDEX idx_enquiry_property ON enquiry_tickets (property_id);
-- The inbox's default view: what this seller still owes an answer on.
CREATE INDEX idx_enquiry_waiting ON enquiry_tickets (tenant_id, last_message_at DESC)
    WHERE awaiting_seller AND status <> 5;

ALTER TABLE enquiry_tickets ADD COLUMN search_text text
    GENERATED ALWAYS AS (
        lower(coalesce(reference, '') || ' ' || coalesce(subject, '') || ' ' ||
              coalesce(property_reference, '') || ' ' || coalesce(property_title, '') || ' ' ||
              coalesce(buyer_name, '') || ' ' || coalesce(buyer_email, ''))
    ) STORED;
CREATE INDEX idx_enquiry_search_trgm ON enquiry_tickets USING gin (search_text public.gin_trgm_ops);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- The conversation.
--
-- No UPDATE path in the application and no edit in the interface: a message is what somebody said. The
-- table is not trigger-guarded like the audit trail, because a typo in a message to a customer is a
-- different class of problem from a tampered audit record — but nothing here offers to change one.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE enquiry_messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id       BIGINT      NOT NULL REFERENCES enquiry_tickets (id),
    -- Which side said it. Stored rather than inferred from whether the author has a tenant: the same person
    -- can hold a buyer profile and a seller profile, and inference would attribute their message to
    -- whichever hat they happened to be wearing when somebody later read the row.
    author_side     VARCHAR(16) NOT NULL,
    author_user_id  BIGINT,
    author_name     VARCHAR(160),
    body            TEXT        NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ck_message_side CHECK (author_side IN ('BUYER', 'SELLER', 'PLATFORM'))
);

CREATE INDEX idx_enquiry_message_ticket ON enquiry_messages (ticket_id, created_at);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- Viewings.
--
-- Two times on the row, not one. `requested_at` is what the buyer asked for and never changes; `slot_at`
-- is what was agreed. Overwriting the request with the agreed time would lose the thing a seller needs
-- when a buyer says "but I asked for Saturday".
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE site_visits (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    reference           VARCHAR(16)  NOT NULL UNIQUE,

    tenant_id           BIGINT       NOT NULL,
    tenant_name         VARCHAR(255),
    property_id         BIGINT       NOT NULL REFERENCES properties (id),
    property_reference  VARCHAR(16)  NOT NULL,
    property_title      VARCHAR(255),

    user_id             BIGINT       NOT NULL REFERENCES users (id),
    buyer_name          VARCHAR(160),
    buyer_email         VARCHAR(128),
    buyer_phone         VARCHAR(32),

    requested_at        TIMESTAMPTZ  NOT NULL,
    slot_at             TIMESTAMPTZ,
    party_size          SMALLINT,
    buyer_note          TEXT,

    state               VARCHAR(16)  NOT NULL DEFAULT 'REQUESTED',
    seller_note         TEXT,
    decided_by_user_id  BIGINT,
    decided_at          TIMESTAMPTZ,
    outcome_note        TEXT,

    status              INTEGER      NOT NULL DEFAULT 1,
    status_flag         VARCHAR(32)  NOT NULL DEFAULT 'Active',

    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          VARCHAR(64),
    updated_by          VARCHAR(64),

    CONSTRAINT ck_visit_state
        CHECK (state IN ('REQUESTED', 'CONFIRMED', 'DECLINED', 'COMPLETED', 'CANCELLED')),
    -- A confirmed viewing has a time everyone agreed on. The buyer's screen trusts the pair, so the
    -- database says it rather than the service remembering to.
    CONSTRAINT ck_visit_confirmed CHECK (state <> 'CONFIRMED' OR slot_at IS NOT NULL),
    CONSTRAINT ck_visit_decided
        CHECK (state IN ('REQUESTED', 'CANCELLED') OR decided_at IS NOT NULL)
);

CREATE INDEX idx_visit_tenant ON site_visits (tenant_id, requested_at DESC);
CREATE INDEX idx_visit_user ON site_visits (user_id, requested_at DESC);
CREATE INDEX idx_visit_property ON site_visits (property_id);
-- The seller's diary: what is agreed and still ahead.
CREATE INDEX idx_visit_upcoming ON site_visits (tenant_id, slot_at)
    WHERE state = 'CONFIRMED' AND status <> 5;

ALTER TABLE site_visits ADD COLUMN search_text text
    GENERATED ALWAYS AS (
        lower(coalesce(reference, '') || ' ' || coalesce(property_reference, '') || ' ' ||
              coalesce(property_title, '') || ' ' || coalesce(buyer_name, '') || ' ' ||
              coalesce(buyer_email, '') || ' ' || coalesce(state, ''))
    ) STORED;
CREATE INDEX idx_visit_search_trgm ON site_visits USING gin (search_text public.gin_trgm_ops);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- Purchase requests.
--
-- An expression of intent, not a contract — the BRD's funnel ends here and conveyancing does not exist on
-- this platform. The affordability check and the mortgage product are carried by *reference* rather than by
-- foreign key: a buyer attaches the sums they did, and neither the check nor the product should be
-- undeletable because somebody once pointed at it.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE purchase_requests (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    reference             VARCHAR(16)  NOT NULL UNIQUE,

    tenant_id             BIGINT       NOT NULL,
    tenant_name           VARCHAR(255),
    property_id           BIGINT       NOT NULL REFERENCES properties (id),
    property_reference    VARCHAR(16)  NOT NULL,
    property_title        VARCHAR(255),
    -- The asking price when the offer was made. An offer read a month later means nothing without it.
    asking_price          NUMERIC(15, 2),

    user_id               BIGINT       NOT NULL REFERENCES users (id),
    buyer_name            VARCHAR(160),
    buyer_email           VARCHAR(128),
    buyer_phone           VARCHAR(32),

    offer_amount          NUMERIC(15, 2) NOT NULL,
    currency              VARCHAR(3)   NOT NULL DEFAULT 'KES',
    financing             VARCHAR(16)  NOT NULL DEFAULT 'MORTGAGE',
    affordability_reference VARCHAR(16),
    product_reference     VARCHAR(16),
    deposit_available     NUMERIC(15, 2),
    buyer_message         TEXT,

    state                 VARCHAR(16)  NOT NULL DEFAULT 'SUBMITTED',
    decided_by_user_id    BIGINT,
    decided_at            TIMESTAMPTZ,
    decision_note         TEXT,

    status                INTEGER      NOT NULL DEFAULT 1,
    status_flag           VARCHAR(32)  NOT NULL DEFAULT 'Active',

    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by            VARCHAR(64),
    updated_by            VARCHAR(64),

    CONSTRAINT ck_purchase_state
        CHECK (state IN ('SUBMITTED', 'UNDER_REVIEW', 'ACCEPTED', 'DECLINED', 'WITHDRAWN')),
    CONSTRAINT ck_purchase_financing CHECK (financing IN ('CASH', 'MORTGAGE', 'PART_EXCHANGE')),
    CONSTRAINT ck_purchase_offer CHECK (offer_amount > 0),
    CONSTRAINT ck_purchase_decided
        CHECK (state IN ('SUBMITTED', 'UNDER_REVIEW', 'WITHDRAWN') OR decided_at IS NOT NULL)
);

-- One *live* offer per buyer per property. A second while the first is outstanding is a changed mind, which
-- is an edit of the first rather than a second offer for a seller to reconcile — but a buyer whose offer was
-- declined in March may well offer again in June, so the index is partial rather than a table constraint
-- over the state column.
CREATE UNIQUE INDEX uk_purchase_live ON purchase_requests (user_id, property_id)
    WHERE state IN ('SUBMITTED', 'UNDER_REVIEW') AND status <> 5;

CREATE INDEX idx_purchase_tenant ON purchase_requests (tenant_id, created_at DESC);
CREATE INDEX idx_purchase_user ON purchase_requests (user_id, created_at DESC);
CREATE INDEX idx_purchase_property ON purchase_requests (property_id);

ALTER TABLE purchase_requests ADD COLUMN search_text text
    GENERATED ALWAYS AS (
        lower(coalesce(reference, '') || ' ' || coalesce(property_reference, '') || ' ' ||
              coalesce(property_title, '') || ' ' || coalesce(buyer_name, '') || ' ' ||
              coalesce(buyer_email, '') || ' ' || coalesce(state, ''))
    ) STORED;
CREATE INDEX idx_purchase_search_trgm ON purchase_requests USING gin (search_text public.gin_trgm_ops);
