-- pg_trgm's operator class, wherever the extension lives.
-- An extension exists once per database, in one schema, and on a shared server that schema is whichever
-- application installed it first — public on one machine, another application's schema on the next. Rather
-- than guess, look it up and put it on this transaction's search path; Flyway runs the whole script in one
-- transaction, so every gin_trgm_ops below resolves. Installs it into our own schema if nobody has yet.
DO $$
DECLARE ext_schema text;
BEGIN
    SELECT n.nspname INTO ext_schema
      FROM pg_extension e JOIN pg_namespace n ON n.oid = e.extnamespace
     WHERE e.extname = 'pg_trgm';
    IF ext_schema IS NULL THEN
        EXECUTE 'CREATE EXTENSION pg_trgm';
        ext_schema := current_schema();
    END IF;
    EXECUTE format('SET LOCAL search_path TO %I, %I', current_schema(), ext_schema);
END $$;

-- ═════════════════════════════════════════════════════════════════════════════════════════════════
-- Phase 4 / M10 — the vendor marketplace (BRD FR170, plan §3.6)
--
-- The other half of buying a house. Somebody who has just had an offer accepted needs a conveyancer, a
-- surveyor, a mover, a bank valuer's fee paid, curtains and a security firm — and the platform already knows
-- exactly when they need them. A vendor is a business offering those services, and a catalogue item is one
-- thing they offer.
--
-- <h2>A vendor is an organisation, like an agent</h2>
--
-- §3.6 said vendors are "organisation-scoped exactly like sellers, so they reuse TenantScope unchanged", and
-- that is what happens: an approved vendor gets a `tenants` row of kind VENDOR, and everything downstream —
-- visibility, module enablement, staff — works without a new mechanism. The kind column added for agents is
-- what keeps them out of the seller administration screen.
--
-- <h2>The catalogue goes through Maker/Checker</h2>
--
-- Plan §3.2 lists M10 as a consumer of the approval queue, and it is the right call for a reason worth
-- writing down: a catalogue item is a public price from a third party, shown to somebody in the middle of
-- the largest transaction of their life. A seller's listing is checked before it is published; a vendor's
-- quotation should be too.
--
-- <h2>What is NOT here</h2>
--
-- `product_rating` from the §4 table. Ratings arrive in M7 as one mechanism covering property, service and
-- product, rather than a product-only table now and a general one a fortnight later that has to absorb it.
-- ═════════════════════════════════════════════════════════════════════════════════════════════════

ALTER TABLE user_types DROP CONSTRAINT ck_user_types_actor_class;
ALTER TABLE user_types ADD CONSTRAINT ck_user_types_actor_class
    CHECK (actor_class IN ('PLATFORM', 'SELLER', 'LENDER', 'BUYER', 'VALUER', 'AGENT', 'VENDOR'));

ALTER TABLE user_profiles DROP CONSTRAINT ck_user_profiles_type;
ALTER TABLE user_profiles ADD CONSTRAINT ck_user_profiles_type
    CHECK (profile_type IN ('PLATFORM', 'SELLER', 'LENDER', 'BUYER', 'VALUER', 'AGENT', 'VENDOR'));

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- The taxonomy.
--
-- A table rather than a CHECK, unlike seller types: this list is expected to grow as the platform learns
-- what buyers actually ask for, and growing it should not be a deploy. Seeded with what a house purchase
-- obviously needs, and editable by the platform from there.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE vendor_categories (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    code         VARCHAR(32)  NOT NULL UNIQUE,
    name         VARCHAR(120) NOT NULL,
    description  TEXT,
    -- What a buyer sees on the directory tile. An emoji, not an image: a taxonomy of eight to thirty rows
    -- does not justify an upload pipeline, and a missing icon should degrade to nothing rather than a
    -- broken image.
    icon         VARCHAR(8),
    sort_order   INTEGER      NOT NULL DEFAULT 100,

    status       INTEGER      NOT NULL DEFAULT 1,
    status_flag  VARCHAR(32)  NOT NULL DEFAULT 'Active',

    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by   VARCHAR(64),
    updated_by   VARCHAR(64)
);

INSERT INTO vendor_categories (code, name, description, icon, sort_order, created_by) VALUES
    ('CONVEYANCING', 'Conveyancing',       'Advocates who handle the transfer and the searches.',   '⚖️', 10, 'system'),
    ('SURVEY',       'Survey and inspection','Structural surveys, land surveys and snag lists.',    '📐', 20, 'system'),
    ('MOVING',       'Moving and storage',  'Removals, packing and storage between houses.',        '📦', 30, 'system'),
    ('INTERIORS',    'Interiors and fit-out','Design, joinery, curtains and kitchens.',             '🛋️', 40, 'system'),
    ('BUILDING',     'Building and repair', 'Contractors, plumbers, electricians and roofers.',     '🧱', 50, 'system'),
    ('SECURITY',     'Security',            'Alarms, electric fencing and guarding.',               '🔒', 60, 'system'),
    ('INSURANCE',    'Insurance',           'Home, contents and mortgage protection cover.',        '🛡️', 70, 'system'),
    ('CLEANING',     'Cleaning and garden', 'Deep cleans, fumigation and landscaping.',             '🧹', 80, 'system');

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- The vendor.
--
-- Same shape as an agent, and deliberately so: apply, be approved, get an organisation. The differences are
-- what is checked (a business registration rather than an estate agent's licence) and what they publish.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE vendor_profiles (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    reference          VARCHAR(16)  NOT NULL UNIQUE,
    user_id            BIGINT       NOT NULL REFERENCES users (id),
    profile_id         BIGINT       NOT NULL REFERENCES user_profiles (id),
    -- Set at approval, exactly like an agent's. No organisation means nowhere to publish a catalogue.
    tenant_id          BIGINT       REFERENCES tenants (id),

    business_name      VARCHAR(255) NOT NULL,
    contact_name       VARCHAR(160),
    email              VARCHAR(128),
    phone              VARCHAR(32),

    category_id        BIGINT       NOT NULL REFERENCES vendor_categories (id),
    category_name      VARCHAR(120),

    registration_number VARCHAR(64),
    kra_pin            VARCHAR(32),
    counties           TEXT,
    about              TEXT,
    website            VARCHAR(255),
    logo_key           VARCHAR(512),

    state              VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    decided_at         TIMESTAMPTZ,
    decided_by_user_id BIGINT,
    decision_note      TEXT,

    status             INTEGER      NOT NULL DEFAULT 1,
    status_flag        VARCHAR(32)  NOT NULL DEFAULT 'Active',

    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by         VARCHAR(64),
    updated_by         VARCHAR(64),

    CONSTRAINT uk_vendor_profile UNIQUE (profile_id),
    CONSTRAINT ck_vendor_state CHECK (state IN ('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED')),
    CONSTRAINT ck_vendor_approved CHECK (
        state <> 'APPROVED' OR (tenant_id IS NOT NULL AND decided_at IS NOT NULL)),
    CONSTRAINT ck_vendor_decided CHECK (state <> 'REJECTED' OR decided_at IS NOT NULL)
);

CREATE INDEX idx_vendor_state ON vendor_profiles (state, created_at DESC);
CREATE INDEX idx_vendor_category ON vendor_profiles (category_id);
CREATE INDEX idx_vendor_tenant ON vendor_profiles (tenant_id) WHERE tenant_id IS NOT NULL;

ALTER TABLE vendor_profiles ADD COLUMN search_text text
    GENERATED ALWAYS AS (
        lower(coalesce(reference, '') || ' ' || coalesce(business_name, '') || ' ' ||
              coalesce(contact_name, '') || ' ' || coalesce(email, '') || ' ' ||
              coalesce(phone, '') || ' ' || coalesce(category_name, '') || ' ' ||
              coalesce(counties, '') || ' ' || coalesce(about, '') || ' ' || coalesce(state, ''))
    ) STORED;
CREATE INDEX idx_vendor_search_trgm ON vendor_profiles USING gin (search_text gin_trgm_ops);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- One thing a vendor offers.
--
-- Prices are honest about their own precision. A conveyancer quotes a percentage of the purchase price, a
-- mover quotes per trip, a surveyor quotes a flat fee — so `price` is optional, `price_from` says "from",
-- and `price_note` carries the sentence a number cannot ("1.5% of the purchase price, minimum KES 35,000").
-- Forcing all of that into one number is how a marketplace ends up displaying prices nobody will honour.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE catalogue_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    reference       VARCHAR(16)  NOT NULL UNIQUE,
    vendor_id       BIGINT       NOT NULL REFERENCES vendor_profiles (id),
    tenant_id       BIGINT,
    vendor_name     VARCHAR(255),

    category_id     BIGINT       NOT NULL REFERENCES vendor_categories (id),
    category_name   VARCHAR(120),

    title           VARCHAR(255) NOT NULL,
    description     TEXT,

    price           NUMERIC(15, 2),
    price_from      BOOLEAN      NOT NULL DEFAULT false,
    currency        VARCHAR(3)   NOT NULL DEFAULT 'KES',
    unit            VARCHAR(32),
    price_note      TEXT,

    lead_time_days  SMALLINT,
    counties        TEXT,
    image_key       VARCHAR(512),

    state           VARCHAR(16)  NOT NULL DEFAULT 'DRAFT',
    published_at    TIMESTAMPTZ,
    withdrawn_at    TIMESTAMPTZ,
    withdrawn_reason TEXT,

    status          INTEGER      NOT NULL DEFAULT 1,
    status_flag     VARCHAR(32)  NOT NULL DEFAULT 'Active',

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      VARCHAR(64),
    updated_by      VARCHAR(64),

    CONSTRAINT ck_item_state CHECK (state IN ('DRAFT', 'PENDING', 'LIVE', 'WITHDRAWN')),
    CONSTRAINT ck_item_published CHECK (state <> 'LIVE' OR published_at IS NOT NULL),
    -- A published item says something about price. Not necessarily a number — but not silence either.
    CONSTRAINT ck_item_priced CHECK (
        state <> 'LIVE' OR price IS NOT NULL OR (price_note IS NOT NULL AND price_note <> ''))
);

CREATE INDEX idx_item_vendor ON catalogue_items (vendor_id, created_at DESC);
CREATE INDEX idx_item_category ON catalogue_items (category_id);
-- The public catalogue: live, newest first. Its own partial index, like the auction one.
CREATE INDEX idx_item_public ON catalogue_items (published_at DESC)
    WHERE state = 'LIVE' AND status <> 5;

ALTER TABLE catalogue_items ADD COLUMN search_text text
    GENERATED ALWAYS AS (
        lower(coalesce(reference, '') || ' ' || coalesce(title, '') || ' ' ||
              coalesce(description, '') || ' ' || coalesce(vendor_name, '') || ' ' ||
              coalesce(category_name, '') || ' ' || coalesce(counties, '') || ' ' ||
              coalesce(price_note, ''))
    ) STORED;
CREATE INDEX idx_item_search_trgm ON catalogue_items USING gin (search_text gin_trgm_ops);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- The modules an approved vendor works in. Appended, token-precise, and only where the row is untouched —
-- see the M9 migration for why `allowed_user_types` is not simply re-seeded.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
UPDATE app_modules
SET allowed_user_types = allowed_user_types || ',VENDOR',
    updated_at         = now(),
    updated_by         = 'system'
WHERE code IN ('DASHBOARD', 'APPROVALS')
  AND ',' || allowed_user_types || ',' NOT LIKE '%,VENDOR,%';
