-- Who brought the buyer is known from the first enquiry, not remembered at the booking; and an agent says
-- where they are paid.
--
-- The introducer travels: named on an enquiry, it is carried onto the buyer's offer on the same home, and
-- from the offer onto the booking it becomes. How early it may be named is a setting
-- (commission.agent.attribution.from); the columns are the same either way.

ALTER TABLE enquiry_tickets
    ADD COLUMN introduced_by_agent_id BIGINT REFERENCES agent_profiles (id);
CREATE INDEX idx_enquiry_introducer ON enquiry_tickets (introduced_by_agent_id)
    WHERE introduced_by_agent_id IS NOT NULL;

ALTER TABLE purchase_requests
    ADD COLUMN introduced_by_agent_id BIGINT REFERENCES agent_profiles (id);
CREATE INDEX idx_offer_introducer ON purchase_requests (introduced_by_agent_id)
    WHERE introduced_by_agent_id IS NOT NULL;

-- ── where an agent is paid ─────────────────────────────────────────────────────────────────────
--
-- On the agent, not in the beneficiary register: an agent is paid as themselves, whichever development's
-- buyer they brought. Several accounts, one default. Confirmed with the bank the way a beneficiary is; an
-- account the bank has not confirmed cannot be paid to. A one-person organisation has no second person to
-- approve where its money goes, so the bank's confirmation of the holder is the check, and the bank sees
-- every account on the register.
CREATE TABLE agent_payout_accounts (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_profile_id   BIGINT       NOT NULL REFERENCES agent_profiles (id),
    bank_code          VARCHAR(4)   NOT NULL,
    account_no         VARCHAR(32)  NOT NULL,
    -- As the agent typed it; what the bank says is beside it.
    holder_name        VARCHAR(160),
    -- VERIFIED | UNVERIFIED
    verification       VARCHAR(12)  NOT NULL DEFAULT 'UNVERIFIED',
    confirmed_name     VARCHAR(160),
    confirmed_at       TIMESTAMPTZ,
    verification_note  TEXT,
    is_default         BOOLEAN      NOT NULL DEFAULT false,

    status             INTEGER      NOT NULL DEFAULT 1,
    status_flag        VARCHAR(32)  NOT NULL DEFAULT 'Active',
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by         VARCHAR(64),
    updated_by         VARCHAR(64),

    CONSTRAINT ck_agent_account_verification CHECK (verification IN ('VERIFIED', 'UNVERIFIED')),
    CONSTRAINT ck_agent_account_confirmed CHECK (verification <> 'VERIFIED' OR confirmed_name IS NOT NULL)
);
CREATE UNIQUE INDEX uk_agent_account ON agent_payout_accounts (agent_profile_id, bank_code, account_no)
    WHERE status <> 5;
-- One default per agent.
CREATE UNIQUE INDEX uk_agent_account_default ON agent_payout_accounts (agent_profile_id)
    WHERE is_default AND status <> 5;
