-- pg_trgm's operator class, wherever the extension lives.
-- An extension exists once per database, in one schema, and on a shared server that schema is whichever
-- application installed it first — public on one machine, another application's schema on the next. Rather
-- than guess, look it up and put it on this transaction's search path; Flyway runs the whole script in one
-- transaction, so every gin_trgm_ops below resolves. Installs it into our own schema if nobody has yet.
DO $$
DECLARE ext_schema text;
BEGIN
    SELECT n.nspname INTO ext_schema
      FROM pg_extension e JOIN pg_namespace n ON n.oid = e.extnamespace
     WHERE e.extname = 'pg_trgm';
    IF ext_schema IS NULL THEN
        EXECUTE 'CREATE EXTENSION pg_trgm';
        ext_schema := current_schema();
    END IF;
    EXECUTE format('SET LOCAL search_path TO %I, %I', current_schema(), ext_schema);
END $$;

-- ═════════════════════════════════════════════════════════════════════════════════════════════════
-- Phase 0a — one login, many profiles (BRD FR073)
--
-- Before this migration a row in `users` *was* an actor: actor_class, the user type, the group and the
-- organisation all sat on the person. One natural person could therefore be a buyer or a seller's owner,
-- never both, because `email` is UNIQUE and there was nowhere to put the second answer. FR073 requires
-- exactly that: "the same person can be a Buyer and an approved Seller under separate profiles, same email
-- allowed".
--
-- So the actor-defining fields move off the person and onto a profile. `users` keeps what identifies and
-- authenticates somebody — name, email, phone, password, second factor, lockout, session cutoff — and one
-- row per profile carries what they *are* in a given organisation.
--
-- Why one login rather than two accounts sharing an address: an account is a credential, and duplicating
-- the credential duplicates every lockout, every password history and every 2FA enrolment, then leaves two
-- rows to reconcile when somebody changes their phone number. The BRD says the email may be the same; it
-- does not say there must be two of them.
--
-- The four profile types here are the four actor classes that exist today. AGENT, VALUER and VENDOR arrive
-- with their own modules (plan §3.4–3.6) and extend the CHECK below; they are deliberately not seeded now,
-- because a profile type with no module, no permissions and no screens is a value nothing can hold.
-- ═════════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE user_profiles (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id             BIGINT       NOT NULL REFERENCES users (id),

    -- The actor class, now a property of the profile rather than of the person.
    profile_type        VARCHAR(16)  NOT NULL,

    user_type_id        BIGINT       NOT NULL,
    user_type_code      VARCHAR(32)  NOT NULL,
    user_type_name      VARCHAR(64),

    user_group_id       BIGINT,
    user_group_name     VARCHAR(128),

    -- At most one organisation, exactly as the old CHECK on users said. A seller profile carries a tenant,
    -- a lender profile an institution, platform and buyer profiles neither.
    tenant_id           BIGINT,
    tenant_name         VARCHAR(255),
    institution_id      BIGINT,
    institution_name    VARCHAR(255),

    -- KYC lands here rather than on the organisation because it is the *profile* that gets gated: the same
    -- person may be an approved seller in one organisation and a pending one in another. Nothing writes
    -- anything but NOT_REQUIRED until M8 (plan §3.3); the column exists now so the gate in
    -- EffectivePermissionResolver has something to read and does not need a second migration to arrive.
    kyc_status          VARCHAR(16)  NOT NULL DEFAULT 'NOT_REQUIRED',
    kyc_decided_at      TIMESTAMPTZ,

    -- Which profile a fresh login lands on. Exactly one per person, enforced below.
    is_default          BOOLEAN      NOT NULL DEFAULT false,

    status              INTEGER      NOT NULL DEFAULT 1,
    status_flag         VARCHAR(32)  NOT NULL DEFAULT 'Active',
    deactivation_reason TEXT,

    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          VARCHAR(64),
    updated_by          VARCHAR(64),

    CONSTRAINT ck_user_profiles_type
        CHECK (profile_type IN ('PLATFORM', 'SELLER', 'LENDER', 'BUYER')),
    CONSTRAINT ck_user_profiles_one_org
        CHECK (tenant_id IS NULL OR institution_id IS NULL),
    CONSTRAINT ck_user_profiles_kyc
        CHECK (kyc_status IN ('NOT_REQUIRED', 'PENDING', 'SUBMITTED', 'APPROVED', 'REJECTED'))
);

-- One profile of a given kind per organisation. coalesce rather than a plain unique tuple, because NULL is
-- never equal to NULL in a unique index — without it, a person could accumulate any number of identical
-- platform or buyer profiles.
CREATE UNIQUE INDEX uk_user_profile_scope ON user_profiles
    (user_id, profile_type, coalesce(tenant_id, 0), coalesce(institution_id, 0))
    WHERE status <> 5;

-- Exactly one default. A partial unique index rather than a trigger: the database refuses the second one
-- outright, so no service can leave a person with two landing profiles or none.
CREATE UNIQUE INDEX uk_user_profile_default ON user_profiles (user_id)
    WHERE is_default AND status <> 5;

CREATE INDEX idx_user_profiles_user ON user_profiles (user_id);
CREATE INDEX idx_user_profiles_tenant ON user_profiles (tenant_id);
CREATE INDEX idx_user_profiles_institution ON user_profiles (institution_id);
CREATE INDEX idx_user_profiles_type ON user_profiles (profile_type);
CREATE INDEX idx_user_profiles_user_type ON user_profiles (user_type_code);
CREATE INDEX idx_user_profiles_group ON user_profiles (user_group_id);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- Backfill: one profile per existing user, carrying exactly what that user already was.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
INSERT INTO user_profiles (user_id, profile_type, user_type_id, user_type_code, user_type_name,
                           user_group_id, user_group_name, tenant_id, tenant_name,
                           institution_id, institution_name, is_default,
                           status, status_flag, created_at, created_by)
SELECT u.id, u.actor_class, u.user_type_id, u.user_type_code, u.user_type_name,
       u.user_group_id, u.user_group_name, u.tenant_id, u.tenant_name,
       u.institution_id, u.institution_name, true,
       u.status, u.status_flag, u.created_at, coalesce(u.created_by, 'migration')
FROM users u;

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- users loses the actor-defining columns.
--
-- search_text goes first and comes back narrower: it is a generated column that reads four of the columns
-- being dropped, so Postgres would refuse the drop while it exists. What it becomes is the person — name,
-- username, email, phone — with the labels moving to the profile's own index, which is where somebody
-- searching for "mortgage officer equity" is now searching.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
DROP INDEX idx_users_search_trgm;
ALTER TABLE users DROP COLUMN search_text;

ALTER TABLE users
    DROP COLUMN user_type_id,
    DROP COLUMN user_type_code,
    DROP COLUMN user_type_name,
    DROP COLUMN user_group_id,
    DROP COLUMN user_group_name,
    DROP COLUMN actor_class,
    DROP COLUMN tenant_id,
    DROP COLUMN tenant_name,
    DROP COLUMN institution_id,
    DROP COLUMN institution_name;

ALTER TABLE users ADD COLUMN search_text text
    GENERATED ALWAYS AS (
        lower(coalesce(first_name, '') || ' ' || coalesce(last_name, '') || ' ' ||
              coalesce(username, '') || ' ' || coalesce(email, '') || ' ' ||
              coalesce(phone, ''))
    ) STORED;
CREATE INDEX idx_users_search_trgm ON users USING gin (search_text gin_trgm_ops);

-- The labels, searchable on the profile that owns them.
ALTER TABLE user_profiles ADD COLUMN search_text text
    GENERATED ALWAYS AS (
        lower(coalesce(user_type_name, '') || ' ' || coalesce(user_group_name, '') || ' ' ||
              coalesce(tenant_name, '') || ' ' || coalesce(institution_name, '') || ' ' ||
              coalesce(profile_type, ''))
    ) STORED;
CREATE INDEX idx_user_profiles_search_trgm ON user_profiles USING gin (search_text gin_trgm_ops);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- A session belongs to a profile, not just to a person.
--
-- Rotation has to hand back the profile the session was issued for. Without this column a refresh would
-- silently drop somebody back to their default profile every twenty minutes — which for a person holding
-- both a buyer and a seller profile is a session that changes what it can see on its own.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
ALTER TABLE refresh_tokens ADD COLUMN profile_id BIGINT;

UPDATE refresh_tokens t
SET profile_id = p.id
FROM user_profiles p
WHERE p.user_id = t.user_id AND p.is_default;

-- Nullable on purpose: a token issued before this migration and still inside its window has no profile,
-- and refusing it would sign out everybody currently working. The refresh path falls back to the default.

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- Password recovery by phone number (BRD FR007) needs a phone somebody can be *found* by.
--
-- The stored number is whatever was typed: "+254 712 345 678", "0712345678", "254712345678". Matching a
-- recovery request against that with LIKE would be both wrong and unindexable, so the database keeps the
-- last nine digits — the national significant number — as a generated column, and the lookup is an equality
-- on an indexed value.
--
-- Nine rather than the whole thing because the country code and the trunk zero are exactly the parts people
-- type differently, and they are the parts that carry no information for a national number.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
ALTER TABLE users ADD COLUMN phone_local text
    GENERATED ALWAYS AS (right(regexp_replace(coalesce(phone, ''), '\D', '', 'g'), 9)) STORED;
CREATE INDEX idx_users_phone_local ON users (phone_local) WHERE phone_local <> '';

-- Which profile acted. The audit trail already records the actor's user type and class; with profiles those
-- two are properties of the profile, so the profile is the thing worth naming.
ALTER TABLE audit_logs ADD COLUMN actor_profile_id BIGINT;
