-- ═════════════════════════════════════════════════════════════════════════════════════════════════
-- Phase 6 / M11 — the assistant (plan §4)
--
-- <h2>What this is, and what it is not</h2>
--
-- Plan §4 calls it "thin orchestration over M2/M3/M4", and that is exactly what it is: something that reads
-- a question, works out which of the platform's own capabilities answers it, and answers from real data.
-- Searching listings, running the affordability arithmetic, explaining what a guide price is, and — when it
-- cannot help — handing the conversation to a person with the transcript attached.
--
-- There is no language model behind it. `AssistantProvider` is an interface with one rules-based
-- implementation, the same shape M3 used for the affordability provider: the seam is real, so adding a model
-- later is a second class rather than a rewrite. What matters more is that the assistant says what it is.
-- An assistant that implies it is a person, to somebody about to spend everything they have on a house, is
-- not a feature.
--
-- <h2>The transcript is the point of the hand-off</h2>
--
-- A buyer who gives up on a machine and asks for a person should not have to say it all again. The hand-off
-- raises an M4 enquiry with the conversation attached, which is why the messages are rows rather than a blob
-- on the conversation: the enquiry quotes them.
-- ═════════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE assistant_conversations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    reference       VARCHAR(16)  NOT NULL UNIQUE,
    user_id         BIGINT       NOT NULL REFERENCES users (id),

    -- Taken from the first thing they said, so a list of conversations reads as a list of questions.
    title           VARCHAR(180),

    -- OPEN | HANDED_OFF | CLOSED
    state           VARCHAR(16)  NOT NULL DEFAULT 'OPEN',
    -- What the hand-off produced, so the conversation can point at the enquiry it became.
    enquiry_ref     VARCHAR(16),
    handed_off_at   TIMESTAMPTZ,

    message_count   INTEGER      NOT NULL DEFAULT 0,
    last_message_at TIMESTAMPTZ,

    status          INTEGER      NOT NULL DEFAULT 1,
    status_flag     VARCHAR(32)  NOT NULL DEFAULT 'Active',

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      VARCHAR(64),
    updated_by      VARCHAR(64),

    CONSTRAINT ck_conversation_state CHECK (state IN ('OPEN', 'HANDED_OFF', 'CLOSED')),
    CONSTRAINT ck_conversation_handoff CHECK (state <> 'HANDED_OFF' OR handed_off_at IS NOT NULL)
);

CREATE INDEX idx_conversation_user ON assistant_conversations (user_id, last_message_at DESC);

CREATE TABLE assistant_messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    conversation_id BIGINT       NOT NULL REFERENCES assistant_conversations (id),

    -- USER | ASSISTANT. Two sides, and the second one is a machine — which is why every screen that shows
    -- these says so rather than styling them as a person.
    side            VARCHAR(16)  NOT NULL,
    body            TEXT         NOT NULL,

    -- What the assistant decided the question was about, and what it found. Kept because "why did it answer
    -- that" is the question anybody debugging this will ask, and a transcript without the reasoning is a
    -- transcript nobody can act on.
    intent          VARCHAR(32),
    payload         JSONB,

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_message_side CHECK (side IN ('USER', 'ASSISTANT'))
);

CREATE INDEX idx_message_conversation ON assistant_messages (conversation_id, created_at);
