-- A campaign is written, checked, and sent inside the window.
--
-- The promotional consent the platform has collected since the start is finally used for something. A
-- campaign names its audience and the words; a checker approves it through the approval engine; a sweep
-- sends it in batches inside the sending window and under the daily cap, one recipient at a time through
-- the same door as every other message, with a one-click way out that works without signing in.

CREATE TABLE campaigns (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference         VARCHAR(16)  NOT NULL UNIQUE,
    -- Null for the platform's own; an organisation's campaign goes to its own buyers.
    tenant_id         BIGINT,
    institution_id    BIGINT,
    title             VARCHAR(160) NOT NULL,
    -- BUYERS today; the shape allows more.
    audience          VARCHAR(16)  NOT NULL DEFAULT 'BUYERS',
    county            VARCHAR(64),
    registered_since  DATE,
    -- CSV of EMAIL, SMS, IN_APP.
    channels          VARCHAR(32)  NOT NULL DEFAULT 'EMAIL,IN_APP',
    subject           VARCHAR(255) NOT NULL,
    body              TEXT         NOT NULL,
    cta_label         VARCHAR(80),
    cta_path          VARCHAR(255),
    -- DRAFT | SUBMITTED | APPROVED | SENDING | SENT | CANCELLED
    state             VARCHAR(12)  NOT NULL DEFAULT 'DRAFT',
    scheduled_for     TIMESTAMPTZ,
    audience_count    INTEGER,
    sent_count        INTEGER      NOT NULL DEFAULT 0,
    failed_count      INTEGER      NOT NULL DEFAULT 0,
    skipped_count     INTEGER      NOT NULL DEFAULT 0,
    started_at        TIMESTAMPTZ,
    finished_at       TIMESTAMPTZ,
    approved_by       VARCHAR(64),
    approved_at       TIMESTAMPTZ,
    cancel_reason     TEXT,
    status            INTEGER      NOT NULL DEFAULT 1,
    status_flag       VARCHAR(32)  NOT NULL DEFAULT 'Active',
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by        VARCHAR(64),
    updated_by        VARCHAR(64),
    CONSTRAINT ck_campaign_state CHECK (state IN ('DRAFT', 'SUBMITTED', 'APPROVED', 'SENDING', 'SENT', 'CANCELLED'))
);
CREATE INDEX idx_campaigns_owner ON campaigns (tenant_id, institution_id, created_at DESC);
CREATE INDEX idx_campaigns_due ON campaigns (scheduled_for) WHERE state IN ('APPROVED', 'SENDING');

-- One row per recipient, written when the audience is fixed at approval; the sweep works through them.
CREATE TABLE campaign_sends (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id  BIGINT      NOT NULL REFERENCES campaigns (id),
    user_id      BIGINT      NOT NULL,
    -- PENDING | SENT | FAILED | SKIPPED
    state        VARCHAR(12) NOT NULL DEFAULT 'PENDING',
    channels     VARCHAR(64),
    sent_at      TIMESTAMPTZ,
    error        TEXT
);
CREATE UNIQUE INDEX uk_campaign_send ON campaign_sends (campaign_id, user_id);
CREATE INDEX idx_campaign_sends_pending ON campaign_sends (campaign_id) WHERE state = 'PENDING';

INSERT INTO notification_events (code, audience, purpose, subject, line, description, placeholders, composed, sort_order) VALUES
('CAMPAIGN', 'BUYER', 'PROMOTIONAL',
 'Offers and news',
 'Composed per campaign: the subject and body the author wrote, with the way to stop receiving them.',
 'A campaign, under promotional consent. The catalogue decides on/off and the channels a campaign may use.', '', true, 90);
