-- ═════════════════════════════════════════════════════════════════════════════════════════════════
-- Phase 2 / M8, first slice — KYC (plan §3.3) and the document vault (§3.9)
--
-- Two things that had to arrive together: KYC is the first thing on this platform that handles documents
-- nobody but Compliance should see, and building it on the media storage that serves listing photographs
-- would be the mistake §3.9 exists to prevent.
--
-- <h2>Requirements are data, not code</h2>
--
-- `kyc_requirement_configs` is a versioned list of what each kind of seller must produce. Compliance changes
-- the CR12 requirement for a SACCO without a deploy, and — this is the point of the version column —
-- submissions already judged keep the version they were judged against. A requirement list that changed
-- retroactively would make every past approval unexplainable.
--
-- <h2>The vault is not the media store</h2>
--
-- `vault_documents` rows have no public URL form at all. Access is a fetch through an endpoint that checks
-- `vault_document_acl`, and every such fetch writes an audit row. The storage key lives in a separate prefix
-- from listing photographs so that a bucket policy can differ between the two.
-- ═════════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE vault_documents (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    reference          VARCHAR(16)  NOT NULL UNIQUE,

    -- Who the document is *about*. One of the two is set; both null would be a document belonging to nobody.
    tenant_id          BIGINT,
    user_id            BIGINT REFERENCES users (id),

    -- What it is, from the requirement catalogue: CERT_INCORPORATION, CR12, KRA_PIN, ID_FRONT…
    document_code      VARCHAR(48)  NOT NULL,
    document_name      VARCHAR(160),

    storage_key        VARCHAR(512) NOT NULL,
    content_type       VARCHAR(64),
    size_bytes         BIGINT,
    original_name      VARCHAR(255),
    -- Hex SHA-256 of the bytes as stored. Two uses: telling a re-upload of the same file from a new one, and
    -- proving on a later dispute that the bytes served are the bytes received.
    checksum_sha256    VARCHAR(64),
    -- What the storage layer declared when it wrote the object: SSE-S3, SSE-KMS, or NONE for local disk in
    -- development. Recorded on the row because "was this encrypted at rest" is an audit question about a
    -- particular document, not about the deployment it happens to be read on.
    encryption         VARCHAR(24)  NOT NULL DEFAULT 'NONE',

    -- Documents expire. A certificate of good conduct from 2019 is not evidence of anything in 2026.
    issued_on          DATE,
    expires_on         DATE,

    uploaded_by_user_id BIGINT,
    uploaded_by_name   VARCHAR(160),

    status             INTEGER      NOT NULL DEFAULT 1,
    status_flag        VARCHAR(32)  NOT NULL DEFAULT 'Active',

    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by         VARCHAR(64),
    updated_by         VARCHAR(64),

    CONSTRAINT ck_vault_subject CHECK (tenant_id IS NOT NULL OR user_id IS NOT NULL),
    CONSTRAINT ck_vault_dates CHECK (expires_on IS NULL OR issued_on IS NULL OR expires_on >= issued_on)
);

CREATE INDEX idx_vault_tenant ON vault_documents (tenant_id);
CREATE INDEX idx_vault_user ON vault_documents (user_id);
CREATE INDEX idx_vault_code ON vault_documents (document_code);
-- Compliance's own question: what is about to lapse.
CREATE INDEX idx_vault_expiring ON vault_documents (expires_on)
    WHERE expires_on IS NOT NULL AND status <> 5;

COMMENT ON TABLE vault_documents IS
    'Sensitive documents. No public URL form exists: every read goes through the vault endpoint, which '
        'checks vault_document_acl and writes an audit row. Do not add a url column.';

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- Who may read one.
--
-- A row per grant rather than a rule in code, because the grants are not uniform: the organisation the
-- document is about can always see its own, Compliance sees everything it is judging, and a specific
-- reviewer may be given sight of one document without being given the module.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE vault_document_acl (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id  BIGINT      NOT NULL REFERENCES vault_documents (id),

    -- Exactly one of the three is set: a person, an organisation, or a permission code.
    user_id      BIGINT,
    tenant_id    BIGINT,
    permission   VARCHAR(64),

    -- READ is the only verb today. WRITE exists so replacing a document is a grant somebody holds rather
    -- than a second table when it arrives.
    grant_type   VARCHAR(16) NOT NULL DEFAULT 'READ',
    granted_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    granted_by   VARCHAR(64),
    -- A grant that lapses. Null is "until revoked".
    expires_at   TIMESTAMPTZ,
    revoked_at   TIMESTAMPTZ,

    CONSTRAINT ck_acl_subject CHECK (
        (user_id IS NOT NULL)::int + (tenant_id IS NOT NULL)::int + (permission IS NOT NULL)::int = 1),
    CONSTRAINT ck_acl_grant CHECK (grant_type IN ('READ', 'WRITE'))
);

CREATE INDEX idx_acl_document ON vault_document_acl (document_id);
CREATE INDEX idx_acl_user ON vault_document_acl (user_id) WHERE user_id IS NOT NULL;
CREATE INDEX idx_acl_tenant ON vault_document_acl (tenant_id) WHERE tenant_id IS NOT NULL;

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- What each kind of seller must produce.
--
-- Versioned as a whole rather than per row: a submission records the version it was judged against, and
-- "which list applied in March" has to be answerable as a set rather than as a reconstruction from row
-- timestamps.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE kyc_requirement_configs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- The seller type this applies to. The catalogue lives in AppConstant.SELLER_TYPES and is the same
    -- list the onboarding form offers; a requirement list for a type nobody can choose is dead data.
    entity_type    VARCHAR(32)  NOT NULL,
    version        INTEGER      NOT NULL DEFAULT 1,

    document_code  VARCHAR(48)  NOT NULL,
    document_name  VARCHAR(160) NOT NULL,
    description    TEXT,
    required       BOOLEAN      NOT NULL DEFAULT true,
    -- How long the document stays valid once issued, in months. Null means it does not lapse.
    validity_months SMALLINT,
    sort_order     INTEGER      NOT NULL DEFAULT 0,

    status         INTEGER      NOT NULL DEFAULT 1,
    status_flag    VARCHAR(32)  NOT NULL DEFAULT 'Active',

    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by     VARCHAR(64),
    updated_by     VARCHAR(64),

    CONSTRAINT uk_kyc_requirement UNIQUE (entity_type, version, document_code)
);

CREATE INDEX idx_kyc_req_type ON kyc_requirement_configs (entity_type, version, sort_order);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- One organisation's pack, and Compliance's answer to it.
--
-- Tied to a profile rather than to a tenant, because `user_profiles.kyc_status` is what the permission
-- resolver reads — and it is the profile that holds the actor. A tenant with three staff has one submission
-- against the owner's profile and three profiles whose status follows it.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE kyc_submissions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    reference           VARCHAR(16)  NOT NULL UNIQUE,

    profile_id          BIGINT       NOT NULL REFERENCES user_profiles (id),
    user_id             BIGINT       NOT NULL REFERENCES users (id),
    tenant_id           BIGINT,
    tenant_name         VARCHAR(255),

    entity_type         VARCHAR(32)  NOT NULL,
    -- The version of the requirement list this pack was judged against. Frozen at submission.
    requirement_version INTEGER      NOT NULL DEFAULT 1,

    state               VARCHAR(16)  NOT NULL DEFAULT 'DRAFT',
    submitted_at        TIMESTAMPTZ,
    decided_at          TIMESTAMPTZ,
    decided_by_user_id  BIGINT,
    decision_note       TEXT,

    status              INTEGER      NOT NULL DEFAULT 1,
    status_flag         VARCHAR(32)  NOT NULL DEFAULT 'Active',

    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          VARCHAR(64),
    updated_by          VARCHAR(64),

    CONSTRAINT ck_kyc_state
        CHECK (state IN ('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'MORE_INFO')),
    CONSTRAINT ck_kyc_submitted CHECK (state = 'DRAFT' OR submitted_at IS NOT NULL),
    CONSTRAINT ck_kyc_decided
        CHECK (state IN ('DRAFT', 'SUBMITTED') OR decided_at IS NOT NULL)
);

CREATE INDEX idx_kyc_sub_profile ON kyc_submissions (profile_id);
CREATE INDEX idx_kyc_sub_tenant ON kyc_submissions (tenant_id);
CREATE INDEX idx_kyc_sub_state ON kyc_submissions (state, submitted_at DESC);
-- One live pack per profile. A second while the first is outstanding would give Compliance two answers to
-- give and no way to say which they were giving it to.
CREATE UNIQUE INDEX uk_kyc_live ON kyc_submissions (profile_id)
    WHERE state IN ('DRAFT', 'SUBMITTED', 'MORE_INFO') AND status <> 5;

ALTER TABLE kyc_submissions ADD COLUMN search_text text
    GENERATED ALWAYS AS (
        lower(coalesce(reference, '') || ' ' || coalesce(tenant_name, '') || ' ' ||
              coalesce(entity_type, '') || ' ' || coalesce(state, ''))
    ) STORED;
CREATE INDEX idx_kyc_sub_search_trgm ON kyc_submissions USING gin (search_text gin_trgm_ops);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- The documents in a pack, and what Compliance made of each one.
--
-- A join row rather than a column on the vault document, because the same document can be produced for two
-- submissions — a renewal reuses the certificate of incorporation — and each submission's verdict on it is
-- its own.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE kyc_documents (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    submission_id  BIGINT      NOT NULL REFERENCES kyc_submissions (id),
    document_id    BIGINT      NOT NULL REFERENCES vault_documents (id),
    document_code  VARCHAR(48) NOT NULL,

    verdict        VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    verdict_note   TEXT,
    verified_at    TIMESTAMPTZ,
    verified_by_user_id BIGINT,

    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ck_kyc_doc_verdict CHECK (verdict IN ('PENDING', 'ACCEPTED', 'REJECTED')),
    CONSTRAINT uk_kyc_doc UNIQUE (submission_id, document_code)
);

CREATE INDEX idx_kyc_doc_submission ON kyc_documents (submission_id);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- The seeded requirement lists, version 1.
--
-- Compliance will change these; that is the point of them being rows. What is seeded is a defensible
-- starting position for the Kenyan market, not a legal opinion.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
INSERT INTO kyc_requirement_configs
    (entity_type, version, document_code, document_name, description, required, validity_months, sort_order,
     created_by, updated_by)
VALUES
 ('INDIVIDUAL', 1, 'ID_FRONT', 'National ID (front)', 'A clear photograph or scan of the front.', true, NULL, 10, 'flyway', 'flyway'),
 ('INDIVIDUAL', 1, 'ID_BACK', 'National ID (back)', 'The reverse of the same document.', true, NULL, 20, 'flyway', 'flyway'),
 ('INDIVIDUAL', 1, 'KRA_PIN', 'KRA PIN certificate', NULL, true, NULL, 30, 'flyway', 'flyway'),
 ('INDIVIDUAL', 1, 'PROOF_ADDRESS', 'Proof of address', 'A utility bill or bank statement from the last three months.', true, 3, 40, 'flyway', 'flyway'),
 ('INDIVIDUAL', 1, 'TITLE_PROOF', 'Proof of ownership', 'Title deed or allotment letter for a property you intend to list.', false, NULL, 50, 'flyway', 'flyway'),

 ('COMPANY', 1, 'CERT_INCORPORATION', 'Certificate of incorporation', NULL, true, NULL, 10, 'flyway', 'flyway'),
 ('COMPANY', 1, 'CR12', 'CR12', 'Issued within the last twelve months.', true, 12, 20, 'flyway', 'flyway'),
 ('COMPANY', 1, 'KRA_PIN', 'Company KRA PIN', NULL, true, NULL, 30, 'flyway', 'flyway'),
 ('COMPANY', 1, 'TAX_COMPLIANCE', 'Tax compliance certificate', 'Valid for twelve months from issue.', true, 12, 40, 'flyway', 'flyway'),
 ('COMPANY', 1, 'DIRECTOR_ID', 'Director''s ID', 'For each director named on the CR12.', true, NULL, 50, 'flyway', 'flyway'),
 ('COMPANY', 1, 'BOARD_RESOLUTION', 'Board resolution', 'Authorising this platform account.', false, NULL, 60, 'flyway', 'flyway'),

 ('SACCO', 1, 'CERT_REGISTRATION', 'Certificate of registration', 'From the Commissioner for Co-operatives.', true, NULL, 10, 'flyway', 'flyway'),
 ('SACCO', 1, 'SASRA_LICENCE', 'SASRA licence', 'Where the SACCO is deposit-taking.', false, 12, 20, 'flyway', 'flyway'),
 ('SACCO', 1, 'KRA_PIN', 'SACCO KRA PIN', NULL, true, NULL, 30, 'flyway', 'flyway'),
 ('SACCO', 1, 'TAX_COMPLIANCE', 'Tax compliance certificate', NULL, true, 12, 40, 'flyway', 'flyway'),
 ('SACCO', 1, 'OFFICIAL_ID', 'Authorised official''s ID', NULL, true, NULL, 50, 'flyway', 'flyway'),
 ('SACCO', 1, 'BOARD_RESOLUTION', 'Committee resolution', 'Authorising this platform account.', true, NULL, 60, 'flyway', 'flyway'),

 ('DEVELOPER', 1, 'CERT_INCORPORATION', 'Certificate of incorporation', NULL, true, NULL, 10, 'flyway', 'flyway'),
 ('DEVELOPER', 1, 'CR12', 'CR12', 'Issued within the last twelve months.', true, 12, 20, 'flyway', 'flyway'),
 ('DEVELOPER', 1, 'KRA_PIN', 'Company KRA PIN', NULL, true, NULL, 30, 'flyway', 'flyway'),
 ('DEVELOPER', 1, 'TAX_COMPLIANCE', 'Tax compliance certificate', NULL, true, 12, 40, 'flyway', 'flyway'),
 ('DEVELOPER', 1, 'NCA_REGISTRATION', 'NCA registration', 'National Construction Authority.', true, 12, 50, 'flyway', 'flyway'),
 ('DEVELOPER', 1, 'APPROVED_PLANS', 'Approved plans', 'For a development you intend to list.', false, NULL, 60, 'flyway', 'flyway'),

 ('AGENCY', 1, 'CERT_INCORPORATION', 'Certificate of incorporation', NULL, true, NULL, 10, 'flyway', 'flyway'),
 ('AGENCY', 1, 'CR12', 'CR12', 'Issued within the last twelve months.', true, 12, 20, 'flyway', 'flyway'),
 ('AGENCY', 1, 'KRA_PIN', 'Company KRA PIN', NULL, true, NULL, 30, 'flyway', 'flyway'),
 ('AGENCY', 1, 'TAX_COMPLIANCE', 'Tax compliance certificate', NULL, true, 12, 40, 'flyway', 'flyway'),
 ('AGENCY', 1, 'EARA_LICENCE', 'Estate agents registration', 'From the Estate Agents Registration Board.', true, 12, 50, 'flyway', 'flyway'),
 ('AGENCY', 1, 'DIRECTOR_ID', 'Director''s ID', NULL, true, NULL, 60, 'flyway', 'flyway'),

 ('GOVERNMENT', 1, 'AUTHORITY_LETTER', 'Letter of authority', 'On letterhead, naming the account holder.', true, NULL, 10, 'flyway', 'flyway'),
 ('GOVERNMENT', 1, 'KRA_PIN', 'Entity KRA PIN', NULL, true, NULL, 20, 'flyway', 'flyway'),
 ('GOVERNMENT', 1, 'OFFICIAL_ID', 'Authorised official''s ID', NULL, true, NULL, 30, 'flyway', 'flyway');
