-- ═════════════════════════════════════════════════════════════════════════════════════════════════
-- Phase 5 / M13 — internal management, seller side (plan §4)
--
-- Three tables the §4 plan names: `property_type_config`, `promotion_package`, `commission_record`. All
-- three exist because something is currently hardcoded, unpriced or uncounted.
--
-- <h2>1. The property types stop being a hardcoded list</h2>
--
-- Six values live in a Java enum, three Vue arrays and a form's validation. Adding "godown" or "serviced
-- apartment" today means a deploy in two repositories, and the fields the form asks for are decided by a
-- switch nobody can see. A table lets the platform add a type, say which of bedrooms, floor area and plot
-- area apply to it, and have every form follow.
--
-- <h2>2. Promotion, without inventing a payment flow</h2>
--
-- A package is what the platform sells: a placement for a number of days at a price. A promotion is one
-- listing holding one package for a window. The platform does not take the money here — there is no payments
-- integration and pretending otherwise would be the worst kind of half-feature — so a seller *requests* a
-- promotion and the platform activates it once they have been paid however they were paid.
--
-- <h2>3. Commission, raised when a sale completes</h2>
--
-- The platform earns on a completed sale, and until now nothing recorded that. A commission is raised from
-- the rate in force at the moment a listing is marked sold, and the rate is **copied onto the row** rather
-- than referenced: a rate change next quarter must not silently restate what was owed last quarter.
-- ═════════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE property_type_configs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    code            VARCHAR(32)  NOT NULL UNIQUE,
    name            VARCHAR(120) NOT NULL,
    description     TEXT,
    icon            VARCHAR(8),
    sort_order      INTEGER      NOT NULL DEFAULT 100,

    -- Which questions a listing of this kind should be asked. A godown has a floor area and no bedrooms;
    -- land has a plot area and neither. Today that is a switch nobody can see.
    has_bedrooms    BOOLEAN      NOT NULL DEFAULT true,
    has_bathrooms   BOOLEAN      NOT NULL DEFAULT true,
    has_floor_area  BOOLEAN      NOT NULL DEFAULT true,
    has_plot_area   BOOLEAN      NOT NULL DEFAULT false,
    has_year_built  BOOLEAN      NOT NULL DEFAULT true,
    -- Whether a listing of this kind may be let rather than sold.
    lettable        BOOLEAN      NOT NULL DEFAULT true,

    status          INTEGER      NOT NULL DEFAULT 1,
    status_flag     VARCHAR(32)  NOT NULL DEFAULT 'Active',

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      VARCHAR(64),
    updated_by      VARCHAR(64)
);

-- The six that were hardcoded, with the fields each actually needs.
INSERT INTO property_type_configs
    (code, name, description, icon, sort_order,
     has_bedrooms, has_bathrooms, has_floor_area, has_plot_area, has_year_built, lettable, created_by)
VALUES
    ('HOUSE',      'House',       'A standalone house on its own plot.',      '🏠', 10, true,  true,  true,  true,  true,  true,  'system'),
    ('APARTMENT',  'Apartment',   'A flat within a block.',                   '🏢', 20, true,  true,  true,  false, true,  true,  'system'),
    ('TOWNHOUSE',  'Townhouse',   'A house in a terrace or gated court.',     '🏘', 30, true,  true,  true,  true,  true,  true,  'system'),
    ('MAISONETTE', 'Maisonette',  'A two-storey home within a larger building.','🏡', 40, true, true,  true,  false, true,  true,  'system'),
    -- Land has none of the building questions and is not lettable through this platform.
    ('LAND',       'Land',        'A plot with nothing built on it.',         '🌍', 50, false, false, false, true,  false, false, 'system'),
    ('COMMERCIAL', 'Commercial',  'Offices, retail space, warehousing.',      '🏬', 60, false, true,  true,  true,  true,  true,  'system');

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- What the platform sells.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE promotion_packages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    reference       VARCHAR(16)  NOT NULL UNIQUE,
    code            VARCHAR(32)  NOT NULL UNIQUE,
    name            VARCHAR(120) NOT NULL,
    description     TEXT,

    -- FEATURED | TOP_OF_SEARCH | HOMEPAGE. What the placement actually does, so search can act on it
    -- rather than on the package's name.
    placement       VARCHAR(24)  NOT NULL,
    duration_days   INTEGER      NOT NULL,
    price           NUMERIC(15, 2) NOT NULL,
    currency        VARCHAR(3)   NOT NULL DEFAULT 'KES',

    -- How hard it lifts a listing in search results. A number rather than an order, so two packages can
    -- coexist without one implying the other's rank.
    boost           INTEGER      NOT NULL DEFAULT 10,

    status          INTEGER      NOT NULL DEFAULT 1,
    status_flag     VARCHAR(32)  NOT NULL DEFAULT 'Active',

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      VARCHAR(64),
    updated_by      VARCHAR(64),

    CONSTRAINT ck_package_placement
        CHECK (placement IN ('FEATURED', 'TOP_OF_SEARCH', 'HOMEPAGE')),
    CONSTRAINT ck_package_duration CHECK (duration_days > 0),
    CONSTRAINT ck_package_price CHECK (price >= 0)
);

INSERT INTO promotion_packages
    (reference, code, name, description, placement, duration_days, price, boost, created_by)
VALUES
    ('PK260826AAAA', 'FEATURED_30', 'Featured — 30 days',
     'A badge on the card and a lift in search results for a month.', 'FEATURED', 30, 7500, 10, 'system'),
    ('PK260826AAAB', 'TOP_14', 'Top of search — 14 days',
     'Above everything else matching the search, for a fortnight.', 'TOP_OF_SEARCH', 14, 12000, 50, 'system'),
    ('PK260826AAAC', 'HOMEPAGE_7', 'Homepage — 7 days',
     'On the front page for a week.', 'HOMEPAGE', 7, 20000, 100, 'system');

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- One listing holding one package for a window.
--
-- The price and the placement are copied onto the row. A package repriced next month must not restate what
-- somebody bought last month — the same reasoning as the commission rate below.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE listing_promotions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    reference         VARCHAR(16)  NOT NULL UNIQUE,
    property_id       BIGINT       NOT NULL REFERENCES properties (id),
    property_ref      VARCHAR(16),
    property_title    VARCHAR(255),
    tenant_id         BIGINT       NOT NULL,
    tenant_name       VARCHAR(255),

    package_id        BIGINT       NOT NULL REFERENCES promotion_packages (id),
    package_name      VARCHAR(120),
    placement         VARCHAR(24)  NOT NULL,
    boost             INTEGER      NOT NULL DEFAULT 10,
    price             NUMERIC(15, 2) NOT NULL,
    currency          VARCHAR(3)   NOT NULL DEFAULT 'KES',
    duration_days     INTEGER      NOT NULL,

    -- REQUESTED | ACTIVE | EXPIRED | CANCELLED. The platform activates once it has been paid, however it
    -- was paid — there is no payments integration here and pretending otherwise would be worse than saying
    -- so.
    state             VARCHAR(16)  NOT NULL DEFAULT 'REQUESTED',
    starts_at         TIMESTAMPTZ,
    ends_at           TIMESTAMPTZ,
    activated_by_user_id BIGINT,
    cancelled_reason  TEXT,
    note              TEXT,

    status            INTEGER      NOT NULL DEFAULT 1,
    status_flag       VARCHAR(32)  NOT NULL DEFAULT 'Active',

    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by        VARCHAR(64),
    updated_by        VARCHAR(64),

    CONSTRAINT ck_promotion_state
        CHECK (state IN ('REQUESTED', 'ACTIVE', 'EXPIRED', 'CANCELLED')),
    CONSTRAINT ck_promotion_window CHECK (
        state <> 'ACTIVE' OR (starts_at IS NOT NULL AND ends_at IS NOT NULL AND ends_at > starts_at))
);

-- One live promotion per listing. Two at once is two people's money buying the same placement.
CREATE UNIQUE INDEX uk_promotion_live ON listing_promotions (property_id)
    WHERE state IN ('REQUESTED', 'ACTIVE') AND status <> 5;
CREATE INDEX idx_promotion_active ON listing_promotions (ends_at)
    WHERE state = 'ACTIVE' AND status <> 5;
CREATE INDEX idx_promotion_tenant ON listing_promotions (tenant_id, created_at DESC);

ALTER TABLE listing_promotions ADD COLUMN search_text text
    GENERATED ALWAYS AS (
        lower(coalesce(reference, '') || ' ' || coalesce(property_ref, '') || ' ' ||
              coalesce(property_title, '') || ' ' || coalesce(tenant_name, '') || ' ' ||
              coalesce(package_name, '') || ' ' || coalesce(state, ''))
    ) STORED;
CREATE INDEX idx_promotion_search_trgm ON listing_promotions USING gin (search_text public.gin_trgm_ops);

-- The boost a listing currently carries, denormalised so marketplace search sorts without a join. Written
-- by PromotionService and by nothing else.
ALTER TABLE properties ADD COLUMN promotion_boost INTEGER NOT NULL DEFAULT 0;
ALTER TABLE properties ADD COLUMN promoted_until TIMESTAMPTZ;
CREATE INDEX idx_property_boost ON properties (promotion_boost DESC)
    WHERE listing_state = 'LIVE' AND status <> 5;

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- What the platform earned.
--
-- Raised when a listing is marked sold, from the rate in force at that moment. The rate is copied onto the
-- row: a rate change next quarter must not silently restate what was owed last quarter.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE commission_records (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    reference       VARCHAR(16)  NOT NULL UNIQUE,

    property_id     BIGINT       NOT NULL REFERENCES properties (id),
    property_ref    VARCHAR(16),
    property_title  VARCHAR(255),
    tenant_id       BIGINT       NOT NULL,
    tenant_name     VARCHAR(255),

    sale_price      NUMERIC(15, 2) NOT NULL,
    -- The rate as it stood, not a pointer to a setting that will change.
    rate_percent    NUMERIC(6, 3)  NOT NULL,
    amount          NUMERIC(15, 2) NOT NULL,
    currency        VARCHAR(3)   NOT NULL DEFAULT 'KES',

    sold_at         TIMESTAMPTZ  NOT NULL,

    -- DUE | INVOICED | PAID | WAIVED
    state           VARCHAR(16)  NOT NULL DEFAULT 'DUE',
    invoice_ref     VARCHAR(64),
    invoiced_at     TIMESTAMPTZ,
    paid_at         TIMESTAMPTZ,
    waived_reason   TEXT,
    note            TEXT,

    status          INTEGER      NOT NULL DEFAULT 1,
    status_flag     VARCHAR(32)  NOT NULL DEFAULT 'Active',

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      VARCHAR(64),
    updated_by      VARCHAR(64),

    CONSTRAINT ck_commission_state CHECK (state IN ('DUE', 'INVOICED', 'PAID', 'WAIVED')),
    CONSTRAINT ck_commission_paid CHECK (state <> 'PAID' OR paid_at IS NOT NULL),
    -- Waiving money says why. A waiver with no reason is not a decision anybody can review afterwards.
    CONSTRAINT ck_commission_waived CHECK (state <> 'WAIVED' OR waived_reason IS NOT NULL)
);

-- One commission per sale. A listing sold twice is a listing relisted, and that is a second row on a
-- second sale — but not two rows for one.
CREATE UNIQUE INDEX uk_commission_per_sale ON commission_records (property_id, sold_at);
CREATE INDEX idx_commission_state ON commission_records (state, sold_at DESC);
CREATE INDEX idx_commission_tenant ON commission_records (tenant_id, sold_at DESC);

ALTER TABLE commission_records ADD COLUMN search_text text
    GENERATED ALWAYS AS (
        lower(coalesce(reference, '') || ' ' || coalesce(property_ref, '') || ' ' ||
              coalesce(property_title, '') || ' ' || coalesce(tenant_name, '') || ' ' ||
              coalesce(invoice_ref, '') || ' ' || coalesce(state, ''))
    ) STORED;
CREATE INDEX idx_commission_search_trgm ON commission_records USING gin (search_text public.gin_trgm_ops);
