-- ═════════════════════════════════════════════════════════════════════════════════════════════════
-- Progress updates stop being a listing's private diary
--
-- A development's build is the thing buyers actually follow, and today the only place a build can be reported
-- is against a `properties` row. Two options: a second table, or this one widened. This one, because a second
-- table makes ProgressTimeline.vue a client-side merge of two arrays sorted by date, and because every screen
-- that reads a timeline would have to learn which table its subject lives in.
--
-- <h2>Exactly one subject, said by the database</h2>
--
-- `property_id` and `tenant_id` become nullable and a CHECK requires exactly one of `property_id` or
-- `development_id`. Every existing row has `property_id` set, so both the new CHECK and the new columns
-- validate on the spot — no backfill, and nothing to run out of hours.
--
-- `phase_id` and `unit_id` narrow a development update to part of the build ("Block B roofed") and are always
-- optional: most updates are about the project.
--
-- <h2>The milestone vocabulary stops being a Vue array</h2>
--
-- Eight strings live in ProgressEditor.vue as a `<datalist>` over a free-text column, which means "Slab",
-- "slab" and "Slab poured" are three milestones and no screen can group by stage. `milestone_code` is the
-- stable identifier; `milestone` stays as the free text, because eight names chosen by us are not the eight
-- names every developer uses, and refusing an unlisted stage would make the field worse than it is now.
--
-- The same move `property_type_configs` already made for property types.
--
-- <h2>image_count</h2>
--
-- `image_key` stays and becomes a cover cache over `media_assets`, so old rows and new ones render
-- identically before any carousel exists. `image_count` is what lets a card say "4 photos" without a second
-- query per row in a feed.
-- ═════════════════════════════════════════════════════════════════════════════════════════════════

-- ── the vocabulary ───────────────────────────────────────────────────────────────────────────────

CREATE TABLE progress_milestone_configs (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    code             VARCHAR(32)  NOT NULL UNIQUE,
    name             VARCHAR(120) NOT NULL,
    description      TEXT,

    -- Roughly how far along a build is when it reaches this stage. Used to *offer* a figure when somebody
    -- picks a milestone, never to overwrite one they typed: a site can be at roofing and 40% complete, and a
    -- table that silently corrected them would be reporting our guess as their measurement.
    typical_percent  SMALLINT,

    -- Where it sits in the build, which is not alphabetical and not the order somebody added rows in.
    sort_order       INTEGER      NOT NULL DEFAULT 100,

    status           INTEGER      NOT NULL DEFAULT 1,
    status_flag      VARCHAR(32)  NOT NULL DEFAULT 'Active',

    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by       VARCHAR(64),
    updated_by       VARCHAR(64),

    CONSTRAINT ck_milestone_percent
        CHECK (typical_percent IS NULL OR (typical_percent >= 0 AND typical_percent <= 100))
);

CREATE INDEX idx_milestone_order ON progress_milestone_configs (sort_order) WHERE status <> 5;

-- The eight already in ProgressEditor.vue, in build order, with a percentage each. The figures are ordinary
-- construction-sequence estimates offered as a default, which is why the column is called typical.
INSERT INTO progress_milestone_configs (code, name, typical_percent, sort_order, description) VALUES
    ('GROUNDWORKS',    'Groundworks',    5,   10, 'Site cleared, excavation and setting out'),
    ('FOUNDATION',     'Foundation',     15,  20, 'Footings and foundation walls'),
    ('SLAB',           'Slab',           25,  30, 'Ground floor slab cast'),
    ('SUPERSTRUCTURE', 'Superstructure', 50,  40, 'Walls and floors to full height'),
    ('ROOFING',        'Roofing',        65,  50, 'Roof structure and covering complete'),
    ('PLASTERING',     'Plastering',     78,  60, 'Internal and external plaster'),
    ('FINISHES',       'Finishes',       92,  70, 'Fittings, fixtures, paint and joinery'),
    ('HANDOVER',       'Handover',       100, 80, 'Complete and handed to the buyer');

-- ── the widened table ────────────────────────────────────────────────────────────────────────────

ALTER TABLE listing_progress_updates
    ALTER COLUMN property_id DROP NOT NULL,
    ALTER COLUMN tenant_id   DROP NOT NULL,
    ADD COLUMN development_id BIGINT      REFERENCES developments (id),
    ADD COLUMN phase_id       BIGINT      REFERENCES development_phases (id),
    ADD COLUMN unit_id        BIGINT      REFERENCES development_units (id),
    ADD COLUMN institution_id BIGINT,
    ADD COLUMN milestone_code VARCHAR(32) REFERENCES progress_milestone_configs (code),
    ADD COLUMN image_count    INTEGER     NOT NULL DEFAULT 0;

-- One subject, never two and never none. Validates immediately: every existing row has property_id.
ALTER TABLE listing_progress_updates ADD CONSTRAINT ck_progress_subject CHECK (
    (property_id IS NOT NULL)::int + (development_id IS NOT NULL)::int = 1);

-- A phase or a unit only makes sense under a development. Without this, an update against a listing could
-- carry another project's phase and no query would notice.
ALTER TABLE listing_progress_updates ADD CONSTRAINT ck_progress_child_needs_development CHECK (
    development_id IS NOT NULL OR (phase_id IS NULL AND unit_id IS NULL));

-- Who may see it, cached from the subject so an access check is one read rather than a walk up the tree.
-- Not "exactly one": a listing update has a tenant, a bank's project has an institution, and a
-- platform-owned project has neither.
ALTER TABLE listing_progress_updates ADD CONSTRAINT ck_progress_owner CHECK (
    (institution_id IS NULL) OR (tenant_id IS NULL));

ALTER TABLE listing_progress_updates ADD CONSTRAINT ck_progress_image_count CHECK (image_count >= 0);

COMMENT ON COLUMN listing_progress_updates.milestone IS
    'The free text the reporter typed. milestone_code is the stable identifier; this stays because eight '
    'names chosen by us are not the eight every developer uses.';
COMMENT ON COLUMN listing_progress_updates.image_key IS
    'Cover photograph. A cache over media_assets for PROGRESS_UPDATE, so rows written before that table '
    'existed still render.';

-- ── indexes for the two new reads ────────────────────────────────────────────────────────────────

CREATE INDEX idx_progress_development ON listing_progress_updates (development_id, reported_on DESC)
    WHERE development_id IS NOT NULL AND status <> 5;

-- The development's public timeline: published rows for one project.
CREATE INDEX idx_progress_development_public ON listing_progress_updates (development_id, reported_on DESC)
    WHERE development_id IS NOT NULL AND published AND status <> 5;

-- The cross-project feed on the public site. No leading subject column, because this query has no subject:
-- it is "everything published, newest first", paged. Ordered by id as well so a page boundary between two
-- updates reported on the same day is stable — without it the second page can repeat or skip a row.
CREATE INDEX idx_progress_feed ON listing_progress_updates (reported_on DESC, id DESC)
    WHERE published AND status <> 5;
