-- ═════════════════════════════════════════════════════════════════════════════════════════════════
-- Phase 5 / M12 — internal management, buyer side (plan §4)
--
-- Two tables, and the §4 table names say exactly what they are: `ticket_assignment_rule` and
-- `event_calendar_entry`. Neither is a new ticket system — M4 already has enquiries, viewings and offers,
-- and a second inbox beside them would be the platform competing with itself for somebody's attention.
--
-- <h2>1. Routing, so an enquiry lands on a desk</h2>
--
-- Today an enquiry arrives unassigned and stays unassigned until somebody replies, at which point it
-- attaches itself to whoever happened to open it first. That works for a two-person seller and fails for
-- everybody else: the enquiries nobody opens are exactly the ones nobody is accountable for.
--
-- A rule matches on what is knowable at the moment a lead arrives — county, property type, the organisation
-- — and names who it goes to. Rules are ordered and the first match wins, because "most specific wins" is a
-- scoring system nobody can predict the behaviour of by reading the list.
--
-- <h2>2. A diary, because the work has dates on it</h2>
--
-- Viewings, valuation appointments and auctions all already have times, and they are in three different
-- modules. Somebody whose job is the week ahead should not have to open three screens to find it.
--
-- The calendar is a *projection*, not a second source of truth: an entry points back at the row it came
-- from and is rewritten when that row moves. Manual entries — a meeting, a site inspection, a deadline —
-- have no source and are the only ones the calendar itself owns.
-- ═════════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE ticket_assignment_rules (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    reference         VARCHAR(16)  NOT NULL UNIQUE,
    name              VARCHAR(160) NOT NULL,

    -- Null means the platform's own rules. A seller's rules only ever see their own leads.
    tenant_id         BIGINT REFERENCES tenants (id),

    -- What it routes: ENQUIRY | SITE_VISIT | PURCHASE_REQUEST. One rule, one kind of work — a rule that
    -- routed all three would need three sets of criteria to be useful and would be read as one.
    work_type         VARCHAR(24)  NOT NULL,

    -- The criteria. All null means "everything", which is what a catch-all rule at the bottom of the list
    -- is for. Each is compared exactly, case-insensitively.
    county            VARCHAR(64),
    property_type     VARCHAR(32),
    -- A platform rule may narrow to one seller; a seller's rule may not (it is already narrowed).
    match_tenant_id   BIGINT,

    -- Where it goes. Exactly one of the two: a named person, or round-robin within a user group.
    assignee_user_id  BIGINT REFERENCES users (id),
    assignee_name     VARCHAR(160),
    assignee_group_id BIGINT REFERENCES user_groups (id),
    assignee_group_name VARCHAR(160),
    -- Round-robin needs to remember where it got to. Not a random pick: random distributes badly over small
    -- numbers and nobody can tell whether it is working.
    last_assigned_user_id BIGINT,

    -- First match wins. Ordered rather than scored, because a scoring system is one nobody can predict the
    -- behaviour of by reading the list.
    priority          INTEGER      NOT NULL DEFAULT 100,

    status            INTEGER      NOT NULL DEFAULT 1,
    status_flag       VARCHAR(32)  NOT NULL DEFAULT 'Active',

    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by        VARCHAR(64),
    updated_by        VARCHAR(64),

    CONSTRAINT ck_rule_work_type
        CHECK (work_type IN ('ENQUIRY', 'SITE_VISIT', 'PURCHASE_REQUEST')),
    CONSTRAINT ck_rule_target CHECK (
        (assignee_user_id IS NOT NULL)::int + (assignee_group_id IS NOT NULL)::int = 1)
);

CREATE INDEX idx_rule_lookup ON ticket_assignment_rules (work_type, priority)
    WHERE status NOT IN (4, 5);
CREATE INDEX idx_rule_tenant ON ticket_assignment_rules (tenant_id);

ALTER TABLE ticket_assignment_rules ADD COLUMN search_text text
    GENERATED ALWAYS AS (
        lower(coalesce(reference, '') || ' ' || coalesce(name, '') || ' ' ||
              coalesce(work_type, '') || ' ' || coalesce(county, '') || ' ' ||
              coalesce(property_type, '') || ' ' || coalesce(assignee_name, '') || ' ' ||
              coalesce(assignee_group_name, ''))
    ) STORED;
CREATE INDEX idx_rule_search_trgm ON ticket_assignment_rules USING gin (search_text gin_trgm_ops);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- The diary.
--
-- A projection of things that already have times, plus the entries somebody typed. `source_type` and
-- `source_id` point back; a manual entry has neither, and that is what makes it editable here.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE event_calendar_entries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    reference       VARCHAR(16)  NOT NULL UNIQUE,

    -- SITE_VISIT | VALUATION | AUCTION | MANUAL.
    --
    -- VALUATION is in the list and nothing writes it yet: a valuation job records when it was assigned and
    -- when it was finished, and neither of those is an appointment. Projecting `assigned_at` as a diary
    -- entry would put a fact in the calendar that is not the fact it claims to be. The value stays here so
    -- that giving a valuation a visit time later is one service change rather than a migration.
    source_type     VARCHAR(24)  NOT NULL,
    source_id       BIGINT,
    source_ref      VARCHAR(16),

    tenant_id       BIGINT,
    tenant_name     VARCHAR(255),

    title           VARCHAR(255) NOT NULL,
    detail          TEXT,
    location        VARCHAR(255),

    starts_at       TIMESTAMPTZ  NOT NULL,
    ends_at         TIMESTAMPTZ,
    all_day         BOOLEAN      NOT NULL DEFAULT false,

    -- Who it is for. Null means the whole organisation's diary rather than one person's.
    owner_user_id   BIGINT REFERENCES users (id),
    owner_name      VARCHAR(160),

    state           VARCHAR(16)  NOT NULL DEFAULT 'SCHEDULED',

    status          INTEGER      NOT NULL DEFAULT 1,
    status_flag     VARCHAR(32)  NOT NULL DEFAULT 'Active',

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      VARCHAR(64),
    updated_by      VARCHAR(64),

    CONSTRAINT ck_entry_source
        CHECK (source_type IN ('SITE_VISIT', 'VALUATION', 'AUCTION', 'MANUAL')),
    CONSTRAINT ck_entry_state
        CHECK (state IN ('SCHEDULED', 'DONE', 'CANCELLED')),
    -- A projected entry knows where it came from; a manual one does not have a source at all.
    CONSTRAINT ck_entry_projection CHECK (
        (source_type = 'MANUAL') = (source_id IS NULL)),
    CONSTRAINT ck_entry_span CHECK (ends_at IS NULL OR ends_at >= starts_at)
);

-- One entry per source row. A projection that can duplicate is a diary with the same viewing in it twice.
CREATE UNIQUE INDEX uk_entry_source ON event_calendar_entries (source_type, source_id)
    WHERE source_id IS NOT NULL;
CREATE INDEX idx_entry_window ON event_calendar_entries (starts_at) WHERE status <> 5;
CREATE INDEX idx_entry_tenant ON event_calendar_entries (tenant_id, starts_at);
CREATE INDEX idx_entry_owner ON event_calendar_entries (owner_user_id, starts_at)
    WHERE owner_user_id IS NOT NULL;

ALTER TABLE event_calendar_entries ADD COLUMN search_text text
    GENERATED ALWAYS AS (
        lower(coalesce(reference, '') || ' ' || coalesce(title, '') || ' ' ||
              coalesce(detail, '') || ' ' || coalesce(location, '') || ' ' ||
              coalesce(tenant_name, '') || ' ' || coalesce(owner_name, ''))
    ) STORED;
CREATE INDEX idx_entry_search_trgm ON event_calendar_entries USING gin (search_text gin_trgm_ops);
