-- The people and companies a development pays, named once and paid many times.
--
-- Until now a cost carried a free-text payee: "Mwangi Hardware" on one line, "mwangi h/w" on the next, and
-- no way to say what kind of payee either was. A beneficiary is a record of its own, owned by the organisation
-- that pays it, reusable across that owner's developments, and confirmed with the bank before it can be paid.

-- ── what kind of payee ─────────────────────────────────────────────────────────────────────────────
--
-- A platform list, like cost categories: the bank adds a type without a deploy, and a suspended type keeps
-- its name on the beneficiaries already filed under it.
CREATE TABLE beneficiary_types (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(32)  NOT NULL UNIQUE,
    name        VARCHAR(120) NOT NULL,
    description TEXT,
    sort_order  INTEGER      NOT NULL DEFAULT 100,
    status      INTEGER      NOT NULL DEFAULT 1,
    status_flag VARCHAR(32)  NOT NULL DEFAULT 'Active',
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(64),
    updated_by  VARCHAR(64)
);

INSERT INTO beneficiary_types (code, name, description, sort_order, created_by) VALUES
    ('SUPPLIER',          'Supplier',           'Materials and goods: hardware, cement, fittings.', 10, 'migration'),
    ('CONTRACTOR',        'Contractor',         'The main contractor on the works.', 20, 'migration'),
    ('SUBCONTRACTOR',     'Subcontractor',      'Trades under the contractor: electrical, plumbing, roofing.', 30, 'migration'),
    ('CONSULTANT',        'Consultant',         'Architects, engineers, quantity surveyors, project managers.', 40, 'migration'),
    ('PROFESSIONAL_FEES', 'Professional fees',  'Lawyers, valuers, auditors.', 50, 'migration'),
    ('UTILITY',           'Utility',            'Power, water, connections.', 60, 'migration'),
    ('GOVERNMENT',        'Government and county', 'Approvals, NEMA, NCA, rates and levies.', 70, 'migration'),
    ('LABOUR',            'Labour',             'Casual and site labour paid directly.', 80, 'migration'),
    ('LANDOWNER',         'Landowner',          'The seller of the land, or a lessor.', 90, 'migration'),
    ('OTHER',             'Other',              'Anybody the types above do not name.', 100, 'migration');

-- ── the beneficiaries ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE beneficiaries (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference         VARCHAR(16)  NOT NULL UNIQUE,

    -- Whose payee: exactly one owner. The platform itself pays nobody through here.
    tenant_id         BIGINT,
    institution_id    BIGINT,

    type_id           BIGINT       NOT NULL REFERENCES beneficiary_types(id),
    name              VARCHAR(160) NOT NULL,
    kra_pin           VARCHAR(16),
    contact_name      VARCHAR(120),
    contact_phone     VARCHAR(32),
    contact_email     VARCHAR(160),

    -- Where they are paid. PesaLink to a bank account for now; the bank code is the clearing code.
    bank_code         VARCHAR(8)   NOT NULL,
    account_no        VARCHAR(32)  NOT NULL,

    -- What the bank said the account is held in, and when. A beneficiary is paid only once VERIFIED: the name
    -- a checker approves a payment against is this one, not the one somebody typed.
    verification      VARCHAR(12)  NOT NULL DEFAULT 'UNVERIFIED',
    confirmed_name    VARCHAR(160),
    confirmed_at      TIMESTAMPTZ,
    verification_note TEXT,

    notes             TEXT,

    -- 0 written and waiting for a second person; 1 live; 4 refused or deactivated; 5 archived.
    status            INTEGER      NOT NULL DEFAULT 0,
    status_flag       VARCHAR(32)  NOT NULL DEFAULT 'New',

    search_text       TEXT GENERATED ALWAYS AS (
        lower(coalesce(name, '') || ' ' || coalesce(reference, '') || ' ' || coalesce(account_no, '') || ' '
              || coalesce(confirmed_name, '') || ' ' || coalesce(contact_name, '') || ' ' || coalesce(kra_pin, ''))
    ) STORED,

    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by        VARCHAR(64),
    updated_by        VARCHAR(64),

    CONSTRAINT ck_beneficiary_owner CHECK ((tenant_id IS NULL) <> (institution_id IS NULL)),
    CONSTRAINT ck_beneficiary_verification CHECK (verification IN ('VERIFIED', 'UNVERIFIED'))
);

CREATE INDEX idx_beneficiary_tenant ON beneficiaries (tenant_id) WHERE tenant_id IS NOT NULL;
CREATE INDEX idx_beneficiary_institution ON beneficiaries (institution_id) WHERE institution_id IS NOT NULL;
-- One owner registers one account once. The same account may be another owner's supplier too.
CREATE UNIQUE INDEX uk_beneficiary_payout ON beneficiaries
    (coalesce(tenant_id, 0), coalesce(institution_id, 0), bank_code, account_no) WHERE status <> 5;

-- pg_trgm's operator class, wherever the extension lives (see V20260920140000 for why).
DO $$
DECLARE ext_schema text;
BEGIN
    SELECT n.nspname INTO ext_schema
      FROM pg_extension e JOIN pg_namespace n ON n.oid = e.extnamespace
     WHERE e.extname = 'pg_trgm';
    IF ext_schema IS NULL THEN
        EXECUTE 'CREATE EXTENSION pg_trgm';
        ext_schema := current_schema();
    END IF;
    EXECUTE format('SET LOCAL search_path TO %I, %I', current_schema(), ext_schema);
END $$;
CREATE INDEX idx_beneficiary_search ON beneficiaries USING gin (search_text gin_trgm_ops);
