-- A valuation is reviewed before it counts, and remembers everything that happened to it.
--
-- A report used to complete a job the moment one valuer submitted it. Now it lands as SUBMITTED and a second
-- person approves it to COMPLETED or sends it back; the figure the bank lends against has had two pairs of
-- eyes. And each thing that happens — raised, assigned, accepted, handed back, reported, approved, sent
-- back, cancelled — is a row of its own, so a job handed back twice says so instead of overwriting itself.

ALTER TABLE valuation_requests
    -- Optimistic lock: two people assigning at once must not both succeed.
    ADD COLUMN version      INTEGER     NOT NULL DEFAULT 0,
    ADD COLUMN submitted_at TIMESTAMPTZ,
    ADD COLUMN reviewed_by  VARCHAR(64),
    ADD COLUMN reviewed_at  TIMESTAMPTZ,
    ADD COLUMN review_note  TEXT;

CREATE TABLE valuation_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id  BIGINT       NOT NULL REFERENCES valuation_requests (id),
    -- RAISED | ASSIGNED | ACCEPTED | HANDED_BACK | REPORTED | APPROVED | SENT_BACK | CANCELLED
    action      VARCHAR(16)  NOT NULL,
    state       VARCHAR(16)  NOT NULL,
    actor       VARCHAR(64),
    actor_role  VARCHAR(16),
    note        TEXT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_valuation_events_request ON valuation_events (request_id, created_at);

-- The statement now says what the job was for, whom it was for, what it cost, when it was due, and what
-- the figures were — and carries the owner columns the report engine scopes on.
DROP VIEW IF EXISTS v_report_valuations;
CREATE VIEW v_report_valuations AS
SELECT vr.reference,
       vr.property_reference,
       vr.property_title,
       vr.county,
       vr.purpose,
       coalesce(vr.institution_name, vr.tenant_name)         AS requested_by,
       vr.valuer_name,
       vr.assignment_method,
       CASE vr.state
            WHEN 'REQUESTED'   THEN 'Waiting for a valuer'
            WHEN 'ASSIGNED'    THEN 'With a valuer'
            WHEN 'IN_PROGRESS' THEN 'In progress'
            WHEN 'SUBMITTED'   THEN 'Report in, awaiting review'
            WHEN 'COMPLETED'   THEN 'Done'
            WHEN 'CANCELLED'   THEN 'Cancelled'
            ELSE vr.state END                                 AS state,
       vr.property_price,
       rp.market_value,
       rp.forced_sale_value,
       CASE WHEN rp.market_value IS NOT NULL AND vr.property_price > 0
            THEN round((rp.market_value - vr.property_price) * 100 / vr.property_price, 1) END AS variance_pct,
       rp.methodology,
       vr.fee_amount,
       vr.currency,
       vr.due_on,
       CASE WHEN vr.due_on IS NOT NULL AND vr.completed_at IS NULL AND vr.state NOT IN ('COMPLETED', 'CANCELLED')
                 AND vr.due_on < CURRENT_DATE THEN true ELSE false END AS overdue,
       vr.created_at                                          AS requested_at,
       vr.assigned_at,
       vr.submitted_at,
       vr.completed_at,
       CASE WHEN vr.completed_at IS NOT NULL
            THEN EXTRACT(day FROM (vr.completed_at - vr.created_at))::int END AS days_to_complete,
       (SELECT count(*) FROM valuation_events e WHERE e.request_id = vr.id AND e.action = 'HANDED_BACK') AS hand_backs,
       vr.tenant_id,
       vr.institution_id,
       NULL::bigint                                           AS development_id
  FROM valuation_requests vr
  LEFT JOIN valuation_reports rp ON rp.request_id = vr.id
 WHERE vr.status <> 5;
