-- ═════════════════════════════════════════════════════════════════════════════════════════════════
-- Phase 3 / M5 — valuation (BRD FR035–FR048, plan §3.5)
--
-- A third kind of actor, and the first one whose visibility is neither "my organisation" nor "everything".
--
-- <h2>A valuer is a person, not an organisation</h2>
--
-- They sit on a panel. They carry professional indemnity cover, a registration number and a set of counties
-- they will travel to, and they see exactly the jobs assigned to them — not their firm's, not the seller's,
-- not the platform's. That is the assignment-scoped visibility §3.5 called for, and it is the reason this
-- module exists as its own thing rather than as a state on a property.
--
-- <h2>The PI rule</h2>
--
-- FR041: a valuer may only be assigned work whose value their professional indemnity cover would meet. The
-- rule is enforced at assignment, in code, against `pi_sum_assured` — and the cover's expiry is checked too,
-- because a policy that lapsed in March is not cover in June.
-- ═════════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE valuer_profiles (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- The person, and the profile that carries their VALUER standing. Both, because the person is who is
    -- paid and the profile is what authorisation resolves from.
    user_id             BIGINT       NOT NULL REFERENCES users (id),
    profile_id          BIGINT       NOT NULL REFERENCES user_profiles (id),

    reference           VARCHAR(16)  NOT NULL UNIQUE,
    full_name           VARCHAR(160),
    firm_name           VARCHAR(255),

    -- Institution of Surveyors of Kenya, or whichever body registers them.
    registration_number VARCHAR(64),
    registration_body   VARCHAR(64),
    registered_until    DATE,

    -- Professional indemnity. The sum assured is the ceiling on what they may be assigned (FR041), and the
    -- expiry is why that ceiling can lapse without anybody editing the row.
    pi_insurer          VARCHAR(160),
    pi_policy_number    VARCHAR(64),
    pi_sum_assured      NUMERIC(15, 2),
    pi_expires_on       DATE,

    -- Where they will travel, as a CSV of counties. Matched by exact token like app_modules'
    -- allowed_user_types, never by LIKE — '%Kisumu%' would also match nothing useful and something wrong.
    counties            TEXT,
    specialisations     TEXT,

    -- On the panel, or not. Separate from `status`: a valuer suspended from the panel for a quarter is a
    -- live row that must not be assigned work, which is a different thing from an archived one.
    on_panel            BOOLEAN      NOT NULL DEFAULT true,
    panel_note          TEXT,

    -- Maintained aggregates for round-robin: assign to whoever has least on, and break ties by who has
    -- waited longest.
    open_assignments    INTEGER      NOT NULL DEFAULT 0,
    completed_count     INTEGER      NOT NULL DEFAULT 0,
    last_assigned_at    TIMESTAMPTZ,

    status              INTEGER      NOT NULL DEFAULT 1,
    status_flag         VARCHAR(32)  NOT NULL DEFAULT 'Active',

    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          VARCHAR(64),
    updated_by          VARCHAR(64),

    CONSTRAINT uk_valuer_profile UNIQUE (profile_id),
    CONSTRAINT ck_valuer_pi CHECK (pi_sum_assured IS NULL OR pi_sum_assured >= 0)
);

CREATE INDEX idx_valuer_user ON valuer_profiles (user_id);
-- The assignment query: who is available, least loaded first.
CREATE INDEX idx_valuer_available ON valuer_profiles (open_assignments, last_assigned_at)
    WHERE on_panel AND status <> 5;

ALTER TABLE valuer_profiles ADD COLUMN search_text text
    GENERATED ALWAYS AS (
        lower(coalesce(reference, '') || ' ' || coalesce(full_name, '') || ' ' ||
              coalesce(firm_name, '') || ' ' || coalesce(registration_number, '') || ' ' ||
              coalesce(counties, ''))
    ) STORED;
CREATE INDEX idx_valuer_search_trgm ON valuer_profiles USING gin (search_text gin_trgm_ops);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- A job.
--
-- Raised by a seller wanting a figure for a listing, or by a lender who will not lend without one. Both
-- columns exist and exactly one is set — the requester decides who may see the report, and "a seller asked"
-- and "a bank asked" are different answers to that.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE valuation_requests (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    reference             VARCHAR(16)  NOT NULL UNIQUE,

    property_id           BIGINT       NOT NULL REFERENCES properties (id),
    property_reference    VARCHAR(16)  NOT NULL,
    property_title        VARCHAR(255),
    -- The asking price at the time. What the PI rule is measured against, and what a later reader compares
    -- the valuer's figure to.
    property_price        NUMERIC(15, 2),
    county                VARCHAR(64),

    -- Exactly one of these two. The CHECK below says so.
    tenant_id             BIGINT,
    tenant_name           VARCHAR(255),
    institution_id        BIGINT,
    institution_name      VARCHAR(255),

    purpose               VARCHAR(24)  NOT NULL DEFAULT 'SALE',
    state                 VARCHAR(16)  NOT NULL DEFAULT 'REQUESTED',

    -- The valuer, once there is one. Nullable because a request exists before anybody is assigned, and the
    -- gap between the two is the queue somebody works.
    valuer_profile_id     BIGINT REFERENCES valuer_profiles (id),
    valuer_name           VARCHAR(160),
    assigned_at           TIMESTAMPTZ,
    assigned_by_user_id   BIGINT,
    -- How the valuer was chosen: ROUND_ROBIN or MANUAL. Worth recording, because a manual override of an
    -- automatic panel is exactly the thing somebody asks about later.
    assignment_method     VARCHAR(16),

    due_on                DATE,
    fee_amount            NUMERIC(15, 2),
    currency              VARCHAR(3)   NOT NULL DEFAULT 'KES',
    requester_note        TEXT,

    declined_reason       TEXT,
    cancelled_reason      TEXT,
    completed_at          TIMESTAMPTZ,

    status                INTEGER      NOT NULL DEFAULT 1,
    status_flag           VARCHAR(32)  NOT NULL DEFAULT 'Active',

    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by            VARCHAR(64),
    updated_by            VARCHAR(64),

    CONSTRAINT ck_valuation_requester CHECK (
        (tenant_id IS NOT NULL)::int + (institution_id IS NOT NULL)::int = 1),
    CONSTRAINT ck_valuation_purpose
        CHECK (purpose IN ('SALE', 'MORTGAGE', 'INSURANCE', 'PROBATE', 'AUCTION')),
    CONSTRAINT ck_valuation_state
        CHECK (state IN ('REQUESTED', 'ASSIGNED', 'DECLINED', 'IN_PROGRESS', 'SUBMITTED',
                         'COMPLETED', 'CANCELLED')),
    -- Anything past REQUESTED has a valuer on it. The valuer's own list trusts the pair.
    CONSTRAINT ck_valuation_assigned
        CHECK (state IN ('REQUESTED', 'CANCELLED') OR valuer_profile_id IS NOT NULL)
);

CREATE INDEX idx_valuation_property ON valuation_requests (property_id);
CREATE INDEX idx_valuation_tenant ON valuation_requests (tenant_id) WHERE tenant_id IS NOT NULL;
CREATE INDEX idx_valuation_institution ON valuation_requests (institution_id)
    WHERE institution_id IS NOT NULL;
-- The assignment-scoped query: a valuer's own work. The index that makes §3.5's visibility rule cheap.
CREATE INDEX idx_valuation_valuer ON valuation_requests (valuer_profile_id, state)
    WHERE valuer_profile_id IS NOT NULL AND status <> 5;
-- The unassigned queue.
CREATE INDEX idx_valuation_waiting ON valuation_requests (created_at)
    WHERE state = 'REQUESTED' AND status <> 5;

ALTER TABLE valuation_requests ADD COLUMN search_text text
    GENERATED ALWAYS AS (
        lower(coalesce(reference, '') || ' ' || coalesce(property_reference, '') || ' ' ||
              coalesce(property_title, '') || ' ' || coalesce(tenant_name, '') || ' ' ||
              coalesce(institution_name, '') || ' ' || coalesce(valuer_name, '') || ' ' ||
              coalesce(state, ''))
    ) STORED;
CREATE INDEX idx_valuation_search_trgm ON valuation_requests USING gin (search_text gin_trgm_ops);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- The valuer's answer.
--
-- One row per request, written once and then read. The signed report itself is a vault document — it is
-- evidence a lender will rely on, and it belongs behind an ACL rather than on the media path.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE valuation_reports (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    request_id           BIGINT       NOT NULL REFERENCES valuation_requests (id),

    -- The two figures a Kenyan valuation carries. Forced sale is what a lender actually lends against.
    market_value         NUMERIC(15, 2) NOT NULL,
    forced_sale_value    NUMERIC(15, 2),
    insurance_value      NUMERIC(15, 2),
    currency             VARCHAR(3)   NOT NULL DEFAULT 'KES',

    -- How they got there. Not a free-text-only field, because "which method" is the first question anybody
    -- asks of a figure they disagree with.
    methodology          VARCHAR(32),
    inspected_on         DATE,
    condition_note       TEXT,
    assumptions          TEXT,
    comparables          TEXT,

    -- The signed PDF, in the vault. A reference rather than a foreign key for the same reason the offer's
    -- affordability reference is: the document's own lifecycle is not this row's business.
    document_reference   VARCHAR(16),

    submitted_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    submitted_by_user_id BIGINT,

    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by           VARCHAR(64),
    updated_by           VARCHAR(64),

    CONSTRAINT uk_valuation_report UNIQUE (request_id),
    CONSTRAINT ck_report_values CHECK (
        market_value > 0
        AND (forced_sale_value IS NULL OR forced_sale_value <= market_value)),
    CONSTRAINT ck_report_method CHECK (
        methodology IS NULL OR methodology IN
            ('COMPARABLE', 'INVESTMENT', 'COST', 'RESIDUAL', 'PROFITS'))
);

CREATE INDEX idx_report_request ON valuation_reports (request_id);
