-- ═════════════════════════════════════════════════════════════════════════════════════════════════
-- Booking a unit, and the money against it
--
-- <h2>Why not purchase_requests</h2>
--
-- That table's own migration header calls an offer "an expression of intent, not a contract", and its
-- uniqueness rule says so: `uk_purchase_live` is UNIQUE (user_id, property_id), which permits five buyers to
-- have live offers on the same property at once. That is correct for offers and exactly wrong for bookings —
-- a booked unit has one holder. The two rules cannot live in one table.
--
-- An offer may also be made by somebody with an account and nothing else; a booking carries a price, a
-- schedule and payments. So: a new table, and a purchase request that is accepted can point at the booking it
-- became through development_units.purchase_request_id, which already exists.
--
-- <h2>The one constraint the whole feature rests on</h2>
--
-- `uk_booking_live_unit` — one live booking per unit, enforced by a partial unique index.
--
-- Enforced by the *index* and not by the service, because two agents pressing Book in the same second is
-- precisely the race a service-level check loses: both read "available", both write, and the second overwrites
-- the first with nothing anywhere recording that it happened. A unique index makes the second one fail, and a
-- failed insert is a message the second agent can act on.
--
-- Partial rather than a table constraint: a unit whose booking was cancelled in March can be booked again in
-- June, and a buyer who cancelled is part of the record rather than a row to delete.
--
-- <h2>Balances are derived, never stored</h2>
--
-- There is no ledger in this system. A stored `paid_total` has no referee — nothing to reconcile it against —
-- so the first time it disagrees with the payments beneath it, there is no way to tell which is right. The
-- view at the bottom is the only place a balance is computed, and the raw-JDBC report paths get a column to
-- scope on.
--
-- <h2>Rescheduling writes a new plan</h2>
--
-- `booking_instalments.plan_no` rather than editing rows in place. The schedule a buyer agreed to in March
-- stays readable in June, which is the whole point of having agreed to it — and "we moved your dates" is a
-- conversation that needs both versions.
-- ═════════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE unit_bookings (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference           VARCHAR(16)  NOT NULL UNIQUE,

    development_id      BIGINT       NOT NULL REFERENCES developments (id),
    unit_id             BIGINT       NOT NULL REFERENCES development_units (id),
    -- Denormalised from the unit so a report can group by typology without a third join, and so the row still
    -- says what was booked if the unit is later moved between types.
    unit_type_id        BIGINT       REFERENCES development_unit_types (id),

    -- Who may see it, cached from the development. The same shape as media_assets: not exactly-one, because a
    -- platform-owned project has neither.
    tenant_id           BIGINT,
    institution_id      BIGINT,

    /*
     * The buyer, who may well not have an account.
     *
     * A bank's 2019 off-plan buyer has no login here and never will, so the name and the phone are the
     * identity and `buyer_user_id` is the bonus. The phone is NOT NULL because it is the only way to reach
     * somebody about a unit they are paying for over three years — and because it is what an inbound payment
     * is corroborated against when the reference alone is not enough.
     */
    buyer_user_id       BIGINT       REFERENCES users (id),
    buyer_name          VARCHAR(160) NOT NULL,
    buyer_phone         VARCHAR(32)  NOT NULL,
    buyer_email         VARCHAR(128),
    -- Kept because a developer's own paperwork asks for it. Masked in logs like every other identifier.
    buyer_id_number     VARCHAR(32),

    /*
     * RESERVED  — held, with a schedule, expiring
     * AGREED    — the buyer has committed; no longer expires
     * COMPLETED — paid up and handed over
     * CANCELLED — called off by either side, with a reason
     * LAPSED    — the reservation ran out and nobody renewed it
     *
     * LAPSED and CANCELLED are separate states because they are different facts: one is a decision and the
     * other is a clock. A single "closed" state would make "how many bookings do we lose to expiry" an
     * unanswerable question, and it is the first question anybody asks about a hold policy.
     */
    state               VARCHAR(24)  NOT NULL DEFAULT 'RESERVED',

    price_agreed        NUMERIC(15, 2),
    currency            VARCHAR(3)   NOT NULL DEFAULT 'KES',
    deposit_due         NUMERIC(15, 2),

    payment_plan        VARCHAR(24)  NOT NULL DEFAULT 'INSTALMENTS',

    booked_on           DATE         NOT NULL DEFAULT CURRENT_DATE,
    -- Null once AGREED: a commitment does not expire, and a column that kept counting down would be read as
    -- though it did.
    expires_at          TIMESTAMPTZ,
    agreed_at           TIMESTAMPTZ,
    completed_at        TIMESTAMPTZ,
    closed_at           TIMESTAMPTZ,
    close_reason        TEXT,

    notes               TEXT,

    status              INTEGER      NOT NULL DEFAULT 1,
    status_flag         VARCHAR(32)  NOT NULL DEFAULT 'Active',
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          VARCHAR(64),
    updated_by          VARCHAR(64),

    CONSTRAINT ck_booking_state CHECK (state IN
        ('RESERVED', 'AGREED', 'COMPLETED', 'CANCELLED', 'LAPSED')),
    CONSTRAINT ck_booking_plan CHECK (payment_plan IN ('LUMP_SUM', 'INSTALMENTS')),
    CONSTRAINT ck_booking_owner CHECK ((institution_id IS NULL) OR (tenant_id IS NULL)),
    CONSTRAINT ck_booking_money CHECK (
        (price_agreed IS NULL OR price_agreed >= 0)
        AND (deposit_due IS NULL OR deposit_due >= 0)),
    -- A reservation expires; the four states after it do not. Said here so the two cannot disagree.
    CONSTRAINT ck_booking_expiry CHECK (
        (state = 'RESERVED') OR (expires_at IS NULL)),
    CONSTRAINT ck_booking_closed CHECK (
        (state IN ('CANCELLED', 'LAPSED')) = (closed_at IS NOT NULL))
);

-- The constraint the feature rests on. See the header.
CREATE UNIQUE INDEX uk_booking_live_unit ON unit_bookings (unit_id)
    WHERE state IN ('RESERVED', 'AGREED') AND status <> 5;

CREATE INDEX idx_booking_development ON unit_bookings (development_id, booked_on DESC) WHERE status <> 5;
CREATE INDEX idx_booking_unit ON unit_bookings (unit_id, booked_on DESC) WHERE status <> 5;
CREATE INDEX idx_booking_tenant ON unit_bookings (tenant_id) WHERE tenant_id IS NOT NULL;
CREATE INDEX idx_booking_institution ON unit_bookings (institution_id) WHERE institution_id IS NOT NULL;
CREATE INDEX idx_booking_buyer ON unit_bookings (buyer_user_id) WHERE buyer_user_id IS NOT NULL;
-- The sweep's query: reservations already past their expiry. Partial, so it reads only the rows it can act on.
CREATE INDEX idx_booking_expiring ON unit_bookings (expires_at)
    WHERE state = 'RESERVED' AND status <> 5;

COMMENT ON COLUMN unit_bookings.buyer_phone IS
    'Mandatory: the buyer may have no account, and this is both how they are reached and how an inbound '
    'payment is corroborated when the four-character reference alone is not enough.';

-- ── the schedule ─────────────────────────────────────────────────────────────────────────────────

CREATE TABLE booking_instalments (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    booking_id          BIGINT       NOT NULL REFERENCES unit_bookings (id),

    /*
     * Which version of the schedule this row belongs to.
     *
     * Rescheduling writes plan 2 and leaves plan 1 alone, so the dates a buyer agreed to in March are still
     * readable in June. Only the highest live plan is the current one; the rest are history, which is why
     * this is a number rather than a boolean nobody could order.
     */
    plan_no             SMALLINT     NOT NULL DEFAULT 1,
    sequence_no         SMALLINT     NOT NULL,

    label               VARCHAR(120),
    due_on              DATE         NOT NULL,
    amount              NUMERIC(15, 2) NOT NULL,
    currency            VARCHAR(3)   NOT NULL DEFAULT 'KES',

    /*
     * There is no paid_total here, and that is deliberate.
     *
     * Payments are allocated against the booking, not against a row of its schedule — a buyer pays what they
     * pay, when they pay it, and rarely in the shape of the plan. Which instalments that settles is arithmetic
     * over the two lists, and arithmetic is cheaper to get right once than a denormalised figure is to keep
     * true in five places.
     */

    status              INTEGER      NOT NULL DEFAULT 1,
    status_flag         VARCHAR(32)  NOT NULL DEFAULT 'Active',
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          VARCHAR(64),
    updated_by          VARCHAR(64),

    CONSTRAINT ck_instalment_amount CHECK (amount >= 0),
    CONSTRAINT uk_instalment_slot UNIQUE (booking_id, plan_no, sequence_no)
);

CREATE INDEX idx_instalment_booking ON booking_instalments (booking_id, plan_no, sequence_no)
    WHERE status <> 5;
CREATE INDEX idx_instalment_due ON booking_instalments (due_on) WHERE status <> 5;

-- ── the money that actually arrived ──────────────────────────────────────────────────────────────

CREATE TABLE booking_payments (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference           VARCHAR(16)  NOT NULL UNIQUE,

    booking_id          BIGINT       NOT NULL REFERENCES unit_bookings (id),
    -- Cached from the booking so the reconciliation screen can scope without a join.
    tenant_id           BIGINT,
    institution_id      BIGINT,

    paid_on             DATE         NOT NULL DEFAULT CURRENT_DATE,
    amount              NUMERIC(15, 2) NOT NULL,
    currency            VARCHAR(3)   NOT NULL DEFAULT 'KES',

    /*
     * How it arrived. MANUAL covers the cheque, the RTGS transfer and the cash a bank actually reconciles,
     * and it is the path that ships first: it needs nobody's API key and it stays in production forever.
     * GATEWAY rows are written by an inbound notification, later.
     */
    source              VARCHAR(24)  NOT NULL DEFAULT 'MANUAL',
    method              VARCHAR(24)  NOT NULL DEFAULT 'BANK_TRANSFER',

    /* What the payer quoted — the unit's four-character code, when they got it right. */
    quoted_reference    VARCHAR(16),
    /* The bank's or the gateway's own reference, for tracing a disputed payment back to its source. */
    external_reference  VARCHAR(64),
    payer_name          VARCHAR(160),
    payer_phone         VARCHAR(32),

    /*
     * A payment is never edited or deleted; it is reversed by a second row with a negative amount, which is
     * why `amount` has no non-negative CHECK. Editing money that has already been reported to a buyer is how
     * a balance becomes unexplainable, and a reversal leaves both facts on the record.
     */
    reversal_of_id      BIGINT       REFERENCES booking_payments (id),
    reversal_reason     TEXT,

    notes               TEXT,

    status              INTEGER      NOT NULL DEFAULT 1,
    status_flag         VARCHAR(32)  NOT NULL DEFAULT 'Active',
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          VARCHAR(64),
    updated_by          VARCHAR(64),

    CONSTRAINT ck_payment_source CHECK (source IN ('MANUAL', 'GATEWAY')),
    CONSTRAINT ck_payment_method CHECK (method IN
        ('CASH', 'CHEQUE', 'BANK_TRANSFER', 'MOBILE_MONEY', 'CARD', 'OTHER')),
    CONSTRAINT ck_payment_owner CHECK ((institution_id IS NULL) OR (tenant_id IS NULL)),
    -- A reversal is negative and carries its reason; an ordinary payment is positive and carries neither.
    CONSTRAINT ck_payment_reversal CHECK (
        (reversal_of_id IS NULL AND amount > 0)
        OR (reversal_of_id IS NOT NULL AND amount < 0 AND reversal_reason IS NOT NULL))
);

CREATE INDEX idx_payment_booking ON booking_payments (booking_id, paid_on DESC) WHERE status <> 5;
CREATE INDEX idx_payment_tenant ON booking_payments (tenant_id, paid_on DESC) WHERE tenant_id IS NOT NULL;
CREATE INDEX idx_payment_quoted ON booking_payments (quoted_reference) WHERE quoted_reference IS NOT NULL;

-- ── the one place a balance is worked out ────────────────────────────────────────────────────────

/*
 * Everything owed and everything paid, per booking.
 *
 * A view rather than columns, because there is no ledger to reconcile a stored total against. It also gives
 * the raw-JDBC report paths a `tenant_id` to splice a scope predicate onto, which is the shape
 * TenantScope.sqlPredicate requires — an aggregate that cannot be scoped is where one developer reads
 * another's sales figures.
 *
 * `scheduled` is the current plan only: the highest plan number, so a rescheduled booking is measured against
 * what was last agreed rather than against every version ever written. `paid` sums reversals too, because a
 * reversal is a negative row and that is exactly the arithmetic wanted.
 */
CREATE VIEW v_booking_balances AS
SELECT b.id                                             AS booking_id,
       b.reference,
       b.development_id,
       b.unit_id,
       b.tenant_id,
       b.institution_id,
       b.state,
       b.currency,
       b.price_agreed,
       b.deposit_due,
       COALESCE(s.scheduled, 0)                         AS scheduled,
       COALESCE(p.paid, 0)                              AS paid,
       COALESCE(b.price_agreed, COALESCE(s.scheduled, 0)) - COALESCE(p.paid, 0) AS balance,
       s.next_due_on,
       -- What is due and unpaid *today*, which is the figure a chase list is ordered by.
       GREATEST(COALESCE(s.due_to_date, 0) - COALESCE(p.paid, 0), 0) AS overdue
  FROM unit_bookings b
  LEFT JOIN (
        SELECT i.booking_id,
               SUM(i.amount)                                                     AS scheduled,
               SUM(CASE WHEN i.due_on <= CURRENT_DATE THEN i.amount ELSE 0 END)   AS due_to_date,
               MIN(CASE WHEN i.due_on > CURRENT_DATE THEN i.due_on END)           AS next_due_on
          FROM booking_instalments i
         WHERE i.status <> 5
           AND i.plan_no = (SELECT MAX(i2.plan_no) FROM booking_instalments i2
                             WHERE i2.booking_id = i.booking_id AND i2.status <> 5)
         GROUP BY i.booking_id
  ) s ON s.booking_id = b.id
  LEFT JOIN (
        SELECT pay.booking_id, SUM(pay.amount) AS paid
          FROM booking_payments pay
         WHERE pay.status <> 5
         GROUP BY pay.booking_id
  ) p ON p.booking_id = b.id
 WHERE b.status <> 5;

COMMENT ON VIEW v_booking_balances IS
    'The only place a booking balance is computed. There is no ledger here, so a stored paid_total would '
    'have no referee — the first time it disagreed with the payments beneath it, nothing could say which '
    'was right.';
