-- pg_trgm's operator class, wherever the extension lives.
-- An extension exists once per database, in one schema, and on a shared server that schema is whichever
-- application installed it first — public on one machine, another application's schema on the next. Rather
-- than guess, look it up and put it on this transaction's search path; Flyway runs the whole script in one
-- transaction, so every gin_trgm_ops below resolves. Installs it into our own schema if nobody has yet.
DO $$
DECLARE ext_schema text;
BEGIN
    SELECT n.nspname INTO ext_schema
      FROM pg_extension e JOIN pg_namespace n ON n.oid = e.extnamespace
     WHERE e.extname = 'pg_trgm';
    IF ext_schema IS NULL THEN
        EXECUTE 'CREATE EXTENSION pg_trgm';
        ext_schema := current_schema();
    END IF;
    EXECUTE format('SET LOCAL search_path TO %I, %I', current_schema(), ext_schema);
END $$;

-- ═════════════════════════════════════════════════════════════════════════════════════════════════
-- Phase 4 / M9 — agents, and a signature that is evidence rather than decoration (BRD FR160–FR161, plan §3.4)
--
-- <h2>An agent is a one-person selling organisation</h2>
--
-- Plan §3.4 predicted "a third TenantScope mode: their own listings, plus client-owned listings where they
-- are the acting agent". Building it showed the platform already expresses that, and more cheaply.
--
-- `PrincipalFactory.resolveVisibleTenants` keys off `profile.tenant_id`, so an agent whose profile is bound
-- to their own organisation resolves to exactly their own rows with no new code at all. The alternative —
-- a third mode inside `TenantScope` — would have added a branch to the one class standing between two
-- organisations' data, to express something the existing branch already expresses. The agent's listings, own
-- and client-owned alike, are their organisation's rows; which of the two a listing is, is a column on it.
--
-- The limit of that, stated plainly: it models an agent acting for private clients, which is what FR160–161
-- describe. It does not model a seller organisation engaging an outside agent to sell rows the seller owns.
-- That is cross-organisation visibility and would need the partnership mechanism, not this one.
--
-- <h2>Why the signature is a table and not a column</h2>
--
-- FR161 wants a captured signature. A boolean "accepted terms" cannot answer the only question that ever
-- gets asked about one — *what exactly did they accept, and how do we know?* So the artifact records the
-- version, a SHA-256 of the terms text as it was served, the image, its own checksum, and the address and
-- user agent it arrived from. The hash is computed on the server from the configuration row; a client that
-- sends its own hash is sending an assertion, not evidence.
--
-- Both this table and the agreements are append-only by trigger, the same way `audit_logs` is. A signature
-- that can be updated is not evidence of anything.
-- ═════════════════════════════════════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- A fifth... sixth actor class. VALUER was the fifth; AGENT is the sixth, and the CHECKs enumerate them
-- deliberately so that adding one cannot happen by editing a Java enum alone.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
ALTER TABLE user_types DROP CONSTRAINT ck_user_types_actor_class;
ALTER TABLE user_types ADD CONSTRAINT ck_user_types_actor_class
    CHECK (actor_class IN ('PLATFORM', 'SELLER', 'LENDER', 'BUYER', 'VALUER', 'AGENT'));

ALTER TABLE user_profiles DROP CONSTRAINT ck_user_profiles_type;
ALTER TABLE user_profiles ADD CONSTRAINT ck_user_profiles_type
    CHECK (profile_type IN ('PLATFORM', 'SELLER', 'LENDER', 'BUYER', 'VALUER', 'AGENT'));

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- The signature.
--
-- Kept separate from `agent_profiles` because it outlives the thing it was captured for: an agent who
-- re-signs a new version of the terms produces a second artifact, and the first one must not be overwritten
-- by it. What was accepted on the day is the whole point.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE signature_artifacts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    reference       VARCHAR(16)  NOT NULL UNIQUE,
    user_id         BIGINT       NOT NULL REFERENCES users (id),
    profile_id      BIGINT       REFERENCES user_profiles (id),

    -- What was being signed. One value today; the column exists because the second one is coming (a seller's
    -- listing mandate, a buyer's offer) and retrofitting a discriminator onto evidence is worse than having
    -- one that is briefly constant.
    purpose         VARCHAR(32)  NOT NULL,

    -- DRAWN carries an image; TYPED carries a name the signer keyed in and nothing else. Both are signatures
    -- in the sense the law uses; only one of them is a picture.
    signature_kind  VARCHAR(16)  NOT NULL,
    typed_name      VARCHAR(160),

    -- The image lives in the vault, never the ordinary media store: it is a specimen of somebody's hand.
    storage_key     VARCHAR(512),
    content_type    VARCHAR(128),
    size_bytes      BIGINT,
    checksum_sha256 VARCHAR(64),
    encryption      VARCHAR(32),

    -- What they accepted, and proof of it. `terms_sha256` is computed server-side over the exact text served.
    terms_version   VARCHAR(32)  NOT NULL,
    terms_sha256    VARCHAR(64)  NOT NULL,

    captured_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    ip_address      VARCHAR(64),
    user_agent      TEXT,

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      VARCHAR(64),

    CONSTRAINT ck_signature_kind CHECK (signature_kind IN ('DRAWN', 'TYPED')),
    CONSTRAINT ck_signature_drawn CHECK (signature_kind <> 'DRAWN' OR storage_key IS NOT NULL),
    CONSTRAINT ck_signature_typed CHECK (signature_kind <> 'TYPED' OR typed_name IS NOT NULL)
);

CREATE INDEX idx_signature_user ON signature_artifacts (user_id, captured_at DESC);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- The agent.
--
-- `tenant_id` is null while the application is pending and set at approval, which is also when the
-- one-person organisation is created. An agent who is never approved never gets an organisation, and so
-- never has anywhere to put a listing — the gate is structural as well as permission-based.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE agent_profiles (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    reference          VARCHAR(16)  NOT NULL UNIQUE,
    user_id            BIGINT       NOT NULL REFERENCES users (id),
    profile_id         BIGINT       NOT NULL REFERENCES user_profiles (id),

    -- Set at approval. Null means "no organisation yet", which is exactly true of a pending application.
    tenant_id          BIGINT       REFERENCES tenants (id),

    full_name          VARCHAR(160) NOT NULL,
    email              VARCHAR(128),
    phone              VARCHAR(32),

    -- FR160: registers independently. Self-employed agents have no agency; the rest must name one.
    self_employed      BOOLEAN      NOT NULL DEFAULT true,
    agency_name        VARCHAR(255),

    id_number          VARCHAR(64),
    licence_number     VARCHAR(64),
    licence_expires_on DATE,
    counties           TEXT,
    bio                TEXT,

    state              VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    decided_at         TIMESTAMPTZ,
    decided_by_user_id BIGINT,
    decision_note      TEXT,

    -- The signature that came with the application, and the agreement generated on approval.
    signature_id       BIGINT       REFERENCES signature_artifacts (id),
    agreement_id       BIGINT,

    status             INTEGER      NOT NULL DEFAULT 1,
    status_flag        VARCHAR(32)  NOT NULL DEFAULT 'Active',

    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by         VARCHAR(64),
    updated_by         VARCHAR(64),

    CONSTRAINT uk_agent_profile UNIQUE (profile_id),
    CONSTRAINT ck_agent_state CHECK (state IN ('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED')),
    -- An agency agent without an agency name is an application nobody can assess.
    CONSTRAINT ck_agent_agency CHECK (self_employed OR agency_name IS NOT NULL),
    -- Approval is three things at once, and a row that has only some of them is a half-approval nobody can
    -- act on: an organisation to list into, an agreement, and a decision with a time on it.
    CONSTRAINT ck_agent_approved CHECK (
        state <> 'APPROVED'
        OR (tenant_id IS NOT NULL AND agreement_id IS NOT NULL AND decided_at IS NOT NULL)),
    CONSTRAINT ck_agent_decided CHECK (state <> 'REJECTED' OR decided_at IS NOT NULL)
);

CREATE INDEX idx_agent_state ON agent_profiles (state, created_at DESC);
CREATE INDEX idx_agent_tenant ON agent_profiles (tenant_id) WHERE tenant_id IS NOT NULL;
CREATE INDEX idx_agent_user ON agent_profiles (user_id);

ALTER TABLE agent_profiles ADD COLUMN search_text text
    GENERATED ALWAYS AS (
        lower(coalesce(reference, '') || ' ' || coalesce(full_name, '') || ' ' ||
              coalesce(agency_name, '') || ' ' || coalesce(email, '') || ' ' ||
              coalesce(phone, '') || ' ' || coalesce(licence_number, '') || ' ' ||
              coalesce(counties, '') || ' ' || coalesce(state, ''))
    ) STORED;
CREATE INDEX idx_agent_search_trgm ON agent_profiles USING gin (search_text gin_trgm_ops);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- The agreement.
--
-- Plan §3.4 calls this `listing_agreement`. It is named for what it is: an agreement between the platform
-- and the agent covering everything they list, generated once at approval — not a per-listing mandate. The
-- per-listing fact FR161 asks for is the ownership flag on `properties` below, which is a different thing
-- and belongs where it is used.
--
-- The body is stored as text rather than as a rendered PDF. The agreement *is* text; keeping it as text
-- makes it searchable, diffable and readable without a viewer, and its SHA-256 pins what was generated.
-- Rendering it to a document is a presentation concern and can be added without changing what is recorded.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE agent_agreements (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    reference        VARCHAR(16)  NOT NULL UNIQUE,
    agent_profile_id BIGINT       NOT NULL REFERENCES agent_profiles (id),
    signature_id     BIGINT       REFERENCES signature_artifacts (id),

    terms_version    VARCHAR(32)  NOT NULL,
    terms_sha256     VARCHAR(64)  NOT NULL,

    body             TEXT         NOT NULL,
    body_sha256      VARCHAR(64)  NOT NULL,

    effective_from   DATE         NOT NULL DEFAULT CURRENT_DATE,
    generated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    generated_by     VARCHAR(64)
);

CREATE INDEX idx_agreement_agent ON agent_agreements (agent_profile_id, generated_at DESC);

ALTER TABLE agent_profiles
    ADD CONSTRAINT fk_agent_agreement FOREIGN KEY (agreement_id) REFERENCES agent_agreements (id);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- Evidence does not change.
--
-- The same guard `audit_logs` carries, for the same reason: a signature or an executed agreement that can be
-- edited afterwards proves nothing about the day it was made. Superseding one means writing another.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION agent_evidence_append_only() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION '% is append-only: rows may not be % once written', TG_TABLE_NAME, lower(TG_OP);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_signature_immutable
    BEFORE UPDATE OR DELETE ON signature_artifacts
    FOR EACH ROW EXECUTE FUNCTION agent_evidence_append_only();

CREATE TRIGGER trg_agreement_immutable
    BEFORE UPDATE OR DELETE ON agent_agreements
    FOR EACH ROW EXECUTE FUNCTION agent_evidence_append_only();

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- FR161: every listing says whose it is.
--
-- On `properties` rather than in a join table, because it is a fact about the listing that every screen
-- showing a listing needs, and because a listing has exactly one answer. The client's name and number are
-- personal data belonging to somebody who never signed up to this platform: they are on the private listing
-- record only, and the public one has no field for them at all.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
ALTER TABLE properties
    ADD COLUMN agent_profile_id   BIGINT REFERENCES agent_profiles (id),
    ADD COLUMN listing_ownership  VARCHAR(16),
    ADD COLUMN client_owner_name  VARCHAR(160),
    ADD COLUMN client_owner_phone VARCHAR(32);

ALTER TABLE properties
    ADD CONSTRAINT ck_property_ownership
        CHECK (listing_ownership IS NULL OR listing_ownership IN ('SELF', 'CLIENT')),
    -- An agent's listing must say which it is. A seller organisation's listing needs no answer, and null is
    -- the honest one rather than a defaulted 'SELF' that would read as a claim nobody made.
    ADD CONSTRAINT ck_property_agent_ownership
        CHECK (agent_profile_id IS NULL OR listing_ownership IS NOT NULL),
    ADD CONSTRAINT ck_property_client_named
        CHECK (listing_ownership IS DISTINCT FROM 'CLIENT' OR client_owner_name IS NOT NULL);

CREATE INDEX idx_property_agent ON properties (agent_profile_id) WHERE agent_profile_id IS NOT NULL;

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- The modules an approved agent works in.
--
-- `allowed_user_types` is not re-seeded once a row exists — it is the super admin's to edit at runtime — so
-- the enum defaults alone would only reach databases created after this deploy. Appended rather than
-- rewritten, and only where the row still matches what the platform shipped.
--
-- Note what is NOT widened: KYC. An agent's clearance is their approval — the platform has just examined a
-- licence, an identity document and a signed agreement — and routing them through the seller pack as well
-- would be asking the same person for the same things twice.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
UPDATE app_modules
SET allowed_user_types = allowed_user_types || ',AGENT',
    updated_at         = now(),
    updated_by         = 'system'
WHERE code IN ('DASHBOARD', 'PROPERTIES', 'ENQUIRIES', 'SITE_VISITS', 'PURCHASE_REQUESTS',
               'VALUATIONS', 'MORTGAGE_PRODUCTS')
  -- Token-precise, not a substring: the CSV already contains SALES_AGENT, and a LIKE '%AGENT%' here would
  -- match it and silently skip every row this migration exists to change.
  AND ',' || allowed_user_types || ',' NOT LIKE '%,AGENT,%';
