-- A walkthrough video, held as the provider's id rather than the link somebody pasted.
--
-- The link is a dozen shapes for one video (watch?v=, youtu.be, shorts, a timestamp on the end); the id is
-- one. Storing the id is also what keeps an arbitrary URL out of a column that is later put inside an iframe.
--
-- One table for three owners, inherited on read the way photographs are: a house owns its tour, a typology
-- card and its units share the show unit's, and the project's flythrough is on every listing in it. PROPERTY
-- is an owner here although media_assets refuses it — that refusal exists only because property_media came
-- first, and there is no older tours table to defer to.
CREATE TABLE virtual_tours (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_type          VARCHAR(32)  NOT NULL,
    owner_id            BIGINT       NOT NULL,

    -- Cached from the owner, as on media_assets: exactly one, or neither for a platform-owned project.
    tenant_id           BIGINT,
    institution_id      BIGINT,

    -- A column rather than an assumption, so a second provider is an adapter and not a migration.
    provider            VARCHAR(16)  NOT NULL DEFAULT 'YOUTUBE',
    video_id            VARCHAR(32)  NOT NULL,
    title               VARCHAR(160),
    start_seconds       INTEGER      NOT NULL DEFAULT 0,

    -- The rooms, as [{"seconds": 72, "label": "Kitchen"}, …] in ascending order. Read with the tour and
    -- never queried into, so a document rather than a child table.
    chapters            JSONB        NOT NULL DEFAULT '[]'::jsonb,

    sort_order          INTEGER      NOT NULL DEFAULT 0,

    status              INTEGER      NOT NULL DEFAULT 1,
    status_flag         VARCHAR(32)  NOT NULL DEFAULT 'Active',
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          VARCHAR(64),
    updated_by          VARCHAR(64),

    CONSTRAINT ck_tour_owner_type CHECK (owner_type IN ('PROPERTY', 'UNIT_TYPE', 'DEVELOPMENT')),
    CONSTRAINT ck_tour_provider CHECK (provider IN ('YOUTUBE')),
    -- YouTube's ids are eleven characters of this alphabet. The check is the last line, not the first: the
    -- parser refuses anything else long before it gets here.
    CONSTRAINT ck_tour_video_id CHECK (provider <> 'YOUTUBE' OR video_id ~ '^[A-Za-z0-9_-]{11}$'),
    CONSTRAINT ck_tour_start CHECK (start_seconds >= 0),
    CONSTRAINT ck_tour_owner CHECK ((institution_id IS NULL) OR (tenant_id IS NULL))
);

CREATE INDEX idx_tour_owner ON virtual_tours (owner_type, owner_id, sort_order) WHERE status <> 5;
-- The same video twice on one owner is a mistake, not a choice: the second copy would be a second tab
-- playing the same thing.
CREATE UNIQUE INDEX uk_tour_owner_video ON virtual_tours (owner_type, owner_id, provider, video_id)
    WHERE status <> 5;
CREATE INDEX idx_tour_tenant ON virtual_tours (tenant_id) WHERE tenant_id IS NOT NULL;
