-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- An applicant's documents, before there is an organisation to hang them on.
--
-- The compliance pack was the obvious home and cannot be: KycService.openPack refuses a profile with no
-- tenant ("KYC applies to seller organisations"), and an applicant has none until the bank approves them
-- — which is precisely the decision the documents are meant to inform. The pack is right for a seller who
-- already exists and is renewing; it cannot serve the person becoming one.
--
-- So the application carries its own, and only the join is new. The files go into the same vault through
-- DocumentService.store, which is what keeps the SHA-256, the per-document ACL and the audited read —
-- a second writer would lose all three, and the vault is the one subsystem where "platform sees all"
-- deliberately does not hold.
--
-- store() already accepts a null tenant for "a document about a person", which is exactly an applicant.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────

CREATE TABLE seller_application_documents (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id   BIGINT       NOT NULL REFERENCES seller_applications (id) ON DELETE CASCADE,
    -- The vault row. Not a storage key: reads go through DocumentService so they are ACL-checked.
    document_id      BIGINT       NOT NULL,
    -- Which line of the checklist this answers — ID, KRA PIN, CR12 and the rest live in
    -- kyc_requirement_configs and are already versioned per seller type.
    document_code    VARCHAR(64)  NOT NULL,
    original_name    VARCHAR(255),
    uploaded_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    status           INTEGER      NOT NULL DEFAULT 1,
    status_flag      VARCHAR(32)  NOT NULL DEFAULT 'Active',
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by       VARCHAR(64),
    updated_by       VARCHAR(64)
);

-- One live document per line. Re-uploading replaces rather than accumulating, because a checklist with
-- two answers to the same question is a reviewer asking which one counts.
CREATE UNIQUE INDEX uk_seller_app_doc ON seller_application_documents (application_id, document_code)
    WHERE status <> 5;
CREATE INDEX idx_seller_app_doc ON seller_application_documents (application_id);
