-- ═════════════════════════════════════════════════════════════════════════════════════════════════
-- Phase 2 / M8, second slice — seller types become real, and listings report progress
--
-- Two things the first slice left open.
--
-- <h2>1. Nothing made KYC mandatory</h2>
--
-- The gate works — §13 proved it — but a seller who never opened a pack stayed at NOT_REQUIRED, which
-- clears it. The missing piece was never machinery; it was the policy statement of *when* clearance becomes
-- a precondition. That is now a configuration row naming the seller types it applies to, applied at the
-- moment a seller type is set rather than re-derived on every permission resolution.
--
-- Existing sellers are untouched: every `tenants.seller_type` is currently null, so nobody's rights change
-- under them. The type becomes required at onboarding from here on, which is also what makes the KYC
-- checklist answerable — a pack cannot know what to ask for without knowing what kind of seller it is about.
--
-- <h2>2. Off-plan property has nothing to say between listing and completion</h2>
--
-- The BRD's progress updates (FR087–FR089). A buyer who has paid a deposit on an unbuilt apartment wants to
-- see the slab go down. These are public marketing posts, not vault documents — they go through the ordinary
-- media store, and the distinction is the point of having two.
-- ═════════════════════════════════════════════════════════════════════════════════════════════════

-- The seller type stops being free text. A CHECK rather than a lookup table: six values that change about
-- once a decade do not need a table, and a CHECK is the only form that a bad row cannot get past.
ALTER TABLE tenants ADD CONSTRAINT ck_tenant_seller_type
    CHECK (seller_type IS NULL OR seller_type IN
        ('INDIVIDUAL', 'COMPANY', 'SACCO', 'DEVELOPER', 'AGENCY', 'GOVERNMENT'));

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- Progress updates on a listing.
--
-- Ordered by `reported_on` rather than by creation: a developer catching up on three months of photographs
-- in one sitting should produce a timeline in the order the work happened, not the order it was typed.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE listing_progress_updates (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    property_id       BIGINT       NOT NULL REFERENCES properties (id),
    tenant_id         BIGINT       NOT NULL,

    title             VARCHAR(180) NOT NULL,
    body              TEXT,
    -- Where the build has got to. A figure and a name for the stage, because "60%" and "roofing" answer
    -- different questions and a buyer asks both.
    percent_complete  SMALLINT,
    milestone         VARCHAR(64),

    -- When the work happened, not when the post was written.
    reported_on       DATE         NOT NULL DEFAULT CURRENT_DATE,

    -- One photograph, through the ordinary media store: this is marketing, not evidence, and it belongs on
    -- the same public path as the listing's own pictures rather than behind the vault.
    image_key         VARCHAR(512),

    -- Drafted, then shown. A developer writing three updates on a Friday should not publish the first two
    -- half-finished.
    published         BOOLEAN      NOT NULL DEFAULT false,
    published_at      TIMESTAMPTZ,

    status            INTEGER      NOT NULL DEFAULT 1,
    status_flag       VARCHAR(32)  NOT NULL DEFAULT 'Active',

    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by        VARCHAR(64),
    updated_by        VARCHAR(64),

    CONSTRAINT ck_progress_percent
        CHECK (percent_complete IS NULL OR (percent_complete >= 0 AND percent_complete <= 100)),
    CONSTRAINT ck_progress_published CHECK (published = false OR published_at IS NOT NULL)
);

CREATE INDEX idx_progress_property ON listing_progress_updates (property_id, reported_on DESC);
CREATE INDEX idx_progress_tenant ON listing_progress_updates (tenant_id);
-- What a buyer sees on the listing: published, newest first.
CREATE INDEX idx_progress_public ON listing_progress_updates (property_id, reported_on DESC)
    WHERE published AND status <> 5;
