-- ═════════════════════════════════════════════════════════════════════════════════════════════════
-- Payment types, payment accounts, and payments
--
-- See claudedocs/PAYMENTS_AND_PAYMENT_TYPES_PLAN.md. The short version: this platform already had the
-- first half of this feature under other names — `pesi_super_types` was a catalogue of channels with no
-- cash, no cheque and no flags; `pesi_payment_methods` was an account with an owner and nothing else; and
-- `booking_payments` was money against a booking with no receipt page, no channel and no list. This
-- migration completes the three rather than adding a second copy of each.
--
-- <h2>Two tables for where money lands, and the split is the design</h2>
--
-- A channel is a fact about a gateway ("KCB takes till credits"); an account is a fact about an
-- organisation ("ours is 7654321"). Collapsing them would have every developer re-describing M-Pesa, and
-- the catalogue row is what decides which fields an account must carry.
--
-- <h2>Void, not reversal</h2>
--
-- `booking_payments` corrected a payment with a second, negative row. A receipt is a record of what a
-- buyer was told, and a void with a reason beside it is a fresh fact rather than an edit — and a payments
-- list reads far better without negative receipts in it. Existing reversal pairs are folded: the original
-- becomes voided carrying the reversal's reason, by and when; the reversal row is archived. Status 4 is
-- this platform's INACTIVE, so every `status <> 5` guard in the codebase still means what it did.
--
-- <h2>The account identifier stays the inbound match key</h2>
--
-- The Pesi notification names the till it landed in, and that is resolved against `account_no` — which is
-- why `account_no` stays unique across live rows. `short_code` is kept as an optional secondary reference
-- the handler falls back to, not as the key.
-- ═════════════════════════════════════════════════════════════════════════════════════════════════

-- ── 1. The catalogue ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE payment_types (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    /*
     * A stable name for the row. Configuration and screens refer to a channel by this, never by the
     * autoincrement id, so adding a channel renumbers nobody.
     */
    code                VARCHAR(40)  NOT NULL UNIQUE,
    name                VARCHAR(120) NOT NULL,
    description         VARCHAR(250),
    -- Who runs the rails: Safaricom, KCB, Co-operative Bank. Display only; there is no banks table here.
    provider_name       VARCHAR(120),

    -- Pesi's discriminator. Null for cash and cheque, the two channels with no gateway behind them.
    pesi_provider_type  VARCHAR(50),

    /*
     * CASH | CHEQUE | STK_PUSH | TRANSFER | VALIDATE — what the channel *is*, and therefore how it behaves.
     * Stored so a query can classify without re-deriving it from the provider string.
     */
    category            VARCHAR(16)  NOT NULL,

    /*
     * The coarse method a payment through this channel records. A column rather than a switch in Java:
     * choosing "Lipa na KCB" on the receive form must not be recordable as a cheque, and the channel is
     * the one place that knows what it amounts to.
     */
    method              VARCHAR(24)  NOT NULL,

    -- What the form must ask for. Stored rather than derived because the form is a different question.
    is_electronic       BOOLEAN      NOT NULL DEFAULT false,
    is_account_based    BOOLEAN      NOT NULL DEFAULT false,
    requires_short_code BOOLEAN      NOT NULL DEFAULT false,

    sort_order          INTEGER      NOT NULL DEFAULT 0,
    status              INTEGER      NOT NULL DEFAULT 1,
    status_flag         VARCHAR(32)  NOT NULL DEFAULT 'Active',
    search_text         TEXT GENERATED ALWAYS AS (
        lower(coalesce(name, '') || ' ' || coalesce(code, '') || ' ' || coalesce(provider_name, '')
              || ' ' || coalesce(description, ''))
    ) STORED,

    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          VARCHAR(64),
    updated_by          VARCHAR(64),

    CONSTRAINT ck_payment_type_category CHECK (category IN
        ('CASH', 'CHEQUE', 'STK_PUSH', 'TRANSFER', 'VALIDATE')),
    CONSTRAINT ck_payment_type_method CHECK (method IN
        ('CASH', 'CHEQUE', 'BANK_TRANSFER', 'MOBILE_MONEY', 'CARD', 'OTHER')),
    -- A gateway channel without a provider cannot reach the gateway; a manual one must not claim to.
    CONSTRAINT ck_payment_type_provider CHECK (
        (category IN ('CASH', 'CHEQUE') AND pesi_provider_type IS NULL)
        OR (category NOT IN ('CASH', 'CHEQUE') AND pesi_provider_type IS NOT NULL)),
    -- Only an outbound channel can be started from the app.
    CONSTRAINT ck_payment_type_electronic CHECK (
        NOT is_electronic OR category IN ('STK_PUSH', 'TRANSFER'))
);

CREATE UNIQUE INDEX uk_payment_type_pesi ON payment_types (pesi_provider_type)
    WHERE pesi_provider_type IS NOT NULL;
CREATE INDEX idx_payment_types_order ON payment_types (sort_order) WHERE status <> 5;
CREATE INDEX idx_payment_types_search ON payment_types USING gin (search_text public.gin_trgm_ops);

/*
 * The channels. Cash and cheque are on, because they need nothing configured to work. Everything with a
 * gateway behind it arrives INACTIVE (4): a channel offered before anybody has an account on it is a
 * payment method that fails at the till. The STK channels stay off until an outbound Pesi client exists.
 */
INSERT INTO payment_types (code, name, description, provider_name, pesi_provider_type, category, method,
                           is_electronic, is_account_based, requires_short_code, sort_order,
                           status, status_flag, created_by)
VALUES
    ('CASH', 'Cash', 'Received by hand and receipted.',
     NULL, NULL, 'CASH', 'CASH', false, false, false, 1, 1, 'Active', 'migration'),
    ('CHEQUE', 'Cheque', 'Banked by the organisation; recorded against its number.',
     NULL, NULL, 'CHEQUE', 'CHEQUE', false, false, false, 2, 1, 'Active', 'migration'),

    ('MPESA_STK', 'M-Pesa STK Push', 'Safaricom prompts the buyer''s phone.',
     'Safaricom', 'DARAJA_STK_PUSH', 'STK_PUSH', 'MOBILE_MONEY', true, true, false, 3, 4, 'Inactive',
     'migration'),
    ('MPESA_C2B', 'M-Pesa Paybill or Till', 'The buyer pays the paybill; the credit arrives on its own.',
     'Safaricom', 'DARAJA_C2B', 'VALIDATE', 'MOBILE_MONEY', false, true, true, 4, 4, 'Inactive',
     'migration'),

    ('KCB_STK', 'Lipa na KCB', 'KCB prompts the buyer''s phone.',
     'KCB', 'BUNI_STK_PUSH', 'STK_PUSH', 'MOBILE_MONEY', true, true, false, 5, 4, 'Inactive', 'migration'),
    ('KCB_IPN_TILL', 'KCB Till', 'The buyer pays a KCB till; the credit arrives on its own.',
     'KCB', 'BUNI_IPN_TILL', 'VALIDATE', 'BANK_TRANSFER', false, true, true, 6, 4, 'Inactive', 'migration'),
    ('KCB_IPN_ACCOUNT', 'KCB Account', 'The buyer pays into a KCB account; the credit arrives on its own.',
     'KCB', 'BUNI_IPN_ACCOUNT', 'VALIDATE', 'BANK_TRANSFER', false, true, true, 7, 4, 'Inactive',
     'migration'),
    ('KCB_FT', 'KCB Funds Transfer', 'Outbound transfer, started by staff.',
     'KCB', 'BUNI_FT', 'TRANSFER', 'BANK_TRANSFER', true, true, false, 8, 4, 'Inactive', 'migration'),

    ('COOP_STK', 'Co-op Bank STK Push', 'Co-operative Bank prompts the buyer''s phone.',
     'Co-operative Bank', 'COOP_BANK_STK_PUSH', 'STK_PUSH', 'MOBILE_MONEY', true, true, false, 9, 4,
     'Inactive', 'migration'),
    ('COOP_IPN_ACCOUNT', 'Co-op Bank Account',
     'The buyer pays into a Co-op account; the credit arrives on its own.',
     'Co-operative Bank', 'COOP_BANK_IPN_ACCOUNT', 'VALIDATE', 'BANK_TRANSFER', false, true, true, 10, 4,
     'Inactive', 'migration'),
    ('COOP_BILLER_B2B', 'Co-op Bank Biller', 'Co-op biller credits, validated by reference.',
     'Co-operative Bank', 'COOP_BILLER_B2B', 'VALIDATE', 'BANK_TRANSFER', false, true, true, 11, 4,
     'Inactive', 'migration'),

    ('EQUITY_IPN', 'Equity Account', 'The buyer pays into an Equity account; the credit arrives on its own.',
     'Equity Bank', 'EQUITY_IPN', 'VALIDATE', 'BANK_TRANSFER', false, true, true, 12, 4, 'Inactive',
     'migration');

-- A channel somebody already collects on stays on: switching it off would withdraw a live till.
UPDATE payment_types t
   SET status = 1, status_flag = 'Active'
 WHERE EXISTS (SELECT 1
                 FROM pesi_payment_methods m
                 JOIN pesi_super_types s ON s.id = m.super_type_id
                WHERE s.code = t.pesi_provider_type
                  AND m.status <> 5);

-- ── 2. The accounts ──────────────────────────────────────────────────────────────────────────────

CREATE TABLE payment_accounts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_type_id     BIGINT       NOT NULL REFERENCES payment_types (id),

    /*
     * Whose money lands here. Exactly one, or neither for the platform's own account — the same shape as
     * every other owner pair in this schema, and the reason a lending institution can collect on a
     * development it financed without being a tenant.
     */
    tenant_id           BIGINT       REFERENCES tenants (id),
    institution_id      BIGINT       REFERENCES lending_institutions (id),

    -- One development, or null for every development the owner has.
    development_id      BIGINT       REFERENCES developments (id),

    pay_bill_no         VARCHAR(32),
    /*
     * Null only for cash and cheque, and the CHECK below says so. A mandatory column here is how a live
     * system ends up with the literal string "HODI" in every STK row — typed to get past a field that
     * channel has no use for.
     */
    account_no          VARCHAR(64),
    account_name        VARCHAR(160),
    /*
     * A secondary reference the bank may quote on its notifications. Optional here: the Pesi contract this
     * platform speaks names the account itself, and that is the key. Unique when present so a fallback
     * match can never land on two accounts.
     */
    short_code          VARCHAR(64),

    -- Copied from the catalogue row so an inbound match is one table and one index.
    pesi_type           VARCHAR(50),
    category            VARCHAR(16)  NOT NULL,

    status              INTEGER      NOT NULL DEFAULT 1,
    status_flag         VARCHAR(32)  NOT NULL DEFAULT 'Active',
    search_text         TEXT GENERATED ALWAYS AS (
        lower(coalesce(account_no, '') || ' ' || coalesce(account_name, '') || ' '
              || coalesce(short_code, '') || ' ' || coalesce(pay_bill_no, ''))
    ) STORED,

    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          VARCHAR(64),
    updated_by          VARCHAR(64),

    CONSTRAINT ck_payment_account_owner CHECK ((tenant_id IS NULL) OR (institution_id IS NULL)),
    CONSTRAINT ck_payment_account_category CHECK (category IN
        ('CASH', 'CHEQUE', 'STK_PUSH', 'TRANSFER', 'VALIDATE')),
    -- An account-based channel carries both halves of the account; a manual one carries neither.
    CONSTRAINT ck_payment_account_fields CHECK (
        (category IN ('CASH', 'CHEQUE') AND account_no IS NULL AND account_name IS NULL)
        OR (category NOT IN ('CASH', 'CHEQUE')
            AND account_no IS NOT NULL AND length(btrim(account_no)) > 0
            AND account_name IS NOT NULL AND length(btrim(account_name)) > 0))
);

-- The inbound match key. Two live rows claiming one till would make whose money it is depend on row order.
CREATE UNIQUE INDEX uk_payment_account_no ON payment_accounts (account_no)
    WHERE account_no IS NOT NULL AND status <> 5;
CREATE UNIQUE INDEX uk_payment_account_short_code ON payment_accounts (short_code)
    WHERE short_code IS NOT NULL AND status <> 5;
-- Cash and cheque once per owner and development. A gateway channel may be configured repeatedly — an
-- organisation really does hold several accounts on one bank — and the index above keeps those apart.
CREATE UNIQUE INDEX uk_payment_account_manual
    ON payment_accounts (coalesce(tenant_id, 0), coalesce(institution_id, 0), payment_type_id,
                         coalesce(development_id, 0))
    WHERE category IN ('CASH', 'CHEQUE') AND status <> 5;

CREATE INDEX idx_payment_account_tenant ON payment_accounts (tenant_id) WHERE tenant_id IS NOT NULL;
CREATE INDEX idx_payment_account_institution ON payment_accounts (institution_id)
    WHERE institution_id IS NOT NULL;
CREATE INDEX idx_payment_account_type ON payment_accounts (payment_type_id, status);
CREATE INDEX idx_payment_account_search ON payment_accounts USING gin (search_text public.gin_trgm_ops);

/*
 * The tills already registered move across with their ids, so the statements that point at them keep
 * pointing at the right row. Every Pesi code the old catalogue held is seeded above, so nothing is lost
 * in the join.
 */
INSERT INTO payment_accounts (id, payment_type_id, tenant_id, institution_id, development_id,
                              account_no, account_name, pesi_type, category,
                              status, status_flag, created_at, updated_at, created_by, updated_by)
SELECT m.id, t.id, m.tenant_id, m.institution_id, NULL,
       m.account_number, m.account_name, t.pesi_provider_type, t.category,
       m.status, m.status_flag, m.created_at, m.updated_at, m.created_by, m.updated_by
  FROM pesi_payment_methods m
  JOIN pesi_super_types s ON s.id = m.super_type_id
  JOIN payment_types t ON t.pesi_provider_type = s.code;

SELECT setval(pg_get_serial_sequence('payment_accounts', 'id'),
              COALESCE((SELECT max(id) FROM payment_accounts), 0) + 1, false);

-- The statements now name the account rather than the method.
ALTER TABLE pesi_statements DROP CONSTRAINT pesi_statements_payment_method_id_fkey;
ALTER TABLE pesi_statements RENAME COLUMN payment_method_id TO payment_account_id;
ALTER TABLE pesi_statements
    ADD CONSTRAINT fk_pesi_statement_account FOREIGN KEY (payment_account_id)
        REFERENCES payment_accounts (id);

DROP TABLE pesi_payment_methods;
DROP TABLE pesi_super_types;

-- ── 3. Payments ──────────────────────────────────────────────────────────────────────────────────

ALTER TABLE booking_payments RENAME TO payments;

ALTER TABLE payments
    -- Cached from the booking, so the list and the receipt read one table. A receipt printed today must
    -- still read the same after a unit is relabelled or a buyer's name is corrected.
    ADD COLUMN development_id    BIGINT REFERENCES developments (id),
    ADD COLUMN unit_id           BIGINT REFERENCES development_units (id),
    ADD COLUMN development_name  VARCHAR(255),
    ADD COLUMN unit_label        VARCHAR(32),
    ADD COLUMN buyer_name        VARCHAR(160),
    ADD COLUMN buyer_phone       VARCHAR(32),
    /*
     * The configured account this came through, where it came through one — beside `method`, not
     * instead of it. The method is what the system did with the money; this is what a person calls it.
     * The name is copied so a receipt still reads the same after the catalogue row is renamed.
     */
    ADD COLUMN payment_type_id   BIGINT REFERENCES payment_types (id),
    ADD COLUMN payment_type_name VARCHAR(120),
    /*
     * What the booking owed immediately before and after. Both stored, neither derived: `after + amount`
     * is wrong the moment the payment is voided and the balance recomputed, and a receipt states what was
     * true when it was issued.
     */
    ADD COLUMN balance_before    NUMERIC(15, 2),
    ADD COLUMN balance_after     NUMERIC(15, 2),
    ADD COLUMN voided_at         TIMESTAMPTZ,
    ADD COLUMN voided_by         VARCHAR(64),
    ADD COLUMN void_reason       TEXT,
    -- The bank credit behind it, where there was one. Null for anything keyed in by hand.
    ADD COLUMN statement_id      BIGINT REFERENCES pesi_statements (id);

UPDATE payments p
   SET development_id = b.development_id,
       unit_id        = b.unit_id,
       buyer_name     = b.buyer_name,
       buyer_phone    = b.buyer_phone
  FROM unit_bookings b
 WHERE b.id = p.booking_id;

UPDATE payments p SET development_name = d.name FROM developments d WHERE d.id = p.development_id;
UPDATE payments p SET unit_label = u.unit_label FROM development_units u WHERE u.id = p.unit_id;

UPDATE payments p SET statement_id = s.id FROM pesi_statements s WHERE s.mapped_payment_id = p.id;

UPDATE payments p
   SET payment_type_id   = a.payment_type_id,
       payment_type_name = t.name
  FROM pesi_statements s
  JOIN payment_accounts a ON a.id = s.payment_account_id
  JOIN payment_types t ON t.id = a.payment_type_id
 WHERE s.id = p.statement_id;

/*
 * Reversals become voids. The original carries what the reversal said — why, who and when — and the
 * reversal row is archived rather than deleted: this schema keeps every row, and everything the reversal
 * knew now sits on the payment it corrected.
 */
UPDATE payments o
   SET status      = 4,
       status_flag = 'Inactive',
       voided_at   = r.created_at,
       voided_by   = r.created_by,
       void_reason = r.reversal_reason,
       updated_at  = now(),
       updated_by  = 'migration'
  FROM payments r
 WHERE r.reversal_of_id = o.id
   AND r.status <> 5;

UPDATE payments
   SET status = 5, status_flag = 'Deleted', updated_at = now(), updated_by = 'migration'
 WHERE reversal_of_id IS NOT NULL;

ALTER TABLE payments DROP CONSTRAINT ck_payment_reversal;
ALTER TABLE payments DROP COLUMN reversal_of_id;
ALTER TABLE payments DROP COLUMN reversal_reason;

ALTER TABLE payments ALTER COLUMN development_id SET NOT NULL;

ALTER TABLE payments
    -- 1 received, 4 voided, 5 archived. Received and voided is the whole life of a payment.
    ADD CONSTRAINT ck_payment_status CHECK (status IN (1, 4, 5)),
    -- A payment of nothing settles nothing. Archived reversal rows are the only negatives left.
    ADD CONSTRAINT ck_payment_amount CHECK (status = 5 OR amount > 0),
    ADD CONSTRAINT ck_payment_void CHECK (
        status <> 4 OR (voided_at IS NOT NULL AND void_reason IS NOT NULL));

ALTER TABLE payments ADD COLUMN search_text TEXT GENERATED ALWAYS AS (
    lower(coalesce(reference, '')          || ' ' ||
          coalesce(external_reference, '') || ' ' ||
          coalesce(quoted_reference, '')   || ' ' ||
          coalesce(payer_name, '')         || ' ' ||
          coalesce(payer_phone, '')        || ' ' ||
          coalesce(buyer_name, '')         || ' ' ||
          coalesce(unit_label, '')         || ' ' ||
          coalesce(development_name, '')   || ' ' ||
          coalesce(payment_type_name, ''))
) STORED;

CREATE INDEX idx_payments_search ON payments USING gin (search_text public.gin_trgm_ops);
CREATE INDEX idx_payments_development ON payments (development_id, paid_on DESC) WHERE status <> 5;
CREATE INDEX idx_payments_institution ON payments (institution_id, paid_on DESC)
    WHERE institution_id IS NOT NULL;
CREATE INDEX idx_payments_type ON payments (payment_type_id) WHERE status = 1;

COMMENT ON TABLE payments IS
    'Money received against a booking. Never edited: a wrong payment is voided with a reason and the row '
    'stays, because a receipt is a record of what a buyer was told.';

-- The receive form finds a booking by what somebody has in front of them: the reference, or the buyer.
ALTER TABLE unit_bookings ADD COLUMN search_text TEXT GENERATED ALWAYS AS (
    lower(coalesce(reference, '') || ' ' || coalesce(buyer_name, '') || ' ' ||
          coalesce(buyer_phone, '') || ' ' || coalesce(buyer_email, ''))
) STORED;
CREATE INDEX idx_booking_search ON unit_bookings USING gin (search_text public.gin_trgm_ops);

-- ── 4. The views: received money only ────────────────────────────────────────────────────────────

CREATE OR REPLACE VIEW v_booking_balances AS
SELECT b.id                                             AS booking_id,
       b.reference,
       b.development_id,
       b.unit_id,
       b.tenant_id,
       b.institution_id,
       b.state,
       b.currency,
       b.price_agreed,
       b.deposit_due,
       COALESCE(s.scheduled, 0)                         AS scheduled,
       COALESCE(p.paid, 0)                              AS paid,
       COALESCE(b.price_agreed, COALESCE(s.scheduled, 0)) - COALESCE(p.paid, 0) AS balance,
       s.next_due_on,
       GREATEST(COALESCE(s.due_to_date, 0) - COALESCE(p.paid, 0), 0) AS overdue
  FROM unit_bookings b
  LEFT JOIN (
        SELECT i.booking_id,
               SUM(i.amount)                                                     AS scheduled,
               SUM(CASE WHEN i.due_on <= CURRENT_DATE THEN i.amount ELSE 0 END)   AS due_to_date,
               MIN(CASE WHEN i.due_on > CURRENT_DATE THEN i.due_on END)           AS next_due_on
          FROM booking_instalments i
         WHERE i.status <> 5
           AND i.plan_no = (SELECT MAX(i2.plan_no) FROM booking_instalments i2
                             WHERE i2.booking_id = i.booking_id AND i2.status <> 5)
         GROUP BY i.booking_id
  ) s ON s.booking_id = b.id
  LEFT JOIN (
        -- Received only. A voided payment is history, not money.
        SELECT pay.booking_id, SUM(pay.amount) AS paid
          FROM payments pay
         WHERE pay.status = 1
         GROUP BY pay.booking_id
  ) p ON p.booking_id = b.id
 WHERE b.status <> 5;

CREATE OR REPLACE VIEW v_chart_payments_by_month AS
SELECT p.tenant_id,
       p.institution_id,
       date_trunc('month', p.paid_on)::date AS bucket,
       'Received'                           AS series,
       sum(p.amount)                        AS value
  FROM payments p
 WHERE p.status = 1
 GROUP BY 1, 2, 3;

-- ── 5. Housekeeping ──────────────────────────────────────────────────────────────────────────────

-- Recording money is the payments module's act now. The seeder creates PAYMENTS_RECEIVE and PAYMENTS_VOID
-- at boot; the old code is retired here so it does not linger as a permission nothing checks.
DELETE FROM user_group_permissions
 WHERE permission_id IN (SELECT id FROM permissions WHERE action_code = 'BOOKINGS_PAYMENTS');
UPDATE permissions
   SET status = 5, status_flag = 'Deleted', updated_at = now(), updated_by = 'migration'
 WHERE action_code = 'BOOKINGS_PAYMENTS';

-- Changing where money lands is confirmed by a code texted to the organisation, so the code table gains
-- the purpose.
ALTER TABLE otp_challenges DROP CONSTRAINT ck_otp_purpose;
ALTER TABLE otp_challenges ADD CONSTRAINT ck_otp_purpose
    CHECK (purpose IN ('LOGIN', 'EMAIL_VERIFY', 'PHONE_VERIFY', 'PAYMENT_ACCOUNT'));
