-- A booking is made under terms the buyer agreed to.
--
-- Everything that can cost the buyer money — the hold and when it lapses, the deposit, the plan, what a
-- refund keeps back, that a cancellation is final — is told to them before they commit, and their answer
-- is kept. The terms are one page: a versioned template at the platform, filled with the live figures of
-- any booking or listing. What acceptance keeps is the version and the figures, so a later change to the
-- rate or the wording does not rewrite what was agreed.

-- ── the policy, per development; null means the platform default ──────────────────────────────────────
ALTER TABLE developments
    ADD COLUMN refund_penalty_basis              VARCHAR(20),
    ADD COLUMN refund_penalty_rate               NUMERIC(15, 3),
    ADD COLUMN refund_penalty_cap                NUMERIC(15, 2),
    ADD COLUMN refund_penalty_bank_share_percent NUMERIC(6, 3),
    ADD COLUMN refund_within_days                INTEGER,
    ADD COLUMN revive_within_days                INTEGER,
    ADD COLUMN booking_policy_note               TEXT;

ALTER TABLE developments
    ADD CONSTRAINT ck_dev_refund_penalty_basis CHECK (refund_penalty_basis IS NULL
        OR refund_penalty_basis IN ('PERCENT_OF_PAID', 'PERCENT_OF_DEPOSIT', 'FIXED'));

-- ── the template: one page, versioned ─────────────────────────────────────────────────────────────────
CREATE TABLE booking_terms_templates (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version     INTEGER      NOT NULL UNIQUE,
    body        TEXT         NOT NULL,
    note        VARCHAR(255),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(64)
);

INSERT INTO booking_terms_templates (version, body, note, created_by) VALUES (1, $body$
## The home and the price

You are booking {{home}} from {{seller}} at {{price}}. The deposit due to hold it is {{deposit}}, and the balance is paid {{plan}}.

## The hold

Your booking holds the home for {{holdDays}} days, until {{expiresOn}}. It is confirmed the moment your first payment lands. If nothing is paid by then, the booking lapses and the home goes back on the market. A lapsed booking can be revived within {{reviveWindow}} of lapsing, as long as nobody else has booked the home.

## If you change your mind

You may ask for a refund of what you have paid within {{refundWindow}} of the booking closing. {{penalty}} The refund is paid to an account you provide, after the seller's checker and the bank have approved it.

## Cancellation

A cancellation by the seller or by you, once agreed, ends this booking for good. Money already paid is refunded under the rule above; the home is released and a new booking is a new agreement.

## What the seller says

{{policyNote}}

## Your agreement

By accepting, you confirm that you have read these terms and agree to them. You can read them again at any time on your booking.
$body$, 'The platform''s first booking terms', 'system');

-- ── what each booking was agreed under ────────────────────────────────────────────────────────────────
CREATE TABLE booking_terms (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id        BIGINT       NOT NULL REFERENCES unit_bookings (id),
    template_version  INTEGER      NOT NULL REFERENCES booking_terms_templates (version),
    -- The figures the template was filled with that day: price, deposit, plan, hold, penalty, windows, note.
    figures           JSONB        NOT NULL,
    presented_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    accepted_at       TIMESTAMPTZ,
    declined_at       TIMESTAMPTZ,
    decline_reason    TEXT,
    -- PORTAL: the buyer, signed in. PAPER: the sales office, with the signed form in the vault.
    channel           VARCHAR(8),
    decided_by_user_id BIGINT,
    decided_by_name   VARCHAR(160),
    -- The signed form, when accepted on paper.
    document_id       BIGINT REFERENCES vault_documents (id),
    -- A buyer confirming in the portal what they had signed on paper.
    confirmed_at      TIMESTAMPTZ,
    superseded_at     TIMESTAMPTZ,
    created_by        VARCHAR(64)
);
CREATE INDEX idx_booking_terms_booking ON booking_terms (booking_id, presented_at DESC);

-- NONE: made before terms existed, or a completed sale recorded by hand. PRESENTED: waiting for the
-- buyer. ACCEPTED, DECLINED: their answer.
ALTER TABLE unit_bookings
    ADD COLUMN terms_state             VARCHAR(10) NOT NULL DEFAULT 'NONE',
    ADD COLUMN expiry_reminder_sent_at TIMESTAMPTZ;

ALTER TABLE unit_bookings
    ADD CONSTRAINT ck_booking_terms_state CHECK (terms_state IN ('NONE', 'PRESENTED', 'ACCEPTED', 'DECLINED'));
