-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- Hodi Market Place — access-management baseline.
--
-- One schema. Unlike axis, there is no master/tenant split and no per-tenant schema: the marketplace
-- search spans every seller, so isolation is a tenant_id column plus the TenantScope choke point
-- rather than a search_path (plan section 1, section 11 deviation 1).
--
-- Naming: VYYYYMMDDHHmmSS__description.sql. Never V1/V2 — sequential integers collide the moment two
-- branches add a migration in parallel, and the collision surfaces as a boot failure rather than as
-- two adjacent files.
--
-- Conventions in every table below:
--   * bigint identity PKs. Ids are HashId-encoded on the wire, never exposed raw.
--   * status (int) + status_flag (varchar) soft lifecycle. No hard deletes; status = 5 is archived.
--   * created_at/by + updated_at/by on anything editable; append-only tables omit the update pair.
--   * timestamptz throughout, stored UTC.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- user_types — global; the platform owns this catalogue (plan section 4.2)
--
-- actor_class is the column that separates the four populations. It is stored rather than derived
-- because platform staff and buyers both carry no organisation: "tenant_id IS NULL AND
-- institution_id IS NULL" describes two entirely different kinds of user, and the inference that gets
-- it wrong is the one that hands a buyer platform access.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE user_types (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                VARCHAR(32)  NOT NULL UNIQUE,
    name                VARCHAR(64)  NOT NULL,
    description         TEXT,
    actor_class         VARCHAR(16)  NOT NULL,
    sort_order          INTEGER      NOT NULL DEFAULT 0,
    status              INTEGER      NOT NULL DEFAULT 1,
    status_flag         VARCHAR(32)  NOT NULL DEFAULT 'Active',
    deactivation_reason TEXT,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          VARCHAR(64),
    updated_by          VARCHAR(64),
    CONSTRAINT ck_user_types_actor_class
        CHECK (actor_class IN ('PLATFORM', 'SELLER', 'LENDER', 'BUYER'))
);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- app_modules — access axis (1)
--
-- allowed_user_types is a CSV of user_types.code, and it is ENFORCED, not advisory. It must never
-- become a SQL predicate: `allowed_user_types LIKE '%ADMIN%'` also matches SUPER_ADMIN and
-- LENDER_ADMIN, and all three codes exist. AppModule.allows() splits and compares exact tokens over
-- a set that is tens of rows long; see plan section 4.2.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE app_modules (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                VARCHAR(64)  NOT NULL UNIQUE,
    name                VARCHAR(128) NOT NULL,
    description         TEXT,
    allowed_user_types  VARCHAR(512),
    is_core             BOOLEAN      NOT NULL DEFAULT false,
    sort_order          INTEGER      NOT NULL DEFAULT 0,
    status              INTEGER      NOT NULL DEFAULT 1,
    status_flag         VARCHAR(32)  NOT NULL DEFAULT 'Active',
    deactivation_reason TEXT,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          VARCHAR(64),
    updated_by          VARCHAR(64)
);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- permissions — the {MODULE}_{ACTION} catalogue, seeded from AppPermissionEnum
--
-- platform_only is a column rather than a check in the seeder because BOTH things that hand out
-- permissions have to honour it — the role templates and the organisation system-group top-up — and a
-- rule living in one of them is a rule the other will break.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE permissions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_code   VARCHAR(64)  NOT NULL UNIQUE,
    action_name   VARCHAR(255) NOT NULL,
    app_module_id BIGINT       NOT NULL REFERENCES app_modules (id),
    module_code   VARCHAR(64)  NOT NULL,
    module_name   VARCHAR(128),
    platform_only BOOLEAN      NOT NULL DEFAULT false,
    status        INTEGER      NOT NULL DEFAULT 1,
    status_flag   VARCHAR(32)  NOT NULL DEFAULT 'Active',
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by    VARCHAR(64),
    updated_by    VARCHAR(64)
);
CREATE INDEX idx_permissions_module ON permissions (module_code);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- tenants — SELLER organisations. The only kind of tenant.
--
-- Note the absences: no schema_name, no provision_status, no domain. There is no schema to create and
-- no host to resolve, so onboarding is an insert plus a module top-up and cannot half-fail — which is
-- why the whole provisioning state machine axis needs is not here (plan section 11, deviations 1-2).
--
-- onboarding_status is the business lifecycle and is deliberately separate from the soft `status`
-- lifecycle. They answer different questions: status is whether the row is in force, onboarding_status
-- is whether the business may trade. A suspended seller is a live row whose staff cannot sign in.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE tenants (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(255) NOT NULL,
    slug                VARCHAR(128) NOT NULL UNIQUE,
    tenant_ref          VARCHAR(16)  NOT NULL UNIQUE,
    seller_type         VARCHAR(32),
    contact_name        VARCHAR(128),
    contact_email       VARCHAR(128),
    contact_phone       VARCHAR(32),
    country             VARCHAR(2),
    currency            VARCHAR(3)   NOT NULL DEFAULT 'KES',
    timezone            VARCHAR(64)  NOT NULL DEFAULT 'Africa/Nairobi',
    onboarding_status   VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    activated_at        TIMESTAMPTZ,
    suspended_at        TIMESTAMPTZ,
    suspension_reason   TEXT,
    terminated_at       TIMESTAMPTZ,
    status              INTEGER      NOT NULL DEFAULT 1,
    status_flag         VARCHAR(32)  NOT NULL DEFAULT 'Active',
    deactivation_reason TEXT,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          VARCHAR(64),
    updated_by          VARCHAR(64),
    CONSTRAINT ck_tenants_onboarding
        CHECK (onboarding_status IN ('PENDING', 'ACTIVE', 'SUSPENDED', 'TERMINATED')),
    -- Lower-case, because the slug is the local part of this seller's outbound email identity and
    -- half the comparisons against it would otherwise be case-sensitive by accident.
    CONSTRAINT ck_tenants_slug_lower CHECK (slug = lower(slug))
);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- lending_institutions — banks, SACCOs, MFIs. NOT tenants.
--
-- An institution's staff read OTHER organisations' rows; that is the job. Modelling them as tenants
-- would have meant either no cross-organisation visibility (useless) or a blanket exemption from
-- tenant scoping (a hole shaped exactly like the thing scoping prevents). The agreement is
-- tenant_lender_partnerships below.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE lending_institutions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(255) NOT NULL,
    slug                VARCHAR(128) NOT NULL UNIQUE,
    institution_ref     VARCHAR(16)  NOT NULL UNIQUE,
    institution_type    VARCHAR(16)  NOT NULL,
    licence_number      VARCHAR(64),
    contact_name        VARCHAR(128),
    contact_email       VARCHAR(128),
    contact_phone       VARCHAR(32),
    country             VARCHAR(2),
    status              INTEGER      NOT NULL DEFAULT 1,
    status_flag         VARCHAR(32)  NOT NULL DEFAULT 'Active',
    deactivation_reason TEXT,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          VARCHAR(64),
    updated_by          VARCHAR(64),
    CONSTRAINT ck_institutions_type
        CHECK (institution_type IN ('BANK', 'SACCO', 'MFI', 'INSURER', 'OTHER')),
    CONSTRAINT ck_institutions_slug_lower CHECK (slug = lower(slug))
);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- tenant_lender_partnerships — the WHOLE of a lender's read access
--
-- Nothing else widens it: a lender's staff resolve to the tenant ids with an active row here for
-- their institution, and to nothing otherwise. That makes "who may see this seller's data" a SELECT
-- against one table rather than a walk through permissions.
--
-- The lifecycle is explicit rather than a boolean because an approval is the moment somebody decided
-- another organisation's staff may read this one's rows — not a fact to overwrite. Revocation is
-- recorded rather than deleted: a row that vanishes cannot answer "who used to have access, until
-- when, and who took it away".
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE tenant_lender_partnerships (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id            BIGINT      NOT NULL REFERENCES tenants (id),
    institution_id       BIGINT      NOT NULL REFERENCES lending_institutions (id),
    tenant_name          VARCHAR(255),
    institution_name     VARCHAR(255),
    portfolio_scope      VARCHAR(16) NOT NULL DEFAULT 'FULL',
    requested_by_side    VARCHAR(16) NOT NULL,
    requested_by_user_id BIGINT,
    requested_at         TIMESTAMPTZ,
    approved_by_user_id  BIGINT,
    approved_at          TIMESTAMPTZ,
    revoked_by_user_id   BIGINT,
    revoked_at           TIMESTAMPTZ,
    revoke_reason        TEXT,
    status               INTEGER     NOT NULL DEFAULT 1,
    status_flag          VARCHAR(32) NOT NULL DEFAULT 'Active',
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by           VARCHAR(64),
    updated_by           VARCHAR(64),
    CONSTRAINT uk_partnership UNIQUE (tenant_id, institution_id),
    CONSTRAINT ck_partnership_scope CHECK (portfolio_scope IN ('FULL', 'SELECTED')),
    CONSTRAINT ck_partnership_side CHECK (requested_by_side IN ('SELLER', 'LENDER', 'PLATFORM'))
);

-- The index behind PrincipalFactory's hottest query: resolving a lender user's visible-tenant set on
-- every principal build. Partial, because only active rows are ever asked for — a revoked or pending
-- partnership grants nothing, so there is no reason to carry it in the index.
CREATE INDEX idx_partnership_active_by_institution
    ON tenant_lender_partnerships (institution_id, tenant_id)
    WHERE approved_at IS NOT NULL AND revoked_at IS NULL AND status <> 5;

CREATE INDEX idx_partnership_by_tenant ON tenant_lender_partnerships (tenant_id);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- user_groups — roles as arbitrary permission bundles (access axis 2)
--
-- Three flavours, told apart by the two organisation columns: both null + is_template is a cloneable
-- global template; both null without it is a platform role; one set means that organisation owns it.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE user_groups (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(128) NOT NULL,
    description         TEXT,
    user_type_id        BIGINT       NOT NULL REFERENCES user_types (id),
    user_type_code      VARCHAR(32)  NOT NULL,
    user_type_name      VARCHAR(64),
    tenant_id           BIGINT       REFERENCES tenants (id),
    institution_id      BIGINT       REFERENCES lending_institutions (id),
    is_template         BOOLEAN      NOT NULL DEFAULT false,
    is_system           BOOLEAN      NOT NULL DEFAULT false,
    status              INTEGER      NOT NULL DEFAULT 1,
    status_flag         VARCHAR(32)  NOT NULL DEFAULT 'Active',
    deactivation_reason TEXT,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          VARCHAR(64),
    updated_by          VARCHAR(64),
    -- A group belongs to at most one organisation. Both set would make "whose group is this" have two
    -- answers, and every visibility decision downstream would have to pick one.
    CONSTRAINT ck_user_groups_one_org
        CHECK (tenant_id IS NULL OR institution_id IS NULL)
);
CREATE INDEX idx_user_groups_tenant ON user_groups (tenant_id);
CREATE INDEX idx_user_groups_institution ON user_groups (institution_id);
CREATE INDEX idx_user_groups_type ON user_groups (user_type_code);

CREATE TABLE user_group_permissions (
    user_group_id BIGINT NOT NULL REFERENCES user_groups (id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES permissions (id) ON DELETE CASCADE,
    PRIMARY KEY (user_group_id, permission_id)
);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- users — every person who can sign in: platform staff, seller staff, lender staff and buyers
--
-- One identity table for all four populations. A separate buyer table would have meant two login
-- pipelines, two password policies, two session models, and two places to remember to check whether
-- an account is locked. What differs between them is not how they authenticate but what they may
-- reach, and that is actor_class plus permissions.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE users (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name           VARCHAR(64)  NOT NULL,
    last_name            VARCHAR(64)  NOT NULL,
    email                VARCHAR(128) NOT NULL UNIQUE,
    username             VARCHAR(64)  NOT NULL UNIQUE,
    phone                VARCHAR(32),
    password             VARCHAR(128) NOT NULL,
    user_group_id        BIGINT       REFERENCES user_groups (id),
    user_group_name      VARCHAR(128),
    user_type_id         BIGINT       NOT NULL REFERENCES user_types (id),
    user_type_code       VARCHAR(32)  NOT NULL,
    user_type_name       VARCHAR(64),
    actor_class          VARCHAR(16)  NOT NULL,
    tenant_id            BIGINT       REFERENCES tenants (id),
    tenant_name          VARCHAR(255),
    institution_id       BIGINT       REFERENCES lending_institutions (id),
    institution_name     VARCHAR(255),
    avatar_key           VARCHAR(512),
    totp_enabled         BOOLEAN      NOT NULL DEFAULT false,
    totp_secret          VARCHAR(255),
    totp_confirmed_at    TIMESTAMPTZ,
    sms_otp_enabled      BOOLEAN      NOT NULL DEFAULT false,
    locked               BOOLEAN      NOT NULL DEFAULT false,
    locked_until         TIMESTAMPTZ,
    failed_attempts      INTEGER      NOT NULL DEFAULT 0,
    enabled              BOOLEAN      NOT NULL DEFAULT true,
    must_change_password BOOLEAN      NOT NULL DEFAULT false,
    last_login           TIMESTAMPTZ,
    username_changeable  BOOLEAN      NOT NULL DEFAULT false,
    password_changed_at  TIMESTAMPTZ,
    password_expires_at  TIMESTAMPTZ,
    email_verified_at    TIMESTAMPTZ,
    phone_verified_at    TIMESTAMPTZ,
    status               INTEGER      NOT NULL DEFAULT 1,
    status_flag          VARCHAR(32)  NOT NULL DEFAULT 'Active',
    deactivation_reason  TEXT,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by           VARCHAR(64),
    updated_by           VARCHAR(64),
    -- At most one organisation. Enforced here rather than only in the service because it is the
    -- invariant every visibility decision downstream is built on.
    CONSTRAINT ck_users_one_org CHECK (tenant_id IS NULL OR institution_id IS NULL),
    -- Lower-case email, enforced by the database so the service cannot forget. Login accepts either
    -- username or email, and a case-sensitive comparison here would make that lookup miss.
    CONSTRAINT ck_users_email_lower CHECK (email = lower(email)),
    CONSTRAINT ck_users_actor_class
        CHECK (actor_class IN ('PLATFORM', 'SELLER', 'LENDER', 'BUYER'))
);
CREATE INDEX idx_users_tenant ON users (tenant_id);
CREATE INDEX idx_users_institution ON users (institution_id);
CREATE INDEX idx_users_group ON users (user_group_id);
CREATE INDEX idx_users_actor_class ON users (actor_class);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- tenant_modules — access axis (1), seller side
--
-- A row exists for every enabled module, core ones included, so that "enabled" is always a row rather
-- than sometimes a row and sometimes an inference from app_modules.is_core. Two ways to be enabled is
-- one too many: EffectivePermissionResolver asks this table and nothing else.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE tenant_modules (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT      NOT NULL REFERENCES tenants (id),
    app_module_id BIGINT      NOT NULL REFERENCES app_modules (id),
    module_code   VARCHAR(64) NOT NULL,
    module_name   VARCHAR(128),
    enabled_at    TIMESTAMPTZ,
    disabled_at   TIMESTAMPTZ,
    status        INTEGER     NOT NULL DEFAULT 1,
    status_flag   VARCHAR(32) NOT NULL DEFAULT 'Active',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by    VARCHAR(64),
    updated_by    VARCHAR(64),
    CONSTRAINT uk_tenant_module UNIQUE (tenant_id, app_module_id)
);
CREATE INDEX idx_tenant_modules_lookup ON tenant_modules (tenant_id, module_code) WHERE status <> 5;

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- refresh_tokens — one row per session; the server half of the sliding idle window (plan section 5)
--
-- expires_at is the idle window plus a small grace, NOT a long fixed lifetime. That inversion is what
-- makes the window real: an unused token dies on its own, and rotation on every use is what lets an
-- active client keep pushing the deadline forward. Only the SHA-256 hash is stored, so a stolen
-- database yields no usable sessions.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE refresh_tokens (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jti           VARCHAR(32)  NOT NULL UNIQUE,
    token_hash    VARCHAR(64)  NOT NULL UNIQUE,
    user_id       BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    session_class VARCHAR(16)  NOT NULL,
    expires_at    TIMESTAMPTZ  NOT NULL,
    revoked       BOOLEAN      NOT NULL DEFAULT false,
    revoked_at    TIMESTAMPTZ,
    replaced_by   VARCHAR(32),
    user_agent    VARCHAR(512),
    ip_address    VARCHAR(64),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_refresh_session_class CHECK (session_class IN ('ADMIN', 'BUYER'))
);
CREATE INDEX idx_refresh_user ON refresh_tokens (user_id);
CREATE INDEX idx_refresh_expiry ON refresh_tokens (expires_at);

CREATE TABLE password_history (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    password   VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_password_history_user ON password_history (user_id, created_at DESC);

CREATE TABLE password_reset_tokens (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    code_hash    VARCHAR(64) NOT NULL UNIQUE,
    expires_at   TIMESTAMPTZ NOT NULL,
    used_at      TIMESTAMPTZ,
    requested_ip VARCHAR(64),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_password_reset_user ON password_reset_tokens (user_id);

-- One table for login challenges and buyer verification, because they are the same mechanism — issue
-- a code, tie it to a purpose and a user, count wrong guesses, expire it. Two tables would mean two
-- places to get the attempt counting wrong. `purpose` keeps them from being interchangeable.
CREATE TABLE otp_challenges (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    challenge_token VARCHAR(64)  NOT NULL UNIQUE,
    user_id         BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    purpose         VARCHAR(24)  NOT NULL,
    channel         VARCHAR(16)  NOT NULL,
    code_hash       VARCHAR(64),
    sent_to_masked  VARCHAR(128),
    attempts        INTEGER      NOT NULL DEFAULT 0,
    expires_at      TIMESTAMPTZ  NOT NULL,
    consumed_at     TIMESTAMPTZ,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_otp_purpose CHECK (purpose IN ('LOGIN', 'EMAIL_VERIFY', 'PHONE_VERIFY')),
    CONSTRAINT ck_otp_channel CHECK (channel IN ('TOTP', 'SMS', 'EMAIL'))
);
CREATE INDEX idx_otp_user_purpose ON otp_challenges (user_id, purpose);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- configurations — global by default, tenant override by exception (plan section 6)
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE configurations (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key     VARCHAR(128) NOT NULL UNIQUE,
    config_value   TEXT,
    value_type     VARCHAR(16)  NOT NULL DEFAULT 'STRING',
    category       VARCHAR(64)  NOT NULL DEFAULT 'GENERAL',
    label          VARCHAR(255),
    description    TEXT,
    is_secret      BOOLEAN      NOT NULL DEFAULT false,
    is_overridable BOOLEAN      NOT NULL DEFAULT false,
    editable       BOOLEAN      NOT NULL DEFAULT true,
    status         INTEGER      NOT NULL DEFAULT 1,
    status_flag    VARCHAR(32)  NOT NULL DEFAULT 'Active',
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by     VARCHAR(64),
    updated_by     VARCHAR(64)
);
CREATE INDEX idx_configurations_category ON configurations (category);

-- Sparse: a row exists ONLY where a seller has deliberately shadowed a global value. Clearing an
-- override deletes the row rather than writing the global value into it — copying the global down
-- would freeze it, so a later platform-wide change would silently stop reaching this organisation.
--
-- Uniqueness is (tenant_id, config_key), not config_key alone. Under axis's schema-per-tenant the key
-- alone sufficed because the table itself was per-tenant; here a unique index on the key alone would
-- let the first seller to override a key stop every other seller from doing so.
CREATE TABLE tenant_configurations (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    BIGINT       NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    config_key   VARCHAR(128) NOT NULL,
    config_value TEXT,
    value_type   VARCHAR(16)  NOT NULL DEFAULT 'STRING',
    category     VARCHAR(64)  NOT NULL DEFAULT 'GENERAL',
    is_secret    BOOLEAN      NOT NULL DEFAULT false,
    status       INTEGER      NOT NULL DEFAULT 1,
    status_flag  VARCHAR(32)  NOT NULL DEFAULT 'Active',
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by   VARCHAR(64),
    updated_by   VARCHAR(64),
    CONSTRAINT uk_tenant_config UNIQUE (tenant_id, config_key)
);

-- Append-only: a change log entry is a statement about the past, and a past that can be deactivated
-- is not much of a log. Secret values are stored MASKED — the log's job is to say that the gateway key
-- changed and who changed it, not to become a second unencrypted copy of every credential.
CREATE TABLE configuration_logs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key     VARCHAR(128) NOT NULL,
    scope          VARCHAR(16)  NOT NULL,
    tenant_id      BIGINT,
    tenant_name    VARCHAR(255),
    previous_value TEXT,
    new_value      TEXT,
    reason         TEXT,
    actor_username VARCHAR(64)  NOT NULL,
    actor_ip       VARCHAR(64),
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_config_log_scope CHECK (scope IN ('GLOBAL', 'TENANT'))
);
CREATE INDEX idx_config_log_key_time ON configuration_logs (config_key, created_at DESC);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- audit_logs — append-only; no status or updated_* columns by design
--
-- tenant_id is a soft reference with NO foreign key, deliberately: audit must survive the organisation
-- it describes. Terminating a seller cannot be allowed to erase the record of what their staff did,
-- which is also why actor_username is denormalised rather than joined — the user row may be gone.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE audit_logs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_id       VARCHAR(64),
    tenant_id       BIGINT,
    actor_user_id   BIGINT,
    actor_username  VARCHAR(64),
    actor_user_type VARCHAR(32),
    actor_class     VARCHAR(16),
    institution_id  BIGINT,
    operation       VARCHAR(64)  NOT NULL,
    entity          VARCHAR(128),
    entity_id       BIGINT,
    outcome         VARCHAR(32)  NOT NULL DEFAULT 'SUCCESS',
    before_payload  JSONB,
    after_payload   JSONB,
    changed_fields  JSONB,
    ip_address      VARCHAR(64),
    user_agent      VARCHAR(512),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_audit_tenant_time ON audit_logs (tenant_id, created_at DESC);
CREATE INDEX idx_audit_entity ON audit_logs (entity, entity_id);
CREATE INDEX idx_audit_actor ON audit_logs (actor_user_id, created_at DESC);
