-- ═════════════════════════════════════════════════════════════════════════════════════════════════
-- M2, second slice — a buyer's own rows (BRD FR020–FR024)
--
-- The listings and the marketplace landed first; these are the two things a buyer does with them. Both were
-- deliberately held back until the consent store existed, because the second one sends messages.
--
-- <h2>Keyed on the person, like consent and for the same reason</h2>
--
-- Saving a house is something a natural person does, not something an actor does. A buyer who is also a
-- seller's listing manager is house-hunting either way, and hiding their shortlist when they switch profiles
-- to do their job would be a bug rather than isolation. The visibility rule is `user_id = the signed-in
-- person`, which is the rule {@code AuthContext.requireUserId} exists to serve — no TenantScope, because a
-- shortlist has no organisation.
-- ═════════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE saved_listings (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id     BIGINT       NOT NULL REFERENCES users (id),
    property_id BIGINT       NOT NULL REFERENCES properties (id),
    -- The public handle, copied. A saved row survives its listing being withdrawn, and the reference is what
    -- the buyer would quote when asking what happened to it.
    reference   VARCHAR(16)  NOT NULL,

    -- A snapshot, in the plan's sense of the word: what the listing said at the moment it was saved. The
    -- card renders live figures by joining to `properties` — a shortlist showing last month's price would be
    -- worse than useless — and falls back to these only when the listing is no longer public, so the buyer
    -- sees "the 3-bed in Kilimani you saved is no longer listed" rather than a blank row.
    title_snapshot    VARCHAR(255),
    price_snapshot    NUMERIC(15, 2),
    currency_snapshot VARCHAR(3),
    town_snapshot     VARCHAR(64),
    image_snapshot    VARCHAR(512),

    -- The buyer's own words: "school run", "ask about the service charge". Nobody else ever reads it.
    note        TEXT,

    saved_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(64),

    CONSTRAINT uk_saved_listing UNIQUE (user_id, property_id)
);

CREATE INDEX idx_saved_listings_user ON saved_listings (user_id, saved_at DESC);
CREATE INDEX idx_saved_listings_property ON saved_listings (property_id);

COMMENT ON TABLE saved_listings IS
    'A person''s shortlist. Un-saving deletes the row: this is the one table in the schema without the soft '
        'lifecycle, because a bookmark somebody removed should stop existing rather than linger as an '
        'archived row nobody can see and the unique index still collides with.';

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- Saved searches, which are alerts.
--
-- <h2>The criteria are the columns the marketplace already filters on</h2>
--
-- Not a JSON blob of "whatever the client sent". The dispatcher has to re-run the search server-side, and a
-- stored blob would be a second parser for the same query — one that drifts from the endpoint's own the first
-- time a facet is added. These columns are the fields of PublicSearchRequest, one for one.
--
-- <h2>Delivery is decided by consent, not by a channel column here</h2>
--
-- There is deliberately no `channel` on this table. Which way an alert arrives is a fact about the person's
-- standing instruction to be contacted (the consent store), not about this particular search — and a channel
-- stored here could contradict the consent store the moment somebody opts out, with the alert winning. The
-- dispatcher resolves channels at send time, every time.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE search_alerts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id         BIGINT       NOT NULL REFERENCES users (id),
    name            VARCHAR(120) NOT NULL,

    -- The criteria, mirroring PublicSearchRequest.
    search_term     VARCHAR(255),
    property_type   VARCHAR(32),
    county          VARCHAR(64),
    town            VARCHAR(64),
    min_price       NUMERIC(15, 2),
    max_price       NUMERIC(15, 2),
    min_bedrooms    SMALLINT,
    max_bedrooms    SMALLINT,
    green_only      BOOLEAN      NOT NULL DEFAULT false,

    -- INSTANT is "as soon as the dispatcher next runs", not literally on publication: a poll the buyer cannot
    -- tell apart from a push, without a queue to operate.
    frequency       VARCHAR(16)  NOT NULL DEFAULT 'DAILY',

    -- Where the window starts. Only listings published after this are ever reported, so an alert created
    -- today does not open with a hundred listings the buyer has already scrolled past.
    last_run_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    next_run_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_match_count INTEGER     NOT NULL DEFAULT 0,
    total_sent      INTEGER      NOT NULL DEFAULT 0,
    -- Why the last run sent nothing, when it sent nothing for a reason worth showing the buyer: chiefly
    -- NO_CONSENT, which is the one they can do something about.
    last_outcome    VARCHAR(32),

    -- The usual soft lifecycle: pausing an alert is status 4, archiving it 5. Unlike a shortlist entry, an
    -- alert is a standing instruction — "when did they stop asking to be told" is a question that gets asked.
    status          INTEGER      NOT NULL DEFAULT 1,
    status_flag     VARCHAR(32)  NOT NULL DEFAULT 'Active',

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      VARCHAR(64),
    updated_by      VARCHAR(64),

    CONSTRAINT ck_search_alert_frequency CHECK (frequency IN ('INSTANT', 'DAILY', 'WEEKLY')),
    CONSTRAINT ck_search_alert_price CHECK (max_price IS NULL OR min_price IS NULL OR max_price >= min_price),
    CONSTRAINT ck_search_alert_beds CHECK (max_bedrooms IS NULL OR min_bedrooms IS NULL
        OR max_bedrooms >= min_bedrooms)
);

CREATE INDEX idx_search_alerts_user ON search_alerts (user_id, created_at DESC);
-- The dispatcher's only query: what is due. Partial, because everything paused or archived is permanently
-- not due and an index carrying it would be mostly rows the poll skips.
CREATE INDEX idx_search_alerts_due ON search_alerts (next_run_at)
    WHERE status NOT IN (4, 5);

ALTER TABLE search_alerts ADD COLUMN search_text text
    GENERATED ALWAYS AS (
        lower(coalesce(name, '') || ' ' || coalesce(search_term, '') || ' ' ||
              coalesce(property_type, '') || ' ' || coalesce(county, '') || ' ' || coalesce(town, ''))
    ) STORED;
CREATE INDEX idx_search_alerts_search_trgm ON search_alerts USING gin (search_text public.gin_trgm_ops);
