-- ═════════════════════════════════════════════════════════════════════════════════════════════════
-- Where every payment Pesi tells us about lands
--
-- The reconciliation surface, kept separate from `booking_payments` on purpose. A statement is "Pesi says
-- money arrived"; a payment is "this booking has been paid". Most of the time those are the same event, and
-- the whole value of this table is the times they are not: a mistyped reference, a walk-in payer, a deposit
-- against a unit that was cancelled last week.
--
-- <h2>Store first, match second, and never make Pesi retry</h2>
--
-- The guide is explicit: no match → insert UNMAPPED anyway and still return success. A retry does not help,
-- because the reference will be just as wrong next time, and each retry is another chance to double-post. So
-- the only thing that must succeed in the handler is writing the row. Matching is best-effort on top of it.
--
-- <h2>Two tiers of catalogue, plus an owner the guide does not mention</h2>
--
-- `pesi_super_types` is "what does this Pesi code mean"; `pesi_payment_methods` is "which of our accounts does
-- it settle to". That separation is the guide's §4.1, and it means a new till is a config row rather than a
-- deploy.
--
-- The column the guide has no reason to mention is the **owner** on each method. This platform is one Pesi
-- business with many tills, each assigned to whoever collects on it — the bank for its own developments, a
-- developer for theirs. An inbound notification carries `accountIdentifier`, which resolves the till, which
-- resolves whose money it is. Nobody needs their own API key and the platform never holds the money.
-- ═════════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE pesi_super_types (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- The Pesi code, e.g. BUNI_IPN_TILL. Theirs, not ours; not translated.
    code                    VARCHAR(48)  NOT NULL UNIQUE,
    name                    VARCHAR(120) NOT NULL,
    /*
     * STK_PUSH | IPN | FT | QUERY | BILLER.
     *
     * Which of the guide's rows applies, and therefore what a form should ask for. Only IPN is used today —
     * the rest are here because the catalogue is worthless if it only holds the codes already in use.
     */
    category                VARCHAR(24)  NOT NULL,

    requires_phone          BOOLEAN      NOT NULL DEFAULT false,
    requires_account_number BOOLEAN      NOT NULL DEFAULT false,

    status                  INTEGER      NOT NULL DEFAULT 1,
    status_flag             VARCHAR(32)  NOT NULL DEFAULT 'Active',
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by              VARCHAR(64),
    updated_by              VARCHAR(64),

    CONSTRAINT ck_pesi_category CHECK (category IN ('STK_PUSH', 'IPN', 'FT', 'QUERY', 'BILLER'))
);

-- The five inbound codes from the guide's §3. One handler serves all of them; this is what lets a payload
-- naming one of them be recognised without an if/else over magic strings.
INSERT INTO pesi_super_types (code, name, category, created_by) VALUES
    ('DARAJA_C2B',            'M-Pesa paybill or till',  'IPN', 'migration'),
    ('BUNI_IPN_ACCOUNT',      'KCB account credit',      'IPN', 'migration'),
    ('BUNI_IPN_TILL',         'KCB till credit',         'IPN', 'migration'),
    ('COOP_BANK_IPN_ACCOUNT', 'Co-op account credit',    'IPN', 'migration'),
    ('EQUITY_IPN',            'Equity account credit',   'IPN', 'migration');

CREATE TABLE pesi_payment_methods (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    super_type_id       BIGINT       NOT NULL REFERENCES pesi_super_types (id),
    /*
     * The till, paybill, operator code or bank account, exactly as registered with Pesi.
     *
     * This is what an inbound `accountIdentifier` is looked up against, so a mismatch here is a payment that
     * cannot be placed. Unique across live rows for that reason: two rows claiming one till would make whose
     * money it is ambiguous, and the answer would depend on row order.
     */
    account_number      VARCHAR(64)  NOT NULL,
    account_name        VARCHAR(160) NOT NULL,

    /*
     * Whose money arrives here. Exactly one, or neither for a platform-operated till.
     *
     * The column the guide has no reason to mention, and the one that makes one Pesi business serve many
     * collecting parties. Without it every payment would belong to the platform and somebody would have to
     * work out afterwards who it was really for.
     */
    tenant_id           BIGINT,
    institution_id      BIGINT,

    status              INTEGER      NOT NULL DEFAULT 1,
    status_flag         VARCHAR(32)  NOT NULL DEFAULT 'Active',
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          VARCHAR(64),
    updated_by          VARCHAR(64),

    CONSTRAINT ck_pesi_method_owner CHECK ((institution_id IS NULL) OR (tenant_id IS NULL))
);

CREATE UNIQUE INDEX uk_pesi_method_account ON pesi_payment_methods (account_number)
    WHERE status <> 5;
CREATE INDEX idx_pesi_method_tenant ON pesi_payment_methods (tenant_id) WHERE tenant_id IS NOT NULL;

-- ── the statements ───────────────────────────────────────────────────────────────────────────────

CREATE TABLE pesi_statements (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    /*
     * Pesi's own identifier for the transaction, and the idempotency key.
     *
     * UNIQUE, and that is the whole defence against a double-post. Pesi retries anything it does not get a
     * clean answer to within thirty seconds, and a timeout on our side looks identical to a refusal on theirs
     * — so the same money arrives twice and the second one must be recognised as the first. A service-level
     * "have I seen this?" loses that race exactly the way the booking check does.
     */
    ref_no              VARCHAR(64)  NOT NULL,
    trace_id            VARCHAR(64),
    /** Our own reference, returned to Pesi as the RRN. Generated once and kept, so a retry echoes the same. */
    our_reference       VARCHAR(16)  NOT NULL UNIQUE,

    trans_type          VARCHAR(48)  NOT NULL,
    payment_method_id   BIGINT       REFERENCES pesi_payment_methods (id),
    account_identifier  VARCHAR(64),

    -- What the payer typed. The reason this table exists is that this is often wrong.
    reference           VARCHAR(64),

    amount              NUMERIC(15, 2) NOT NULL,
    currency            VARCHAR(3)   NOT NULL DEFAULT 'KES',
    phone_no            VARCHAR(32),
    customer_name       VARCHAR(160),
    paid_at             TIMESTAMPTZ,

    /*
     * The payload as it arrived, for audit.
     *
     * JSONB rather than TEXT so a reconciliation query can reach a field the normalised columns do not carry.
     * It holds a name and a phone number, which is why the endpoint that writes it is annotated
     * @SkipRequestLog: the same data must not also go to the request log.
     */
    raw_payload         JSONB,

    /*
     * MAPPED   — attached to a booking payment
     * UNMAPPED — arrived, stored, and waiting for a person
     * IGNORED  — a person decided it is not ours (a test transaction, a duplicate Pesi itself resent)
     */
    state               VARCHAR(16)  NOT NULL DEFAULT 'UNMAPPED',
    mapped_payment_id   BIGINT       REFERENCES booking_payments (id),
    mapped_booking_id   BIGINT       REFERENCES unit_bookings (id),
    mapped_at           TIMESTAMPTZ,
    mapped_by           VARCHAR(64),
    /** Why it could not be placed automatically, in words a person can act on. */
    unmapped_reason     TEXT,

    tenant_id           BIGINT,
    institution_id      BIGINT,

    status              INTEGER      NOT NULL DEFAULT 1,
    status_flag         VARCHAR(32)  NOT NULL DEFAULT 'Active',
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          VARCHAR(64),
    updated_by          VARCHAR(64),

    CONSTRAINT ck_pesi_state CHECK (state IN ('MAPPED', 'UNMAPPED', 'IGNORED')),
    CONSTRAINT ck_pesi_amount CHECK (amount <> 0),
    CONSTRAINT ck_pesi_owner CHECK ((institution_id IS NULL) OR (tenant_id IS NULL)),
    -- A mapped statement points at the payment it became. Said here so the two cannot drift apart.
    CONSTRAINT ck_pesi_mapped CHECK (
        (state <> 'MAPPED') OR (mapped_payment_id IS NOT NULL AND mapped_at IS NOT NULL))
);

-- The idempotency key. See the column comment: this is the defence, not the check in the service.
CREATE UNIQUE INDEX uk_pesi_ref_no ON pesi_statements (ref_no) WHERE status <> 5;

-- The ops screen's query: what is waiting for a person, oldest first, because the oldest is the one somebody
-- is already chasing.
CREATE INDEX idx_pesi_unmapped ON pesi_statements (created_at)
    WHERE state = 'UNMAPPED' AND status <> 5;
CREATE INDEX idx_pesi_tenant ON pesi_statements (tenant_id, created_at DESC) WHERE tenant_id IS NOT NULL;
-- Searching by what the payer typed, and by their phone, which is how an unmapped row is usually resolved.
CREATE INDEX idx_pesi_reference ON pesi_statements (reference) WHERE reference IS NOT NULL;
CREATE INDEX idx_pesi_phone ON pesi_statements (phone_no) WHERE phone_no IS NOT NULL;

COMMENT ON TABLE pesi_statements IS
    'Every payment Pesi tells us about, matched or not. Separate from booking_payments because "money '
    'arrived" and "this booking has been paid" are the same event most of the time, and the value of this '
    'table is the times they are not.';
