-- pg_trgm's operator class, wherever the extension lives.
-- An extension exists once per database, in one schema, and on a shared server that schema is whichever
-- application installed it first — public on one machine, another application's schema on the next. Rather
-- than guess, look it up and put it on this transaction's search path; Flyway runs the whole script in one
-- transaction, so every gin_trgm_ops below resolves. Installs it into our own schema if nobody has yet.
DO $$
DECLARE ext_schema text;
BEGIN
    SELECT n.nspname INTO ext_schema
      FROM pg_extension e JOIN pg_namespace n ON n.oid = e.extnamespace
     WHERE e.extname = 'pg_trgm';
    IF ext_schema IS NULL THEN
        EXECUTE 'CREATE EXTENSION pg_trgm';
        ext_schema := current_schema();
    END IF;
    EXECUTE format('SET LOCAL search_path TO %I, %I', current_schema(), ext_schema);
END $$;

-- ═════════════════════════════════════════════════════════════════════════════════════════════════
-- Phase 3 / M6 — auction (BRD UC006, plan §4)
--
-- <h2>Isolation is the design, not a filter</h2>
--
-- UC006 requires that auction property never appears in buyer search. The plan says that exclusion "is a
-- different query path, not a flag" — and this schema is what makes that true: an auction lot is a row in
-- its own table, not a `properties` row with a marker on it.
--
-- A flag would have meant every public query on `properties` remembering to exclude it, forever, including
-- the ones nobody has written yet. Here the marketplace *cannot* return a lot, because a lot is not in the
-- table the marketplace reads. The two surfaces share a schema and nothing else.
--
-- <h2>Why a lot is not a listing</h2>
--
-- It is also honestly a different thing. A listing has an asking price and an owner who wants to sell; a lot
-- has a guide price, a reserve nobody outside the room may see, a date, a venue, an auctioneer with a
-- licence, and usually a lender exercising a power of sale. Modelling one as a state of the other would
-- have meant a dozen columns that are null for every listing and required for every lot.
-- ═════════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE auctioneers (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    reference         VARCHAR(16)  NOT NULL UNIQUE,
    name              VARCHAR(255) NOT NULL,
    firm_name         VARCHAR(255),

    -- Auctioneers Licensing Board. A lot conducted by somebody unlicensed is a sale that can be set aside.
    licence_number    VARCHAR(64),
    licence_expires_on DATE,

    contact_name      VARCHAR(160),
    contact_email     VARCHAR(128),
    contact_phone     VARCHAR(32),
    counties          TEXT,

    status            INTEGER      NOT NULL DEFAULT 1,
    status_flag       VARCHAR(32)  NOT NULL DEFAULT 'Active',

    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by        VARCHAR(64),
    updated_by        VARCHAR(64)
);

ALTER TABLE auctioneers ADD COLUMN search_text text
    GENERATED ALWAYS AS (
        lower(coalesce(reference, '') || ' ' || coalesce(name, '') || ' ' ||
              coalesce(firm_name, '') || ' ' || coalesce(licence_number, ''))
    ) STORED;
CREATE INDEX idx_auctioneer_search_trgm ON auctioneers USING gin (search_text gin_trgm_ops);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- A lot.
--
-- Note what is NOT here: no foreign key to `properties`. A lot describes its own property, because most
-- auction stock never was a marketplace listing — it is security a lender is realising, and the borrower is
-- not the one bringing it to sale.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE auction_lots (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    reference           VARCHAR(16)  NOT NULL UNIQUE,
    lot_number          VARCHAR(16),

    title               VARCHAR(255) NOT NULL,
    description         TEXT,
    property_type       VARCHAR(32)  NOT NULL,

    county              VARCHAR(64),
    town                VARCHAR(64),
    estate              VARCHAR(128),
    -- The full address IS public here, unlike a marketplace listing. A bidder has to be able to find the
    -- property to inspect it, and a public auction notice carries the address by law.
    address_line        TEXT,
    latitude            NUMERIC(9, 6),
    longitude           NUMERIC(9, 6),

    title_number        VARCHAR(64),
    plot_area_acres     NUMERIC(10, 3),
    bedrooms            SMALLINT,

    -- The guide is published; the reserve is not. Two columns because they are two different facts, and the
    -- public response record carries only the first.
    guide_price         NUMERIC(15, 2),
    reserve_price       NUMERIC(15, 2),
    currency            VARCHAR(3)   NOT NULL DEFAULT 'KES',
    -- What a bidder must lodge to be allowed to bid. Published.
    deposit_required    NUMERIC(15, 2),

    auction_date        TIMESTAMPTZ,
    venue               VARCHAR(255),
    viewing_notes       TEXT,
    terms               TEXT,

    auctioneer_id       BIGINT REFERENCES auctioneers (id),
    auctioneer_name     VARCHAR(255),

    -- Who is bringing it. A lender exercising a power of sale, or a seller consigning stock. At most one —
    -- an auction with two principals is two auctions.
    institution_id      BIGINT,
    institution_name    VARCHAR(255),
    tenant_id           BIGINT,
    tenant_name         VARCHAR(255),

    state               VARCHAR(16)  NOT NULL DEFAULT 'DRAFT',
    published_at        TIMESTAMPTZ,
    sold_price          NUMERIC(15, 2),
    sold_at             TIMESTAMPTZ,
    outcome_note        TEXT,

    primary_image_key   VARCHAR(512),

    status              INTEGER      NOT NULL DEFAULT 1,
    status_flag         VARCHAR(32)  NOT NULL DEFAULT 'Active',

    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          VARCHAR(64),
    updated_by          VARCHAR(64),

    CONSTRAINT ck_lot_principal CHECK (
        (institution_id IS NOT NULL)::int + (tenant_id IS NOT NULL)::int = 1),
    CONSTRAINT ck_lot_state
        CHECK (state IN ('DRAFT', 'SCHEDULED', 'SOLD', 'UNSOLD', 'WITHDRAWN', 'POSTPONED')),
    -- A scheduled lot has a date and an auctioneer. Both are what a public notice is.
    CONSTRAINT ck_lot_scheduled CHECK (
        state <> 'SCHEDULED'
        OR (auction_date IS NOT NULL AND auctioneer_id IS NOT NULL AND published_at IS NOT NULL)),
    CONSTRAINT ck_lot_sold CHECK (state <> 'SOLD' OR (sold_price IS NOT NULL AND sold_at IS NOT NULL)),
    CONSTRAINT ck_lot_reserve CHECK (
        reserve_price IS NULL OR guide_price IS NULL OR reserve_price >= guide_price)
);

CREATE INDEX idx_lot_institution ON auction_lots (institution_id) WHERE institution_id IS NOT NULL;
CREATE INDEX idx_lot_tenant ON auction_lots (tenant_id) WHERE tenant_id IS NOT NULL;
CREATE INDEX idx_lot_auctioneer ON auction_lots (auctioneer_id);
-- The public catalogue: scheduled, soonest first. The auction surface's own index — nothing in it is ever
-- reachable from the marketplace's.
CREATE INDEX idx_lot_public ON auction_lots (auction_date)
    WHERE state = 'SCHEDULED' AND status <> 5;
CREATE INDEX idx_lot_county ON auction_lots (county, town);

ALTER TABLE auction_lots ADD COLUMN search_text text
    GENERATED ALWAYS AS (
        lower(coalesce(reference, '') || ' ' || coalesce(lot_number, '') || ' ' ||
              coalesce(title, '') || ' ' || coalesce(description, '') || ' ' ||
              coalesce(county, '') || ' ' || coalesce(town, '') || ' ' || coalesce(estate, '') || ' ' ||
              coalesce(title_number, '') || ' ' || coalesce(auctioneer_name, ''))
    ) STORED;
CREATE INDEX idx_lot_search_trgm ON auction_lots USING gin (search_text gin_trgm_ops);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- Bidder registration.
--
-- Not bidding. The bidding happens in a room with an auctioneer, and a platform that implied otherwise
-- would be making a promise about a legal process it does not conduct. What this records is that somebody
-- asked to be allowed to bid, and whether the auctioneer approved them.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE auction_registrations (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    reference         VARCHAR(16)  NOT NULL UNIQUE,
    lot_id            BIGINT       NOT NULL REFERENCES auction_lots (id),
    lot_reference     VARCHAR(16)  NOT NULL,
    lot_title         VARCHAR(255),

    user_id           BIGINT       NOT NULL REFERENCES users (id),
    bidder_name       VARCHAR(160),
    bidder_email      VARCHAR(128),
    bidder_phone      VARCHAR(32),
    id_number         VARCHAR(64),

    -- What they say they have lodged, and whether anybody confirmed it. The platform does not take the
    -- money — the auctioneer does — so this is a claim until somebody with a licence says otherwise.
    deposit_reference VARCHAR(64),
    deposit_confirmed BOOLEAN      NOT NULL DEFAULT false,

    state             VARCHAR(16)  NOT NULL DEFAULT 'REGISTERED',
    decided_at        TIMESTAMPTZ,
    decided_by_user_id BIGINT,
    decision_note     TEXT,

    status            INTEGER      NOT NULL DEFAULT 1,
    status_flag       VARCHAR(32)  NOT NULL DEFAULT 'Active',

    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by        VARCHAR(64),
    updated_by        VARCHAR(64),

    CONSTRAINT ck_registration_state
        CHECK (state IN ('REGISTERED', 'APPROVED', 'REJECTED', 'WITHDRAWN')),
    CONSTRAINT ck_registration_decided
        CHECK (state IN ('REGISTERED', 'WITHDRAWN') OR decided_at IS NOT NULL)
);

CREATE INDEX idx_registration_lot ON auction_registrations (lot_id, created_at DESC);
CREATE INDEX idx_registration_user ON auction_registrations (user_id, created_at DESC);
-- One live registration per person per lot. Registering twice is a duplicate, not a second bidder.
CREATE UNIQUE INDEX uk_registration_live ON auction_registrations (user_id, lot_id)
    WHERE state IN ('REGISTERED', 'APPROVED') AND status <> 5;

ALTER TABLE auction_registrations ADD COLUMN search_text text
    GENERATED ALWAYS AS (
        lower(coalesce(reference, '') || ' ' || coalesce(lot_reference, '') || ' ' ||
              coalesce(bidder_name, '') || ' ' || coalesce(bidder_email, '') || ' ' ||
              coalesce(state, ''))
    ) STORED;
CREATE INDEX idx_registration_search_trgm
    ON auction_registrations USING gin (search_text gin_trgm_ops);
