-- Reminders are rules the platform sets and an organisation may tune.
--
-- A reminder is a rule: how many days before or after the thing, whether it repeats, and which catalogued
-- event it sends. The platform's row is the default; an organisation may switch a rule off or change its
-- days for its own people. "Said once" is a row per subject per rule, so nothing repeats unless the rule
-- says to. The two reminders that already existed — the hold about to lapse, a valuer's cover about to
-- run out — move onto the same table and lose their private settings.

CREATE TABLE reminder_rules (
    code               VARCHAR(40)  PRIMARY KEY,
    description        VARCHAR(255) NOT NULL,
    enabled            BOOLEAN      NOT NULL DEFAULT true,
    -- Days before the thing (a due date, an expiry, a viewing) or after it (overdue, waiting, unanswered).
    days               INTEGER      NOT NULL,
    -- Say it again every so many days while it still holds; null says it once.
    repeat_every_days  INTEGER,
    sort_order         INTEGER      NOT NULL DEFAULT 0,
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by         VARCHAR(64)
);

CREATE TABLE reminder_rule_overrides (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_code          VARCHAR(40) NOT NULL REFERENCES reminder_rules (code),
    tenant_id          BIGINT,
    institution_id     BIGINT,
    enabled            BOOLEAN,
    days               INTEGER,
    repeat_every_days  INTEGER,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by         VARCHAR(64),
    CONSTRAINT ck_reminder_override_owner CHECK ((tenant_id IS NULL) <> (institution_id IS NULL))
);
CREATE UNIQUE INDEX uk_reminder_override ON reminder_rule_overrides (rule_code, coalesce(tenant_id, 0), coalesce(institution_id, 0));

-- Said once: one row per rule, subject and key (an instalment, an expiry date, a message time).
CREATE TABLE reminder_sent (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_code     VARCHAR(40) NOT NULL,
    subject_type  VARCHAR(32) NOT NULL,
    subject_id    BIGINT      NOT NULL,
    subject_key   VARCHAR(64) NOT NULL DEFAULT '',
    sent_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    times         INTEGER     NOT NULL DEFAULT 1
);
CREATE UNIQUE INDEX uk_reminder_sent ON reminder_sent (rule_code, subject_type, subject_id, subject_key);

INSERT INTO reminder_rules (code, description, days, repeat_every_days, sort_order) VALUES
('INSTALMENT_DUE',     'An instalment falls due in so many days and is not yet covered.',           3,  NULL, 10),
('INSTALMENT_OVERDUE', 'A booking has money overdue; said so many days after, and again while it lasts.', 1, 7, 11),
('HOLD_EXPIRING',      'A hold lapses in so many days; the terms are waiting when they are.',        3,  NULL, 12),
('VIEWING_TOMORROW',   'A confirmed viewing is so many days away: the buyer and the seller''s staff.', 1, NULL, 20),
('ENQUIRY_UNANSWERED', 'A buyer''s enquiry has had no reply from the seller for so many days.',       2,  3,    21),
('APPROVAL_WAITING',   'Something has sat with a checker for so many days; said again while it does.', 2, 3,    30),
('DOCUMENT_EXPIRING',  'A document in the vault runs out in so many days.',                          30, NULL, 40),
('VALUER_LAPSE',       'A valuer''s cover or registration runs out in so many days.',                30, NULL, 41);

INSERT INTO notification_events (code, audience, purpose, subject, line, description, placeholders, sort_order) VALUES
('INSTALMENT_DUE', 'BUYER', 'TRANSACTIONAL',
 '{{amount}} due on {{when}} for {{home}}',
 'Your instalment of {{amount}} for {{home}} ({{label}}) is due on {{when}}. Quote {{payCode}} whenever you pay.',
 'A reminder before an instalment falls due.', 'home,reference,amount,when,label,payCode', 44),
('INSTALMENT_OVERDUE', 'BUYER', 'TRANSACTIONAL',
 '{{overdue}} overdue on {{home}}',
 '{{overdue}} is overdue on your booking {{reference}} for {{home}}. Quote {{payCode}} whenever you pay; get in touch if something has changed.',
 'A reminder while money is overdue on a booking.', 'home,reference,overdue,payCode', 45),
('VIEWING_TOMORROW', 'BUYER', 'TRANSACTIONAL',
 'Your viewing of {{property}} is on {{when}}',
 'A reminder: your viewing of {{property}} is on {{when}}. If you cannot make it, cancel it from your conversations so the seller knows.',
 'A reminder to the buyer before a confirmed viewing.', 'property,when,reference', 23),
('VIEWING_TOMORROW_STAFF', 'SELLER_STAFF', 'TRANSACTIONAL',
 'Viewing on {{when}}: {{property}}',
 '{{buyer}} is viewing {{property}} on {{when}}.',
 'A reminder to the seller''s staff before a confirmed viewing.', 'property,buyer,when,reference', 24),
('ENQUIRY_UNANSWERED', 'SELLER_STAFF', 'TRANSACTIONAL',
 'Unanswered: {{buyer}} about {{property}}',
 '{{buyer}} asked about {{property}} ({{reference}}) and has had no reply for {{days}} days.',
 'A buyer''s enquiry is waiting on the seller.', 'property,buyer,reference,days', 13),
('APPROVAL_WAITING', 'SELLER_STAFF', 'TRANSACTIONAL',
 'Waiting for a decision: {{subject}}',
 '{{subject}} ({{kind}}) has been waiting for your decision for {{days}} days.',
 'Something has sat with an organisation''s checker. To holders of the deciding permission.', 'subject,kind,days', 80),
('APPROVAL_WAITING_PLATFORM', 'PLATFORM_STAFF', 'TRANSACTIONAL',
 'Waiting for a decision: {{subject}}',
 '{{subject}} ({{kind}}) has been waiting for the platform''s decision for {{days}} days.',
 'Something has sat with a platform checker. To holders of the deciding permission.', 'subject,kind,days', 81),
('DOCUMENT_EXPIRING', 'SELLER_STAFF', 'TRANSACTIONAL',
 '{{document}} runs out on {{when}}',
 'Your organisation''s {{document}} in the vault runs out on {{when}}. Upload the renewed one before then.',
 'An organisation''s document is about to expire.', 'document,when', 82),
('DOCUMENT_EXPIRING_PERSON', 'BUYER', 'TRANSACTIONAL',
 '{{document}} runs out on {{when}}',
 'Your {{document}} on the platform runs out on {{when}}. Upload the renewed one before then.',
 'A person''s document is about to expire.', 'document,when', 83);
