-- pg_trgm's operator class, wherever the extension lives.
-- An extension exists once per database, in one schema, and on a shared server that schema is whichever
-- application installed it first — public on one machine, another application's schema on the next. Rather
-- than guess, look it up and put it on this transaction's search path; Flyway runs the whole script in one
-- transaction, so every gin_trgm_ops below resolves. Installs it into our own schema if nobody has yet.
--
-- This file shipped without this block and failed on a server where pg_trgm sits outside the default
-- search_path: "operator class gin_trgm_ops does not exist for access method gin" — the same failure the
-- seller-applications migration had, fixed the same way.
DO $$
DECLARE ext_schema text;
BEGIN
    SELECT n.nspname INTO ext_schema
      FROM pg_extension e JOIN pg_namespace n ON n.oid = e.extnamespace
     WHERE e.extname = 'pg_trgm';
    IF ext_schema IS NULL THEN
        EXECUTE 'CREATE EXTENSION pg_trgm';
        ext_schema := current_schema();
    END IF;
    EXECUTE format('SET LOCAL search_path TO %I, %I', current_schema(), ext_schema);
END $$;

-- ═════════════════════════════════════════════════════════════════════════════════════════════════
-- Disbursements: the bank sends money out
--
-- Not a payment. A payment is money arriving against a booking; a disbursement is the bank's own account
-- debited to pay a developer, a contractor, or whoever else the platform owes. It never touches a
-- booking, a payment or a statement, so it has its own table, its own states, and its own permissions.
--
-- <h2>Validated before it exists</h2>
--
-- A row is written only after Co-op has resolved the destination account to the name it is held in.
-- Thirteen digits carry no redundancy; the name is what a second person approves. `validated_name` is
-- therefore NOT NULL: there is no such thing as a disbursement to an account nobody has checked.
--
-- <h2>States</h2>
--
--   AWAITING_APPROVAL → APPROVED → SENDING → SENT → SUCCEEDED | FAILED
--                     → REFUSED
--
-- SENDING is the claim taken immediately before the outbound call, so a process that dies mid-call
-- leaves a row that says "we may have sent this" — which is chased with a status enquiry, never by
-- sending again. SENT is the bank's acknowledgement; the money is confirmed by callback or enquiry.
-- ═════════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE disbursements (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference               VARCHAR(16)  NOT NULL UNIQUE,

    -- Who is paid. A seller organisation on the platform, or anybody else by name.
    payee_kind              VARCHAR(24)  NOT NULL,
    tenant_id               BIGINT       REFERENCES tenants (id),
    payee_name              VARCHAR(160) NOT NULL,
    bank_code               VARCHAR(8)   NOT NULL,
    account_no              VARCHAR(32)  NOT NULL,
    -- What Co-op said the account is held in. The thing the checker approves.
    validated_name          VARCHAR(160) NOT NULL,
    validated_at            TIMESTAMPTZ  NOT NULL,

    amount                  NUMERIC(15, 2) NOT NULL,
    currency                VARCHAR(3)   NOT NULL DEFAULT 'KES',
    purpose                 VARCHAR(240) NOT NULL,
    narration               VARCHAR(160),
    -- The platform's own account the money leaves. The PesaLink payment account.
    source_account_id       BIGINT       NOT NULL REFERENCES payment_accounts (id),

    state                   VARCHAR(24)  NOT NULL DEFAULT 'AWAITING_APPROVAL',
    -- Co-op's own id for the transfer, once they give one: Destinations[0].TransactionID.
    bank_reference          VARCHAR(64),
    response_code           VARCHAR(16),
    response_description    VARCHAR(400),
    raw_response            JSONB,
    sent_at                 TIMESTAMPTZ,
    settled_at              TIMESTAMPTZ,
    callback_timeout_seconds INTEGER     NOT NULL DEFAULT 300,
    status_query_attempts   INTEGER      NOT NULL DEFAULT 0,
    processing_reason       TEXT,

    -- Maker and checker, by name, so the row reads without a join.
    made_by                 VARCHAR(64)  NOT NULL,
    checked_by              VARCHAR(64),
    checked_at              TIMESTAMPTZ,
    decision_reason         TEXT,

    status                  INTEGER      NOT NULL DEFAULT 1,
    status_flag             VARCHAR(32)  NOT NULL DEFAULT 'Active',
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by              VARCHAR(64),
    updated_by              VARCHAR(64),

    CONSTRAINT ck_disbursement_state CHECK (state IN
        ('AWAITING_APPROVAL', 'APPROVED', 'SENDING', 'SENT', 'SUCCEEDED', 'FAILED', 'REFUSED')),
    CONSTRAINT ck_disbursement_amount CHECK (amount > 0),
    CONSTRAINT ck_disbursement_payee CHECK (payee_kind IN ('SELLER_ORGANISATION', 'OTHER')),
    -- A seller organisation is named by its row; anybody else only by name.
    CONSTRAINT ck_disbursement_payee_ref CHECK (
        (payee_kind = 'SELLER_ORGANISATION' AND tenant_id IS NOT NULL)
        OR (payee_kind = 'OTHER' AND tenant_id IS NULL)),
    -- Once the bank has acknowledged, we hold their reference or a sentence saying why not.
    CONSTRAINT ck_disbursement_checked CHECK (
        state IN ('AWAITING_APPROVAL') OR checked_by IS NOT NULL)
);

-- The sweep's own order: what is out and unanswered, oldest first.
CREATE INDEX ix_disbursement_in_flight ON disbursements (sent_at)
    WHERE state IN ('APPROVED', 'SENDING', 'SENT') AND status <> 5;
CREATE INDEX ix_disbursement_state ON disbursements (state, created_at DESC) WHERE status <> 5;
CREATE INDEX ix_disbursement_bank_ref ON disbursements (bank_reference) WHERE bank_reference IS NOT NULL;

ALTER TABLE disbursements ADD COLUMN search_text TEXT GENERATED ALWAYS AS (
    lower(coalesce(reference, '')       || ' ' ||
          coalesce(payee_name, '')      || ' ' ||
          coalesce(validated_name, '')  || ' ' ||
          coalesce(account_no, '')      || ' ' ||
          coalesce(bank_reference, '')  || ' ' ||
          coalesce(purpose, ''))
) STORED;
CREATE INDEX idx_disbursement_search ON disbursements USING gin (search_text gin_trgm_ops);

COMMENT ON TABLE disbursements IS
    'Money the bank sends out — to a developer, a contractor, anybody the platform owes. Not a payment: '
    'it debits, and it never touches a booking or a statement. Validated, then approved by a second '
    'person, then sent once.';

-- The send channel is switched on now that something sends through it. Only a row still at its shipped
-- state moves; an operator who switched it off on purpose is not overruled.
UPDATE payment_types
   SET status = 1, status_flag = 'Active', updated_by = 'migration', updated_at = now()
 WHERE provider_type = 'COOP_PESALINK' AND status = 4;
